// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * ViewRelease 官方发布接口的一个可用版本（stable 或 beta 通道）。
 * MD5/Size 来自接口 files 数组（官方计算，完整性校验第一依据）。
 * 托管统一使用便携 zip 资产：根目录即 portable.ini 全便携布局，配置随目录走；
 * 安装包 exe（Inno/NSIS 系）与 .7z（需外部解压依赖）均不适合隔离托管。
 * @typedef {$models.ViewRelease} ViewRelease
 */

/**
 * ViewVersionInfo 本地已安装的果核看图版本信息。
 * 有效载荷是整个解压目录（exe + core-ui.dll/ghde.dll 解码内核 + resources/ +
 * plugins/ + portable.ini），配置 config.ini 与 exe 同目录（portable.ini 激活
 * 便携模式），版本隔离目录即完整便携实例。
 * @typedef {$models.ViewVersionInfo} ViewVersionInfo
 */
