// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - resolve/downloading/verify/extract/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * ViewRelease 官方发布接口的一个可用版本（stable 或 beta 通道）。
 * MD5/Size 来自接口 files 数组（官方计算，完整性校验第一依据）。
 * 托管统一使用便携 zip 资产：根目录即 portable.ini 全便携布局，配置随目录走；
 * 安装包 exe（Inno/NSIS 系）与 .7z（需外部解压依赖）均不适合隔离托管。
 * @typedef {Object} ViewRelease
 * @property {string} version - 归一化四段版本，如 v3.2.7.98
 * @property {string} channel - stable / beta
 * @property {boolean} isPre - beta 通道即预发布
 * @property {string} assetName - 如 GuoheView_v3.2.7.98-便携版.zip
 * @property {string} assetUrl - 官方直链（无镜像）
 * @property {number} size - 资产字节数
 * @property {string} md5 - 官方 MD5（hex 小写）
 */

/**
 * ViewVersionInfo 本地已安装的果核看图版本信息。
 * 有效载荷是整个解压目录（exe + core-ui.dll/ghde.dll 解码内核 + resources/ +
 * plugins/ + portable.ini），配置 config.ini 与 exe 同目录（portable.ini 激活
 * 便携模式），版本隔离目录即完整便携实例。
 * @typedef {Object} ViewVersionInfo
 * @property {string} version - 如 v3.2.7.98
 * @property {string} exePath - GuoheView.exe 完整路径
 * @property {string} dir - 版本隔离目录
 * @property {number} size - GuoheView.exe 大小（字节）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录（仅导入安装时有值）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
