// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Device usbipd state 的一行设备（归一化视图，直出前端）。
 * @typedef {$models.Device} Device
 */
