// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 表示下载、校验与安装阶段的实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * SnipasteRelease 表示官网可下载的 Windows x64 免安装版本。
 * @typedef {$models.SnipasteRelease} SnipasteRelease
 */

/**
 * SnipasteVersionInfo 表示一个本地隔离安装版本。
 * @typedef {$models.SnipasteVersionInfo} SnipasteVersionInfo
 */
