// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Form,
    Platform
} from "./models.js";

import * as $models from "./models.js";

/**
 * AssetNote 一条发布物的展示元数据（JSON 契约进各模块 Release.Assets）。
 * @typedef {$models.AssetNote} AssetNote
 */
