// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AssetNote 一条发布物的展示元数据（JSON 契约进各模块 Release.Assets）。
 * @typedef {Object} AssetNote
 * @property {Platform} platform
 * @property {Form} form
 * @property {string} label - 上游原始资产名（可复制/可查）
 * @property {boolean} managed - 本条是否即 Hanxi 托管所选（调用方置）
 */

/**
 * Form 发布物形态。portable=文件名有便携证据（portable/self-contained 等
 * 字样）；installer=有安装证据（setup/install 字样或安装介质扩展名）；
 * binary=可执行单文件但文件名给不出便携/安装证据（裸 .exe 两可，宁降级
 * 不猜标）；package=系统包格式（msi/deb/rpm/apk 等）；archive=纯归档；
 * meta=签名/清单/更新元数据（展示层过滤）。
 * @readonly
 * @enum {string}
 */
export const Form = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FormPortable: "portable",
    FormInstaller: "installer",
    FormBinary: "binary",
    FormPackage: "package",
    FormArchive: "archive",
    FormMeta: "meta",
};

/**
 * Platform 发布物目标平台。
 * @readonly
 * @enum {string}
 */
export const Platform = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlatformWindows: "windows",
    PlatformMacOS: "macos",
    PlatformLinux: "linux",
    PlatformAndroid: "android",
    PlatformFreeBSD: "freebsd",
    PlatformOther: "other",
};

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
