// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DdnsGoService 向前端暴露 ddns-go 版本管理、托管启停与内嵌 Web 控制台能力。
 * DNS 解析配置操作在子 Webview 窗口内的上游原生页面完成（决策记录见包注释），
 * 本服务只做托管：拉起/退出/状态/日志/端口设置，不重复实现上游功能面。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 ddnsgo:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(655054441, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(2384740153);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 true）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(3331360017);
}

/**
 * GetListenPort 返回 web 监听端口。
 * @returns {$CancellablePromise<number>}
 */
export function GetListenPort() {
    return $Call.ByID(1555310313);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(4087437255);
}

/**
 * ImportLocal 导入本地已有的 ddns-go.exe（任意目录下载的官方原版）。
 * 配置恒在 ~/.ddns_go_config.yaml 不受导入影响；仅迁移单 exe。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 文件被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.DdnsVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(3709885665, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表。
 * @returns {$CancellablePromise<version$0.DdnsVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(2761888066);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.DdnsRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(1549779361);
}

/**
 * Logs 返回实例最近 n 行进程输出（引擎重启会清空，前端另以事件流累积）。
 * @param {number} n
 * @returns {$CancellablePromise<string[] | null>}
 */
export function Logs(n) {
    return $Call.ByID(1895148448, n);
}

/**
 * OpenConfigDir 在资源管理器中定位 ddns-go 的配置文件（%USERPROFILE%\.ddns_go_config.yaml）——
 * 上游配置为单文件而非目录，直接打开整个用户主目录噪音过大，采用 /select 高亮定位。只读导航，不改写。
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfigDir() {
    return $Call.ByID(1229857660);
}

/**
 * OpenConsole 打开（或复用）内嵌 Web 控制台子窗口：
 *   - running：直接指向自有实例监听地址；
 *   - external：按候选端口（设定端口 + 上游默认 9876）探测外部 web 服务；
 *   - stopped/failed：冷启动后打开。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenConsole() {
    return $Call.ByID(1832378148);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义在文件对象上是"执行"
 * 而非"打开"（markeron「打开安装目录」按钮的事故教训：传 exe 路径直接启动了程序）。
 * 这里入参恒为目录，语义安全，但仍走本模块自有实现保持行为显式。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(3393995614, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(4205261315);
}

/**
 * Quit 退出引擎托管的 ddns-go（经配置写静默期防护后终止）。
 * external 状态不越权强杀（进程归属不在本引擎）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(3423725116);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(2851567073, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(1784058480);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(4052685341, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(1230460485, b);
}

/**
 * SetListenPort 设定端口（1024~65535，下次启动生效；运行中实例不变）。
 * @param {number} port
 * @returns {$CancellablePromise<string>}
 */
export function SetListenPort(port) {
    return $Call.ByID(1837324541, port);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 终止自有实例（强杀通道，不等待
 * 配置写静默期——OnShutdown 阻塞返回）。外部实例不受影响；自有实例另受
 * JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1048859593);
}

/**
 * Start 托管启动自有 ddns-go 实例（不弹面板）：
 * external 状态不越权接管、running 幂等直返、stopped/failed 冷启动。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function Start() {
    return $Call.ByID(1322440801);
}
