// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ControlOutcome 启动/打开控制台操作的执行结果说明。
 * @typedef {Object} ControlOutcome
 * @property {string} action - started（冷启动）/ opened（已运行直接开面板）/ external-opened（外部实例面板）/ starting（并发启动中）
 * @property {boolean} external
 * @property {string} message - 面向用户的执行说明
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {Object} QuitOutcome
 * @property {boolean} stopped - 是否真正终止了自有实例
 * @property {boolean} external - true = 当前为外部实例，未越权终止
 * @property {string} message - 面向用户的执行说明
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
