// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Relation
} from "./models.js";

import * as $models from "./models.js";

/**
 * Channel 表示一个官方发布通道。
 * @typedef {$models.Channel} Channel
 */

/**
 * Release 表示官网通道中的正式版本。
 * @typedef {$models.Release} Release
 */
