// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Channel 表示一个官方发布通道。
 * @typedef {Object} Channel
 * @property {string} key
 * @property {string} label
 * @property {string} detail
 * @property {Release[] | null} releases
 * @property {Relation} relation
 * @property {string} [relationDetail]
 */

/**
 * Relation 表示本机版本与某个官网通道目标版本的关系。
 * @readonly
 * @enum {string}
 */
export const Relation = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RelationUnknown: "unknown",
    RelationNotInstalled: "not-installed",
    RelationLatest: "latest",
    RelationUpdateAvailable: "update-available",
    RelationAhead: "ahead",
};

/**
 * Release 表示官网通道中的正式版本。
 * @typedef {Object} Release
 * @property {string} version
 * @property {string} published
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
