// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    State
} from "./models.js";

import * as $models from "./models.js";

/**
 * Snapshot 引擎状态快照，事件推送与前端渲染共用；external 态时 PID/ExePath
 * 为探针实测的外部实例事实（版本/启动时刻同样如实展示）。
 * @typedef {$models.Snapshot} Snapshot
 */
