// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    State
} from "./models.js";

import * as $models from "./models.js";

/**
 * Snapshot 引擎状态快照，事件推送与前端渲染共用；仅本引擎自有实例，无 external 态。
 * @typedef {$models.Snapshot} Snapshot
 */
