// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot 引擎状态快照，事件推送与前端渲染共用；仅本引擎自有实例，无 external 态。
 * @typedef {Object} Snapshot
 * @property {string} version
 * @property {State} state
 * @property {number} pid
 * @property {string} exePath
 * @property {number} exitCode
 * @property {string} error
 * @property {string} startedAt
 * @property {string} stoppedAt
 */

/**
 * State 引擎状态机：stopped → starting → running ⇄ quitting → (stopped | failed)。
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 未运行或已正常退出
     */
    StateStopped: "stopped",

    /**
     * 进程创建与 Job 绑定窗口
     */
    StateStarting: "starting",

    /**
     * 自有托管实例运行中
     */
    StateRunning: "running",

    /**
     * 已发关闭请求、等待退出（宽限期内）
     */
    StateQuitting: "quitting",

    /**
     * 启动失败或异常退出
     */
    StateFailed: "failed",
};

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
