// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * McpWizardService 是「AI 接入」分区的 Wails 绑定服务（装配根直挂，先例 snapshot）。
 * 无常驻业务状态：每次配置方法调用即时读盘分析，天然与外部工具并发改配置对齐。
 * 唯一的例外是安装前自检（selfcheck.go）的短 TTL 结果缓存与串行锁——它只是
 * 一次性握手的新鲜度备忘，不持有任何文件句柄或后台协程。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfirmInstall 按预览令牌执行写入链：备份 → 原子写 → 复验 → 失败回滚。
 * @param {string} clientID
 * @param {string} token
 * @returns {$CancellablePromise<$models.OpResult>}
 */
export function ConfirmInstall(clientID, token) {
    return $Call.ByID(2030391240, clientID, token);
}

/**
 * ConfirmUninstall 逆向操作：同样走备份/原子写/复验/回滚链，精确摘除自家条目。
 * @param {string} clientID
 * @param {string} token
 * @returns {$CancellablePromise<$models.OpResult>}
 */
export function ConfirmUninstall(clientID, token) {
    return $Call.ByID(3594175857, clientID, token);
}

/**
 * GetAccessInfo 单独刷新授权呈现（授权文件 ≤16KB，读放大无虞）。
 * @returns {$CancellablePromise<$models.AccessInfo>}
 */
export function GetAccessInfo() {
    return $Call.ByID(3138478511);
}

/**
 * GetStatus 探测三客户端状态 + access.json 呈现，供分区页首屏。
 * @returns {$CancellablePromise<$models.WizardStatus>}
 */
export function GetStatus() {
    return $Call.ByID(2113815631);
}

/**
 * PreviewInstall 生成对某客户端的写入预览（只读操作，不落任何盘）。
 * @param {string} clientID
 * @returns {$CancellablePromise<$models.WizardPreview>}
 */
export function PreviewInstall(clientID) {
    return $Call.ByID(1638086312, clientID);
}

/**
 * PreviewUninstall 生成摘除预览。
 * @param {string} clientID
 * @returns {$CancellablePromise<$models.WizardPreview>}
 */
export function PreviewUninstall(clientID) {
    return $Call.ByID(3959652945, clientID);
}

/**
 * SelfCheck 执行（或复用）一次安装前自检。refresh=true 忽略缓存强制重 spawn
 * （前端「重新自检」按钮）。返回的 error 仅代表编程错误，业务失败在
 * State=failed + Message 里表达——绑定面友好，前端无须 try/catch 双轨。
 * 全程互斥串行：同刻至多一个自检子进程（并发预览共用结果）。
 * @param {boolean} refresh
 * @returns {$CancellablePromise<$models.SelfCheckInfo>}
 */
export function SelfCheck(refresh) {
    return $Call.ByID(1925285191, refresh);
}
