// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccessInfo access.json 的读方视角呈现：Tools 恒等于 MCP 读者此刻的采信结果
 * （缺文件/损坏/超纲都呈现为八 false——读者 fail-closed 语义），不呈现读者不认的
 * "字面值"。写入口在本分区（SetToolAccess/ResetAccess，R6）。
 * @typedef {Object} AccessInfo
 * @property {string} path
 * @property {boolean} exists
 * @property {boolean} readable
 * @property {number} version
 * @property {AccessTools} tools
 * @property {string} note
 */

/**
 * AccessTools 授权八开关（PLAN §6 固定键名 + N32/N34 扩充批 + AI 接入批扫描族
 * portscan/lan；与 Go 侧 mcpwizard.AccessTools 手工同步，勿待再生成）。
 * @typedef {Object} AccessTools
 * @property {boolean} envcheck
 * @property {boolean} everything
 * @property {boolean} ocr
 * @property {boolean} memo
 * @property {boolean} sysinfo
 * @property {boolean} logs
 * @property {boolean} portscan
 * @property {boolean} lan
 */

/**
 * ClientState 单个客户端配置文件的状态行。State 字面量：not-installed /
 * installed / needs-repair / conflict / blocked。
 * @typedef {Object} ClientState
 * @property {string} id
 * @property {string} name
 * @property {string} format
 * @property {string} configPath
 * @property {boolean} dirExists
 * @property {boolean} configExists
 * @property {string} state
 * @property {string} detail
 * @property {boolean} canInstall
 * @property {boolean} canUninstall
 * @property {string} installedAt
 */

/**
 * DiffLine 预览差异行（绑定 DTO）。Kind：keep / add / del。
 * @typedef {Object} DiffLine
 * @property {string} kind
 * @property {string} text
 */

/**
 * OpResult 写操作结果（含回滚信息）。
 * @typedef {Object} OpResult
 * @property {boolean} success
 * @property {boolean} rolledBack
 * @property {string} backupPath
 * @property {string} message
 */

/**
 * SelfCheckInfo 安装前自检结果（Wails 绑定 DTO）。Message 恒非空：
 * 成功=结论一句话，失败=原因（指引文案由前端固定补充）。
 * @typedef {Object} SelfCheckInfo
 * @property {string} state - ok / failed
 * @property {number} toolCount - tools/list 工具数（失败为 0）
 * @property {string[] | null} tools - 工具名清单（可发现性展示）
 * @property {string} message
 * @property {string} checkedAt - 真实 spawn 时刻（RFC3339；缓存复用仍是原时刻）
 * @property {boolean} fresh - true=本次调用真 spawn；false=TTL 内缓存复用
 */

/**
 * ServerInfo MCP server 启动命令（写入客户端配置的 command/args）。
 * @typedef {Object} ServerInfo
 * @property {string} command
 * @property {string[] | null} args
 * @property {boolean} ready - exe 路径可解析才可安装
 */

/**
 * WizardPreview 安装/卸载预览。Allowed=false 时看 Reason 与 ManualSnippet；
 * Token 供确认调用回传（预览后文件被改则确认整体拒绝）。
 * @typedef {Object} WizardPreview
 * @property {string} client
 * @property {string} clientName
 * @property {string} configPath
 * @property {boolean} allowed
 * @property {boolean} zeroDiff
 * @property {boolean} willCreate
 * @property {string} reason
 * @property {string} manualSnippet
 * @property {DiffLine[] | null} diff
 * @property {string} token
 */

/**
 * WizardStatus 分区页初始状态整包。
 * @typedef {Object} WizardStatus
 * @property {ServerInfo} server
 * @property {ClientState[] | null} clients
 * @property {AccessInfo} access
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
