// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MenuItem 弹窗菜单的一个条目：复用托盘 TrayMenu 配置（同一份条目、同一套分发），
 * Index 为展示序下标，前端点击经 Launch(index) 回传。
 * @typedef {Object} MenuItem
 * @property {number} index
 * @property {string} label - 已解析显示名（自定义名缺省回退）
 * @property {string} type - exe | command | route
 * @property {string} hint - 辅助说明：exe 路径 / 命令与页面的引用键
 */

/**
 * Status 快捷菜单运行态（模块页只读展示）。
 * @typedef {Object} Status
 * @property {boolean} trapActive - 全局鼠标钩子是否在位
 * @property {number} holdMs - 触发所需按住时长（ms）
 * @property {number} moveTol - 抬手前允许的光标位移（物理像素）
 * @property {number} itemCount - 当前可用条目数（来自托盘配置中启用的条目）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
