// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QuickMenuService 鼠标快捷菜单：全局右键长按 → 光标处无边框弹窗 → 点击派发条目。
 * 条目配置与分发与托盘右键菜单完全共享（settings.TrayMenu + internal/launcher）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dismiss 收起弹窗（前端 Esc / 空背景点击调用）。
 * @returns {$CancellablePromise<void>}
 */
export function Dismiss() {
    return $Call.ByID(1801568691);
}

/**
 * GetStatus 返回快捷菜单运行态（模块页展示）。
 * @returns {$CancellablePromise<$models.Status>}
 */
export function GetStatus() {
    return $Call.ByID(484908897);
}

/**
 * Launch 执行第 index 个条目：先收起弹窗给即时反馈，派发进 goroutine，
 * 失败统一走通知 Hub（与托盘失败反馈同构）。
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function Launch(index) {
    return $Call.ByID(3874078790, index);
}

/**
 * ListItems 返回弹窗菜单条目（复用托盘配置中启用的条目，展示序即索引序）。
 * @returns {$CancellablePromise<$models.MenuItem[] | null>}
 */
export function ListItems() {
    return $Call.ByID(691642123);
}

/**
 * OpenSettings 引导至设置页托盘菜单配置区（弹窗空态的"去配置"动作），并收起弹窗。
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(3350795860);
}

/**
 * SetMainWindow 注入主窗口引用（装配根在窗口创建后调用一次）。
 * @param {application$0.WebviewWindow | null} win
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(win) {
    return $Call.ByID(3119883326, win);
}
