// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QuickMenuService 鼠标快捷菜单：全局右键长按 → 光标处弹出圆盘 → 点击扇区派发条目。
 * 条目配置与分发与托盘右键菜单完全共享（settings.TrayMenu + internal/launcher）；
 * group 分组条目在二级轮盘开启时悬停在外扩子环（StarPie 式级联外扩，见前端
 * QuickMenuPopup.vue 与 wheelGeometry.ts），关闭时子条目拍平进主盘，
 * 展示与派发共用 wheelView 保证索引一致。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dismiss 收起弹窗（前端 Esc / 空背景点击调用的 RPC 导出版：接统一调用门），并武装空闲销毁。
 * @returns {$CancellablePromise<void>}
 */
export function Dismiss() {
    return $Call.ByID(1801568691);
}

/**
 * GetStatus 返回快捷菜单运行态（模块页展示 + 二级轮盘开关回显）。
 * @returns {$CancellablePromise<$models.Status>}
 */
export function GetStatus() {
    return $Call.ByID(484908897);
}

/**
 * GetTriggerConfig 返回当前生效触发参数（钳制后，模块页表单初值）。
 * @returns {$CancellablePromise<[number, number]>}
 */
export function GetTriggerConfig() {
    return $Call.ByID(1139089451);
}

/**
 * GetTwoTier 返回二级轮盘开关状态（模块页独立读取用）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetTwoTier() {
    return $Call.ByID(1518657311);
}

/**
 * Launch 按展示序路径派发条目：[i] 主盘第 i 个扇区；[i, j] 主盘分组 i 的第 j 个
 * 子条目（二级轮盘关闭时后端已拍平，前端只会传一元路径，二元路径被拍平结构自然
 * 拒绝）。与 ListItems 共用 wheelView，索引一致。先收起弹窗给即时反馈，派发进
 * goroutine，失败统一走通知 Hub（与托盘失败反馈同构）。
 * @param {number[] | null} path
 * @returns {$CancellablePromise<void>}
 */
export function Launch(path) {
    return $Call.ByID(3874078790, path);
}

/**
 * ListItems 返回弹窗菜单条目树（复用托盘配置中启用的条目，展示序即索引序；
 * 二级轮盘关闭时 group 已被拍平，树只有一层）。
 * @returns {$CancellablePromise<$models.MenuItem[] | null>}
 */
export function ListItems() {
    return $Call.ByID(691642123);
}

/**
 * OpenSettings 引导至设置页托盘菜单配置区（弹窗空态的"去配置"动作），并收起弹窗。
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(3350795860);
}

/**
 * SetMainWindow 注入主窗口引用（装配根在窗口创建后调用一次）。
 * 装配布线: Go 直调路径,不得依赖运行态(见 ADR-0001 Wave 3 注记)——不接调用门。
 * @param {application$0.WebviewWindow | null} win
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(win) {
    return $Call.ByID(3119883326, win);
}

/**
 * SetTriggerConfig 保存触发参数并热重启鼠标钩子（N5-C2）。入参先钳进合法域再落盘
 * ——越界不报错回显钳后值（数值输入框防呆口径，与字号族一致）；store 不可用如实拒。
 * @param {number} holdMs
 * @param {number} movePx
 * @returns {$CancellablePromise<[number, number]>}
 */
export function SetTriggerConfig(holdMs, movePx) {
    return $Call.ByID(4189661119, holdMs, movePx);
}

/**
 * SetTwoTier 保存二级轮盘开关：开启时分组扇区点击展开子盘，关闭时分组子条目
 * 拍平进主盘。热生效——弹窗每次唤出都经 wheelView 重算，无需重启。
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetTwoTier(on) {
    return $Call.ByID(2743464091, on);
}
