// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ControlOutcome OpenWindow 编排回执（多实例三分支由后端裁决，UI 恒一钮）。
 * @typedef {Object} ControlOutcome
 * @property {string} action - started / focused / external-focused / starting
 * @property {boolean} external - true = 本轮面对的是外部自行启动的实例
 * @property {string} message
 */

/**
 * QuitOutcome 退出请求结果（自有实例或按 N3 分档处置的外部实例）。
 * Action="confirm-required" 表示 confirm-force 档首入未获授权，前端弹全局
 * 确认框后携 confirm=true 重入（vscode 安装闸同款往返契约）。
 * @typedef {Object} QuitOutcome
 * @property {boolean} stopped
 * @property {boolean} forced
 * @property {boolean} closeRequested
 * @property {string} method
 * @property {boolean} external
 * @property {string} [action]
 * @property {string} message
 * @property {string} [risk] - Risk 非空 = 需要用户知情确认的风险文案（confirm-required 时送达 UI）。
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
