// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} form - portable/installer
 * @property {string} stage - resolve/downloading/verify/extract/install/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * InstalledInfo 安装版（本机唯一一份，含用户自行安装的）探测信息。
 * 安装位置与版本均来自 HKCU 卸载注册表（用户安装时可选任意目录，
 * 实测存在自定义到非默认位置的情况，路径必须以注册表为准）。
 * @typedef {Object} InstalledInfo
 * @property {boolean} installed - 注册表命中且 Code.exe 存在
 * @property {string} version - DisplayVersion（如 1.136.1，缺省回退 PE 资源）
 * @property {string} dir - InstallLocation（规范化，无尾分隔符）
 * @property {string} exePath - <dir>\Code.exe
 */

/**
 * Release 远程可下载的 VS Code 版本（Windows x64）。
 * @typedef {Object} Release
 * @property {string} version - 纯语义版本如 1.136.1（VS Code 无 v 前缀）
 * @property {string} commit - 构建 commit（40 位 hex，下载直链含于路径）
 * @property {string} downloadUrl - 官方 CDN 直链（解析自版本化重定向）
 * @property {number} size - 字节数（HEAD 实测，防截断）
 * @property {string} assetName - 如 VSCode-win32-x64-1.136.1.zip / VSCodeUserSetup-x64-1.136.1.exe
 * @property {string} sha256 - SHA256 官方哈希（feed 更新清单 sha256hash）。上游仅对"最新版"发布官方 哈希（feed 恒返最新清单），旧版恒为空——下载时降级三层完整性校验。
 */

/**
 * VersionInfo 本地便携版已安装版本信息（versions/vscode_X.Y.Z/）。
 * @typedef {Object} VersionInfo
 * @property {string} version - 如 1.136.1
 * @property {string} exePath - Code.exe 完整路径（版本隔离目录根）
 * @property {string} dir - 版本隔离目录
 * @property {number} size - Code.exe 大小（字节）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录（仅导入安装时有值）
 * @property {boolean} verified - 安装时是否经官方 sha256 校验（仅最新版可得）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
