// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DouzyService 向前端暴露「抖音下载器」(Douzy) 的版本管理与安装包下载能力。
 * 刻意窄于 ccswitch/rustdesk 等托管模块：本模块**不做进程托管**——
 * 仅"列版本 → 下载官方安装包 → sha256 校验 → 拉起上游安装向导（发射后不管）"。
 * 原因见 version 包注释：桌面版内测、Electron 壳闭源、Windows 仅 NSIS 安装版。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

/**
 * DownloadVersion 后台下载指定版本安装包：立即返回，全程经事件 douzy:version-download 推送进度。
 * 返回 "started" / "in-progress" / "already-installed"，语义与 ccswitch 对齐供前端复用。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(1256348047, targetVersion);
}

/**
 * LaunchInstaller 拉起指定版本已下载安装包的上游安装向导（NSIS，交互式）。
 * 与托管引擎无关：不 Wait、不绑 JobObject、不探测生命周期——UAC 授权与向导
 * 全程由用户操作，Hanxi 只负责"把包交出去"。安装结果本模块无从得知（壳闭源）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function LaunchInstaller(targetVersion) {
    return $Call.ByID(3578811954, targetVersion);
}

/**
 * ListInstalledVersions 获取本地已下载安装包列表（按版本数值降序，最新在前）。
 * @returns {$CancellablePromise<version$0.DouzyVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(50960352);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存，按上游发布顺序新在前）。
 * @returns {$CancellablePromise<version$0.DouzyRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(118112511);
}

/**
 * OpenDir 在资源管理器中打开安装包所在隔离目录（"打开位置"按钮）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义是"执行"而非"打开"
 * （markeron「打开安装目录」事故教训）。这里入参恒为目录，语义安全。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(3889400716, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(2741787597);
}

/**
 * RemoveVersion 删除指定版本的已下载安装包目录。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(3938457835, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(127084514);
}
