// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CheckItem 单条体检项。
 * @typedef {Object} CheckItem
 * @property {string} key
 * @property {string} label
 * @property {string} state - ok | warn | bad | info
 * @property {string} value - 机器值摘要（mono 展示）
 * @property {string} detail - 结论/修正建议
 */

/**
 * Distro 单个已安装发行版的运行现状（wsl -l -v 表行）。
 * @typedef {Object} Distro
 * @property {string} name
 * @property {boolean} default
 * @property {string} state - 原文透传（Running/正在运行、Stopped/已停止…）
 * @property {string} version
 */

/**
 * DistroOption 官方在线可安装发行版清单项（wsl --list --online）。
 * @typedef {Object} DistroOption
 * @property {string} id
 * @property {string} label
 */

/**
 * Report 就绪性体检总报告（GetReadiness 载荷）。
 * @typedef {Object} Report
 * @property {string} verdict
 * @property {string} verdictTitle
 * @property {string} verdictDetail
 * @property {CheckItem[] | null} checks
 * @property {string} wslVersion
 * @property {Distro[] | null} distros
 * @property {string} collectedAt
 * @property {boolean} vmPlatformEnabled - VMPlatformEnabled 供前端状态驱动"开启/关闭虚拟机平台"按钮形态切换。
 * @property {string} machineArch - MachineArch 本机包架构口径（x64 / arm64，未知原样小写）： 供 MSI 列表自动标记与排序"本机首选"，避免用户在 x64 机器上纠结 ARM 包。
 * @property {boolean} rebootPending - RebootPending 系统真有组件变更欠着重启（引导条的唯一驱动源，操作语境不配说话）。
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
