// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 表示下载、校验与安装阶段的实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version
 * @property {string} stage
 * @property {number} done
 * @property {number} total
 * @property {string} message
 */

/**
 * SnipasteRelease 表示官网可下载的 Windows x64 免安装版本。
 * @typedef {Object} SnipasteRelease
 * @property {string} version
 * @property {string} published
 * @property {boolean} isPre
 * @property {string} assetName
 * @property {string} assetUrl
 * @property {number} size
 * @property {string} officialHash
 * @property {string} hashAlgorithm
 * @property {boolean} stale
 */

/**
 * SnipasteVersionInfo 表示一个本地隔离安装版本。
 * @typedef {Object} SnipasteVersionInfo
 * @property {string} version
 * @property {string} exePath
 * @property {string} dir
 * @property {number} size
 * @property {string} installedAt
 * @property {boolean} isImport
 * @property {string} source
 * @property {string} packageSha256
 * @property {string} verificationMode
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
