// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as MemoService from "./memoservice.js";
export {
    MemoService
};

import * as $models from "./models.js";

/**
 * MemoFilter 检索与过滤条件
 * @typedef {$models.MemoFilter} MemoFilter
 */

/**
 * MemoItem 便签核心数据模型
 * @typedef {$models.MemoItem} MemoItem
 */

/**
 * MemoStats 便签统计与标签云数据
 * @typedef {$models.MemoStats} MemoStats
 */
