// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 是暴露给前端的基础服务：
 * 应用信息、模块清单与导航（扩展注入的入口）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as extapi$0 from "../extapi/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.AppInfo>}
 */
export function GetAppInfo() {
    return $Call.ByID(2798046905);
}

/**
 * GetNavs 返回前端左侧导航（核心 + 已启用扩展）。
 * @returns {$CancellablePromise<extapi$0.NavEntry[] | null>}
 */
export function GetNavs() {
    return $Call.ByID(3041244904);
}

/**
 * ListModules 返回模块清单与启用状态（设置页）。
 * @returns {$CancellablePromise<extapi$0.ModuleInfo[] | null>}
 */
export function ListModules() {
    return $Call.ByID(911257607);
}

/**
 * SetModuleEnabled 设置页开关模块；启用/禁用成功返回最新元信息。
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<extapi$0.ModuleInfo | null>}
 */
export function SetModuleEnabled(id, enabled) {
    return $Call.ByID(3713314263, id, enabled);
}
