// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AppService from "./appservice.js";
export {
    AppService
};

import * as $models from "./models.js";

/**
 * AppInfo 前端关于页/首页展示的应用信息。
 * @typedef {$models.AppInfo} AppInfo
 */
