// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AppService from "./appservice.js";
export {
    AppService
};

import * as $models from "./models.js";

/**
 * AppInfo 前端关于页/首页展示的应用信息。
 * @typedef {$models.AppInfo} AppInfo
 */

/**
 * GeneralSettings 前端通用设置模型
 * @typedef {$models.GeneralSettings} GeneralSettings
 */

/**
 * LogFileInfo 日志文件基本元数据
 * @typedef {$models.LogFileInfo} LogFileInfo
 */
