// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as PortKillService from "./portkillservice.js";
export {
    PortKillService
};

import * as $models from "./models.js";

/**
 * KillResult 查杀操作反馈结果
 * @typedef {$models.KillResult} KillResult
 */

/**
 * PortOccupant 端口占用实体模型
 * @typedef {$models.PortOccupant} PortOccupant
 */
