// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as PortKillService from "./portkillservice.js";
export {
    PortKillService
};

export {
    KillResult,
    PortOccupant
} from "./models.js";
