// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * KillProcess 通过安全令牌终止目标进程
 * @param {number} pid
 * @param {string} exePath
 * @param {number} startedAtUnix
 * @returns {$CancellablePromise<$models.KillResult>}
 */
export function KillProcess(pid, exePath, startedAtUnix) {
    return $Call.ByID(2649245811, pid, exePath, startedAtUnix);
}

/**
 * KillProcessElevated 触发 UAC 提权 Helper 查杀管理员进程
 * @param {number} pid
 * @returns {$CancellablePromise<$models.KillResult>}
 */
export function KillProcessElevated(pid) {
    return $Call.ByID(2779334205, pid);
}

/**
 * ListListeningPorts 列举当前系统处于 LISTEN / 占用的常见活跃端口
 * @returns {$CancellablePromise<$models.PortOccupant[] | null>}
 */
export function ListListeningPorts() {
    return $Call.ByID(3594736545);
}

/**
 * QueryPort 查询指定端口号的占用情况 (TCP + UDP)
 * @param {number} port
 * @returns {$CancellablePromise<$models.PortOccupant[] | null>}
 */
export function QueryPort(port) {
    return $Call.ByID(1324470625, port);
}
