// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * KeyvizRelease 远程 GitHub Release 中可用的 Keyviz Windows MSI 安装包。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的第一依据）。
 * @typedef {$models.KeyvizRelease} KeyvizRelease
 */

/**
 * KeyvizVersionInfo 本地已安装的 Keyviz 版本信息。
 * @typedef {$models.KeyvizVersionInfo} KeyvizVersionInfo
 */
