// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - resolve/downloading/verify/extract/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * KeyvizRelease 远程 GitHub Release 中可用的 Keyviz Windows MSI 安装包。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的第一依据）。
 * @typedef {Object} KeyvizRelease
 * @property {string} version - 如 v2.1.1
 * @property {string} published - 发布时间（RFC3339）
 * @property {boolean} isPre - 是否为预发布版本
 * @property {string} assetName - 如 keyviz_2.1.1_windows.msi
 * @property {string} assetUrl - 资产下载地址（302 到 CDN）
 * @property {number} size - 资产大小（字节）
 * @property {string} sha256 - 官方 sha256（digest 去掉前缀）
 */

/**
 * KeyvizVersionInfo 本地已安装的 Keyviz 版本信息。
 * @typedef {Object} KeyvizVersionInfo
 * @property {string} version - 如 v2.1.1
 * @property {string} exePath - keyviz.exe 完整路径（供托管启停使用）
 * @property {string} dir - 版本隔离目录
 * @property {number} size - keyviz.exe 大小（字节）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录（仅导入安装时有值）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
