// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Overview 组合本机 Node.js 探测结果与官网 LTS/Current 通道。
 * @typedef {$models.Overview} Overview
 */
