// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QuickLookService 向前端暴露 QuickLook 版本管理与托管启停能力。
 * 空格预览本身不内嵌：预览窗与插件查看器依赖上游 Manager 进程与全局键盘钩子，
 * 样式设置全在 QuickLook 自有设置窗口完成（入口=托盘左键，上游无唤窗契约）。
 * 
 * 所有业务 RPC 方法经 holder.Enter() 接入统一调用门（Wave 3）：
 * 未安装/停用/阻止模块的任何方法调用被拒，且调用在途期间停用会等待 drain。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 quicklook:version-download
 * 推送进度；同时开一笔 journal 托管事务（install 首装 / update 向已托管工具链
 * 追加版本，managed-declarative 资产形态）——journal 先落盘再副作用，进度阶段
 * 迁移逐步 Advance，收口经观察面 Handle 自动落账并广播 operation:changed
 * （与既有模块事件双通道并行，Wave 4-B 接线，ccswitch/markeron 同构）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(2133945723, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(2746915083);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 false）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(2780648843);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(607016041);
}

/**
 * ImportLocal 导入本地已解压的 QuickLook 便携目录（整套迁移）。
 * 与 ccswitch 的单 exe 导入不同：QuickLook 便携目录含原生 DLL 与 QuickLook.Plugin 插件树，
 * 且配置随 portable.lock 落此目录，故整套搬入版本隔离目录（连用户既有 .config 设置一并保留）。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe/DLL 被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.QuickLookVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(692488199, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表。
 * @returns {$CancellablePromise<version$0.QuickLookVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(3127737284);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.QuickLookRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(475410059);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 收口至 windows.RevealDir：非空与目录存在性校验及中文报错内置，explorer.exe <dir> 直启；
 * 刻意不走 explorer.exe <file> 的"执行"语义（markeron「打开安装目录」按钮的事故教训）。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(1572530384, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(3104298433);
}

/**
 * Quit 退出引擎托管的 QuickLook（优先命名管道 Quit 优雅退出，宽限后强杀兜底，
 * 理由与零残渣论证见 instance 包注释）。
 * external 状态不越权强杀（互斥体探测拿不到 PID）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(238246782);
}

/**
 * Reload 请求运行中的实例重载配置（命名管道 Reload，best-effort）。
 * @returns {$CancellablePromise<string>}
 */
export function Reload() {
    return $Call.ByID(4181300228);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(37823783, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(324111078);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(1492082391, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(2748466391, b);
}

/**
 * Shutdown RPC：经调用门取 operation lease 后执行收尾（与内部版 shutdown 同语义）。
 * 停用/阻止态下被门拒属预期——OnDestroy 路径走内部版，不经本入口。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2141242227);
}

/**
 * StartQuickLook 启动编排中枢：
 *   - stopped/failed：解析 active 版本无参启动 → 驻托盘 + 全局键盘钩子生效（资源管理器按空格即预览）；
 *   - running/starting：自有实例幂等指引（重复拉起只会弹"已在运行"框，无唤窗语义）；
 *   - external：不接管外部实例（互斥体探测拿不到 PID，且无信使可唤醒窗口）。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function StartQuickLook() {
    return $Call.ByID(1870443673);
}
