// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FrpcService 向前端暴露 frp 版本管理与项目实例管理能力
 * （M4.1 版本管理 + M4.2 项目 CRUD + M4.3 多实例运行引擎）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

/**
 * DeleteProject 删除项目（若实例在运行则先停止再移除）
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProject(id) {
    return $Call.ByID(1721709521, id);
}

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经由事件 frpc:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(667372965, targetVersion);
}

/**
 * GenerateToml 生成项目配置的 TOML 预览文本（不落盘，供编辑页展示与校验）
 * @param {domain$0.Project} p
 * @returns {$CancellablePromise<string>}
 */
export function GenerateToml(p) {
    return $Call.ByID(1281526808, p);
}

/**
 * GetProject 按 ID 查询单个项目
 * @param {string} id
 * @returns {$CancellablePromise<domain$0.Project | null>}
 */
export function GetProject(id) {
    return $Call.ByID(4232700946, id);
}

/**
 * GetProjectLogs 拉取项目实例最近日志（lastN <= 0 返回全部缓冲）。
 * @param {string} id
 * @param {number} lastN
 * @returns {$CancellablePromise<string[] | null>}
 */
export function GetProjectLogs(id, lastN) {
    return $Call.ByID(152779793, id, lastN);
}

/**
 * ImportLocalFrpc 弹窗选择本地 frpc.exe 并导入（自动探测版本号）
 * @returns {$CancellablePromise<version$0.FrpVersionInfo>}
 */
export function ImportLocalFrpc() {
    return $Call.ByID(281801248);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表
 * @returns {$CancellablePromise<version$0.FrpVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(3958550646);
}

/**
 * ListInstanceStates 返回全部项目实例状态（含已停止的历史实例）。
 * @returns {$CancellablePromise<instance$0.Snapshot[] | null>}
 */
export function ListInstanceStates() {
    return $Call.ByID(2038248270);
}

/**
 * ListProjects 返回全部 frpc 项目
 * @returns {$CancellablePromise<domain$0.Project[] | null>}
 */
export function ListProjects() {
    return $Call.ByID(100482405);
}

/**
 * ListReleases 获取远程可用版本列表（GitHub 官方源 + 镜像回退，10 分钟缓存）
 * @returns {$CancellablePromise<version$0.FrpRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(2368682045);
}

/**
 * OpenConfigDir 打开 frpc 实例配置目录（Hanxi RuntimeDir/frpc，各项目启动时生成的 TOML 落盘处）。
 * frpc 为 CLI 托管无自有用户数据，此目录即 Hanxi 侧全部可看数据；自有目录缺失时先备后打开。
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfigDir() {
    return $Call.ByID(1132256144);
}

/**
 * OpenDir 在系统文件管理器中打开 frpc.exe 所在目录。
 * @param {string} exePath
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(exePath) {
    return $Call.ByID(2994245858, exePath);
}

/**
 * ParseToml 从用户粘贴/导入的 frp TOML 配置解析回领域模型（兼容 v1.x 与 v0.x 格式）
 * @param {string} content
 * @returns {$CancellablePromise<domain$0.Project>}
 */
export function ParseToml(content) {
    return $Call.ByID(5587590, content);
}

/**
 * RemoveVersion 卸载已安装版本
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(467668509, targetVersion);
}

/**
 * SaveProject 新建或更新项目（空 ID 表示新建）
 * @param {domain$0.Project} p
 * @returns {$CancellablePromise<domain$0.Project>}
 */
export function SaveProject(p) {
    return $Call.ByID(511911899, p);
}

/**
 * Shutdown 销毁实例引擎，终止所有正在运行的 frpc 子进程
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1806515109);
}

/**
 * StartProject 启动项目实例：解析绑定版本 → 生成 TOML 落盘 → 拉起 frpc.exe 并绑定 JobObject。
 * 启动后状态/日志经事件 frpc:instance-state / frpc:instance-log 持续推送。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartProject(id) {
    return $Call.ByID(2673916718, id);
}

/**
 * StopProject 停止项目实例（幂等），并清除生成的运行时临时配置。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopProject(id) {
    return $Call.ByID(3735177428, id);
}
