// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Bili23Release 远程 GitHub Release 中可用的 Bili23 Downloader Windows x64 便携版。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的第一依据）。
 * @typedef {$models.Bili23Release} Bili23Release
 */

/**
 * Bili23VersionInfo 本地已安装的 Bili23 Downloader 版本信息。
 * 安装单元是整个目录（Bili23.exe + _pystand_static.int + script/ + runtime/ 等），
 * 用户配置恒在 %APPDATA%\Bili23 Downloader\，与安装位置无关。
 * @typedef {$models.Bili23VersionInfo} Bili23VersionInfo
 */

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */
