// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Overview 组合本机 Go 探测结果与官网受支持版本通道。
 * @typedef {$models.Overview} Overview
 */
