// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DdnsRelease 远程 GitHub Release 中可用的 ddns-go Windows x64 版本。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的第一依据，
 * 与 ccswitch 同源——GitHub 自 2024 年起全量资产带 digest）。
 * @typedef {$models.DdnsRelease} DdnsRelease
 */

/**
 * DdnsVersionInfo 本地已安装的 ddns-go 版本信息。
 * @typedef {$models.DdnsVersionInfo} DdnsVersionInfo
 */

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */
