// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PaseoService 向前端暴露 Paseo 版本管理与窗口唤起能力。
 * agent 编排操作不内嵌：打开 Paseo 自有窗口完成（界面完整、协议在 daemon 侧，
 * 内嵌重做性价比为零——决策记录见 module.go 包注释）。
 * 
 * 所有业务 RPC 方法经 holder.Enter() 接入统一调用门（Wave 3）：
 * 未安装/停用/阻止模块的任何方法调用被拒，且调用在途期间停用会等待 drain。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDesktopShortcut 在桌面为当前使用版本创建快捷方式（同名覆盖）。
 * 上游安装器才会建开始菜单项；便携托管下这是显式提供的入口。
 * @returns {$CancellablePromise<void>}
 */
export function CreateDesktopShortcut() {
    return $Call.ByID(2848965829);
}

/**
 * DownloadVersion 后台下载官方 win zip 并保布局解压到 versions/paseo_<ver>/：
 * 立即返回，全程经事件 paseo:version-download 推送进度；同时开一笔 journal
 * 托管事务（install 首装 / update 向已托管工具链追加版本，managed-declarative
 * 资产形态）——journal 先落盘再副作用，进度阶段迁移逐步 Advance，收口经观察面
 * Handle 自动落账并广播 operation:changed（与既有模块事件双通道并行，
 * Wave 4-B 接线，markeron/ccswitch 同构）。
 * 运行中不拒绝：解压目标是独立的新版本目录，不触碰在跑实例的文件。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(249361919, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定的使用版本（空串 = 自动最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(1637199631);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 false）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(3252379839);
}

/**
 * GetReleaseChannel 返回当前更新通道（stable/beta）。
 * @returns {$CancellablePromise<string>}
 */
export function GetReleaseChannel() {
    return $Call.ByID(3233831403);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(78010245);
}

/**
 * ImportLocal 导入本地 Paseo 程序目录（整套 Electron 目录拷入托管版本目录）。
 * 数据恒在 %APPDATA%\Paseo 与 ~/.paseo（与 exe 位置无关），导入不搬数据。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.PaseoVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(3730549779, srcDir);
}

/**
 * ListInstalledVersions 获取本地托管已装版本（多版本目录并存，新→旧排序）。
 * @returns {$CancellablePromise<version$0.PaseoVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(2899386512);
}

/**
 * ListReleases 获取当前通道可用版本（多镜像回退，10 分钟缓存；
 * 数据源为 GitHub releases，无本机架构 win zip 或无官方 digest 的版本不入列表）。
 * @returns {$CancellablePromise<version$0.PaseoRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(177134575);
}

/**
 * OpenDaemonHome 打开 daemon 数据主目录 ~/.paseo（持久配置、实例注册、
 * 会话与配对状态所在）。与 exe 位置无关，删托管版本不丢配对。
 * @returns {$CancellablePromise<void>}
 */
export function OpenDaemonHome() {
    return $Call.ByID(827567622);
}

/**
 * OpenDir 在资源管理器中打开指定目录（"打开位置"按钮）。
 * 收口至 windows.RevealDir：非空与目录存在性校验及中文报错内置，explorer.exe <dir> 直启；
 * 刻意不走 explorer.exe <file> 的"执行"语义（markeron 事故教训）。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(1933855484, dir);
}

/**
 * OpenElectronDataDir 打开 Electron 数据目录 %APPDATA%\Paseo（窗口状态/桌面设置）。
 * 共享数据决策下的直达入口：托管实例与自装实例同用此目录，只读导航不改写。
 * @returns {$CancellablePromise<void>}
 */
export function OpenElectronDataDir() {
    return $Call.ByID(3409068882);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(536745021);
}

/**
 * OpenWindow 窗口唤起编排中枢。Paseo 上游 second-instance 语义是
 * "再开一个新窗口"而非聚焦（main.ts 实证），故唤窗优先 Win32 直唤已有窗口，
 * 仅无窗可用时才以二次拉起请求开新窗（与 recordly 信使唤窗族不同，决策见包注释）。
 *   - external：共享数据同锁组下外部实例即全局唯一主实例，可直唤；
 *   - running：自有实例直唤；
 *   - stopped/failed：解析使用版本直接无参冷启动。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(702957685);
}

/**
 * Quit 退出引擎托管的 Paseo。
 * external 状态不越权强杀（进程名探测拿不到主进程 PID，且那是用户的实例）：
 * 仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(1781034882);
}

/**
 * RemoveVersion 卸载指定托管版本（该版本正在运行则拒绝）。
 * 用户数据（%APPDATA%\Paseo 与 ~/.paseo）恒不动——共享数据集成决策，
 * 与 recordly"卸载保数据"先例一致。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(3690309627, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(3880218834);
}

/**
 * SetActiveVersion 指定启动使用的托管版本（须已安装）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(257533795, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。开启后 Hanxi 退出将连带终止
 * Paseo 及其 daemon 上正在运行的 agent 会话——UI 提示条必须如实预告。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(2006590963, b);
}

/**
 * SetReleaseChannel 切换更新通道（beta 为上游预发布，资产完整但属尝鲜性质）。
 * @param {string} channel
 * @returns {$CancellablePromise<string>}
 */
export function SetReleaseChannel(channel) {
    return $Call.ByID(504508575, channel);
}

/**
 * Shutdown RPC：经调用门取 operation lease 后执行收尾（与内部版 shutdown 同语义）。
 * 停用/阻止态下被门拒属预期——OnDestroy 路径走内部版，不经本入口。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(382609607);
}
