// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as NotificationService from "./notificationservice.js";
export {
    NotificationService
};

export {
    Level
} from "./models.js";

import * as $models from "./models.js";

/**
 * Notification 表示一条系统/业务通知
 * @typedef {$models.Notification} Notification
 */
