// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as SnipasteService from "./snipasteservice.js";
export {
    SnipasteService
};

import * as $models from "./models.js";

/**
 * LaunchOutcome 表示一次脱管启动请求的事实性结果。
 * @typedef {$models.LaunchOutcome} LaunchOutcome
 */

/**
 * QuitOutcome 表示页面手动退出当前会话自有实例的结果。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */
