// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LaunchOutcome 表示一次脱管启动请求的事实性结果。
 * @typedef {Object} LaunchOutcome
 * @property {string} version
 * @property {string} message
 */

/**
 * QuitOutcome 表示页面手动退出当前会话自有实例的结果。
 * @typedef {Object} QuitOutcome
 * @property {boolean} stopped
 * @property {boolean} forced
 * @property {boolean} closeRequested
 * @property {string} method
 * @property {string} message
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
