// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnipasteService 面向前端的 Snipaste 托管服务：官网 zip 下载、本地导入、版本切换与会话内启停。
 * downloads 记录进行中的下载版本号（按版本去重，允许不同版本并行下载）。
 * 所有业务 RPC 方法经 holder.Enter() 接入统一调用门（Wave 3）：
 * 未安装/停用/阻止模块的任何方法调用被拒，且调用在途期间停用会等待 drain。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadVersion 异步下载：返回 "started"；目标版本已装返回 "already-installed"、
 * 同版本下载中返回 "in-progress"（不报错，前端按状态渲染）。进度经
 * "snipaste:version-download" 事件推送；首个版本装完自动设为使用版本。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(3922443105, targetVersion);
}

/**
 * GetActiveVersion 返回使用版本号，未设置时为空串（error 恒 nil，统一前端签名）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(1774103441);
}

/**
 * GetStatus 返回引擎状态快照；读取前做一次外部探针校正（瞬时枚举调用，
 * 内核在运行/启动/退出中自行短路，不会误探自家进程——external 感知为拉取式，
 * 前端定时刷新即得）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(2988675695);
}

/**
 * ImportLocal 导入本地 Snipaste 目录为托管版本；未设使用版本时自动激活导入结果。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.SnipasteVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(437028713, srcDir);
}

/**
 * Launch 启动当前使用版本（无 active 时回退最新可运行版本）。启动前复核 exe 为非空常规文件，
 * 交给 engine.Start 建身份与 Job 绑定；重复启动由 engine 拒绝。
 * @returns {$CancellablePromise<$models.LaunchOutcome>}
 */
export function Launch() {
    return $Call.ByID(2966976932);
}

/**
 * ListInstalledVersions 扫描本地已装版本目录。
 * @returns {$CancellablePromise<version$0.SnipasteVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(3807981626);
}

/**
 * ListReleases 拉取官网发布通道列表（远端缓存），网络失败返回错误。
 * @returns {$CancellablePromise<version$0.SnipasteRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(1687575689);
}

/**
 * OfficialSiteURL / OpenOfficialSite 提供 Snipaste 官网入口（error 恒 nil，统一前端签名）。
 * @returns {$CancellablePromise<string>}
 */
export function OfficialSiteURL() {
    return $Call.ByID(620077070);
}

/**
 * OpenDir 用资源管理器打开版本目录（先校验存在，explorer 自身不报错）。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(4203597366, dir);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenOfficialSite() {
    return $Call.ByID(3704778449);
}

/**
 * Quit 执行分层退出并把 engine 的 Method 归因翻译成用户文案；
 * 身份复核被拒时保留 Stopped/Method 字段返回错误，供前端精确提示"未误杀"场景。
 * 外部实例（N3 终裁 force-free 档）走 quitExternal 独立通道，不触碰自有语义。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(1164047972);
}

/**
 * RemoveVersion 删除本地版本；本会话正在运行该版本、或该版本为"当前使用版本"时拒绝。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(2367682201, targetVersion);
}

/**
 * SetActiveVersion 切换使用版本；ResolveExe 确认版本目录内主程序存在后才落盘。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(3736058005, targetVersion);
}

/**
 * ShowImages 唤起 Snipaste 贴图显隐——Snipaste 无传统主窗口，官方 `toggle-images`
 * 命令即其"唤窗"等价物（Qt 单实例转发通道，免费命令，外部/自有实例通用，
 * W1 调研 §2）。命令仅在实例已在运行时有实效，静止态先引导启动。
 * @returns {$CancellablePromise<string>}
 */
export function ShowImages() {
    return $Call.ByID(2434302400);
}
