// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(3922443105, targetVersion);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(1774103441);
}

/**
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(2988675695);
}

/**
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.SnipasteVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(437028713, srcDir);
}

/**
 * @returns {$CancellablePromise<$models.LaunchOutcome>}
 */
export function Launch() {
    return $Call.ByID(2966976932);
}

/**
 * @returns {$CancellablePromise<version$0.SnipasteVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(3807981626);
}

/**
 * @returns {$CancellablePromise<version$0.SnipasteRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(1687575689);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function OfficialSiteURL() {
    return $Call.ByID(620077070);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(4203597366, dir);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenOfficialSite() {
    return $Call.ByID(3704778449);
}

/**
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(1164047972);
}

/**
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(2367682201, targetVersion);
}

/**
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(3736058005, targetVersion);
}
