// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    State
} from "./models.js";

import * as $models from "./models.js";

/**
 * Snapshot 引擎状态快照：事件推送与前端渲染共用同一模型。external 态时
 * PID/ExePath/StartedAt 为探针实测的外部实例事实（身份不明时保持零值，
 * 呈现层如实显示"未取得身份"）。
 * @typedef {$models.Snapshot} Snapshot
 */
