// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 是暴露给前端的基础服务：
 * 应用信息、模块清单与导航（扩展注入的入口）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as extapi$0 from "../extapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearLogs 清除所有历史日志（保留当天的）
 * @returns {$CancellablePromise<void>}
 */
export function ClearLogs() {
    return $Call.ByID(3711438991);
}

/**
 * EnsureModuleActive 确保指定模块已按需完成懒初始化（在进入模块路由时调用）
 * @param {string} moduleID
 * @returns {$CancellablePromise<void>}
 */
export function EnsureModuleActive(moduleID) {
    return $Call.ByID(1002666571, moduleID);
}

/**
 * @returns {$CancellablePromise<$models.AppInfo>}
 */
export function GetAppInfo() {
    return $Call.ByID(2225764144);
}

/**
 * GetGeneralSettings 获取常规配置（开机自启、最小化托盘等）
 * @returns {$CancellablePromise<$models.GeneralSettings>}
 */
export function GetGeneralSettings() {
    return $Call.ByID(3546674934);
}

/**
 * GetNavs 返回前端左侧导航（核心 + 已启用扩展）。
 * @returns {$CancellablePromise<extapi$0.NavEntry[] | null>}
 */
export function GetNavs() {
    return $Call.ByID(3845712467);
}

/**
 * GetTrayMenu 返回当前托盘右键菜单配置条目（按保存顺序）。
 * @returns {$CancellablePromise<settings$0.TrayMenuItem[] | null>}
 */
export function GetTrayMenu() {
    return $Call.ByID(2718414818);
}

/**
 * ListLogFiles 获取日志目录下的所有日志文件列表（按时间倒序排列）
 * @returns {$CancellablePromise<$models.LogFileInfo[] | null>}
 */
export function ListLogFiles() {
    return $Call.ByID(3086177210);
}

/**
 * ListModules 返回模块清单与启用状态（设置页）。
 * @returns {$CancellablePromise<extapi$0.ModuleInfo[] | null>}
 */
export function ListModules() {
    return $Call.ByID(3944382308);
}

/**
 * ListTrayMenuOptions 返回全部可启用的托盘菜单候选项（仅收集已启用模块）。
 * @returns {$CancellablePromise<$models.TrayMenuOption[] | null>}
 */
export function ListTrayMenuOptions() {
    return $Call.ByID(1683509678);
}

/**
 * OpenHostsFile 使用系统默认记事本或编辑器打开系统的 hosts 文件
 * @returns {$CancellablePromise<void>}
 */
export function OpenHostsFile() {
    return $Call.ByID(1159345840);
}

/**
 * OpenNetworkConnections 打开系统网络连接适配器控制面板 (ncpa.cpl)
 * @returns {$CancellablePromise<void>}
 */
export function OpenNetworkConnections() {
    return $Call.ByID(2311620412);
}

/**
 * OpenPath 在系统资源管理器中打开指定目录或选中文件
 * @param {string} targetPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(targetPath) {
    return $Call.ByID(3664558816, targetPath);
}

/**
 * OpenSystemEnvSettings 打开系统环境变量设置面板
 * @returns {$CancellablePromise<void>}
 */
export function OpenSystemEnvSettings() {
    return $Call.ByID(1340710676);
}

/**
 * PickExeFile 弹出系统文件选择框选取外部程序，返回绝对路径（用户取消时为空串）。
 * @returns {$CancellablePromise<string>}
 */
export function PickExeFile() {
    return $Call.ByID(3033369884);
}

/**
 * ReadLogContent 读取指定日志文件的内容（限制最大行数避免内存溢出，默认倒序取最新行）
 * @param {string} fileName
 * @param {number} maxLines
 * @returns {$CancellablePromise<string>}
 */
export function ReadLogContent(fileName, maxLines) {
    return $Call.ByID(2663620472, fileName, maxLines);
}

/**
 * SendDelayedTestNotification 延迟指定秒数后发送通知（专用于测试最小化/后台时的 Windows 原生桌面通知气泡）
 * @param {number} delaySeconds
 * @returns {$CancellablePromise<void>}
 */
export function SendDelayedTestNotification(delaySeconds) {
    return $Call.ByID(4089895938, delaySeconds);
}

/**
 * SendTestNotification 发送一条测试通知 (用于在设置页面测试前后台通知效果)
 * @returns {$CancellablePromise<void>}
 */
export function SendTestNotification() {
    return $Call.ByID(1721883358);
}

/**
 * SetGeneralSettings 保存常规配置
 * @param {$models.GeneralSettings} gen
 * @returns {$CancellablePromise<void>}
 */
export function SetGeneralSettings(gen) {
    return $Call.ByID(381871890, gen);
}

/**
 * SetModuleEnabled 设置页开关模块；启用/禁用成功返回最新元信息。
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<extapi$0.ModuleInfo | null>}
 */
export function SetModuleEnabled(id, enabled) {
    return $Call.ByID(3661323466, id, enabled);
}

/**
 * SetTrayMenu 校验并持久化托盘菜单配置，保存成功后立即重建右键菜单热生效。
 * @param {settings$0.TrayMenuItem[] | null} items
 * @returns {$CancellablePromise<void>}
 */
export function SetTrayMenu(items) {
    return $Call.ByID(1571635758, items);
}

/**
 * SetTrayRebuilder 注入托盘菜单热重建回调，仅由装配根（app.New）在托盘创建后调用。
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetTrayRebuilder(fn) {
    return $Call.ByID(178488523, fn);
}
