// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

/**
 * ControlOutcome 控制操作（Start 起服务 / OpenWindow 打开界面）的执行结果说明。
 * action 词表照托管族（ccswitch/dbx 同名）：started（冷启动，仅 Start 出口）/
 * already-running（Start 幂等直返）/ opened（补开自有实例界面）/
 * external-opened（打开外部实例界面，恒带"非 Hanxi 托管"如实标注）/
 * starting（启动临界区，不重复动作）/ external（外部实例在场，托管不接管）。
 * 两个动词严格分工（C 线前端同口径锁定）：**OpenWindow 绝不冷启动**——起服务
 * 等于在局域网敞开分享端口，只在机主点「启动」时发生；界面没自动弹出时
 * OpenWindow 只负责补开。
 * 状态词表如实声明：A 线为五态（stopped/starting/running/failed/external），
 * 优雅停的收口相在引擎内部（stopping）对前端折并入 running，**没有 quitting 档**
 * ——前端 adapters/piik.ts 现按六态写词表，其 quitting 分支属永不到来的档，
 * 已列联编收口清单（要么前端删档，要么 A 线补档，本层不造幻影状态）。
 * @typedef {Object} ControlOutcome
 * @property {string} action
 * @property {boolean} external
 * @property {string} message - 面向用户的执行说明
 * @property {number} port - 本条回执相关的监听端口（0 = 不适用）
 * @property {string} url - 界面地址（打开界面/已运行回执携带）
 */

/**
 * PiikStatus GetStatus 复合投影：A 线实例快照 + 端口账 + 机读字段投影 +
 * 托管数据目录账 + 使用版本漂移复查。
 * 
 * 内嵌 Snapshot 经 JSON 展平，前端消费形状 = "piik:instance-state" 事件载荷
 * 再加本层投影位（两路同形，前端不必分两套读法——dbx/ccswitch 同纪律）。
 * 前提纪律如实声明：内嵌意味着 A 线快照字段会原样进前端，因此
 * **piikinstance.Snapshot 不得携带口令明文等任何秘密值**（口令只得以
 * PasswordSet 布尔形态出场）；该纪律是联编硬要求，见交付收口清单。
 * @typedef {Object} PiikStatus
 * @property {string} version
 * @property {instance$0.State} state
 * @property {number} pid
 * @property {number} exitCode
 * @property {string} error
 * @property {boolean} external - state==external 时为 true
 * @property {number} port - 本代/最近一代分配端口（0=从未启动）
 * @property {string} startedAt
 * @property {string} stoppedAt
 * @property {boolean} localAccessOpen - 上游机读字段账（stdout 逐行解析，machine.go）；实例未运行保留最近 一代终值供诊断，新一轮 Start 即清零。 "Local access: open" 命中
 * @property {boolean} passwordSet - 口令行命中且值非空（明文已弃）
 * @property {string} lanInvitation - LAN 邀请来源（原样转呈）
 * @property {string} publicInvitation - 公网邀请来源（原样转呈）
 * @property {boolean} noBrowser - GATE_NO_BROWSER 命中位
 * @property {number} listenPort - ListenPort 界面访问端口：running = 引擎记账的本代分配端口（8787 起被占 则由本层分配器上移）；external = 上游默认口（外部实例端口不可知，前端 话术"通常占着 8787"同源取此值）；stopped/failed = 最近一代端口，无账给 0。
 * @property {string} consoleUrl - ConsoleURL 本机界面地址（http://127.0.0.1:<port>/，值由 A 线 instance.URLForPort 单点组装）：**仅自有实例在跑时给值**，其余状态空串—— 前端"界面恒在浏览器"话术与 GATE_NO_BROWSER 兜底链接共用这一个字符串， 杜绝前后端两处各拼一遍。external 态不填（那个实例的端口不归本层记账， 谎报一个可点链接比不给更糟），由 OpenWindow 现场拨测候选口后代开浏览器。
 * @property {string} dataDir - DataDir / ConfigPath / LogDir 托管数据目录三账（跨版本共享、删版本不 删数据；前端"打开数据目录"与 metaHints 披露同源于此）。
 * @property {string} configPath
 * @property {string} logDir
 * @property {boolean} drifted - 使用版本 exe 发生账外漂移（只报告不处置）
 * @property {string} driftNote - 漂移/无法比对的如实明细（空 = 未复查）
 */

/**
 * QuitOutcome 退出执行结果。
 * 如实口径：piik 无自有窗口，优雅停走**上游官方通道**（stdin 写入/关闭即
 * 优雅退出），宽限后 JobObject 兜底并连带回收 cloudflared / piik-capture 孙
 * 进程。external 态（机主自行双击裸 exe 起的实例，占住 8787）绝不越权终止。
 * @typedef {Object} QuitOutcome
 * @property {boolean} stopped
 * @property {boolean} external
 * @property {string} message
 * @property {number} port - 退出后本端口已释放（0 = 不适用）
 */

/**
 * 冻结契约类型锚点（A 线 version/instance 子包公开面的本包别名）：本包业务
 * 代码只经这几个别名引用 A 面类型，收口时如需改名，改动集中在本块。
 * 现状：两侧均已落盘证实（version 侧 PiikRelease/PiikVersionInfo/DownloadProgress
 * + Manager 全套面；instance 侧 Snapshot/Options/Engine + DefaultPort/URLForPort），
 * 其中 DownloadProgress 与 Snapshot 另由装配根 app.go 的 RegisterEvent 实锁。
 * @typedef {version$0.PiikRelease} Release
 */

/**
 * 冻结契约类型锚点（A 线 version/instance 子包公开面的本包别名）：本包业务
 * 代码只经这几个别名引用 A 面类型，收口时如需改名，改动集中在本块。
 * 现状：两侧均已落盘证实（version 侧 PiikRelease/PiikVersionInfo/DownloadProgress
 * + Manager 全套面；instance 侧 Snapshot/Options/Engine + DefaultPort/URLForPort），
 * 其中 DownloadProgress 与 Snapshot 另由装配根 app.go 的 RegisterEvent 实锁。
 * @typedef {version$0.PiikVersionInfo} VersionInfo
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
