// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SubnetDeskService 向前端暴露 SubnetDesk 版本管理与启停/唤窗能力。
 * 远程桌面画面本身不内嵌（上游 GUI 完整，内嵌不可行）：
 * 连接、局域网设置（用户名/密码/CIDR 白名单/端口 21118）均在 SubnetDesk 自有窗口操作。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDesktopShortcut 在桌面为当前使用版本创建快捷方式（同名覆盖）。
 * @returns {$CancellablePromise<void>}
 */
export function CreateDesktopShortcut() {
    return $Call.ByID(1986796573);
}

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 subnetdesk:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(3811975943, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(1687989943);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 true）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(1943214455);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(694110397);
}

/**
 * ImportLocal 导入本机已有的 SubnetDesk 便携 exe（文件路径或所在目录均可）。
 * 配置恒在 %APPDATA%\SubnetDesk 不受导入影响；仅迁移 exe。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 被独占，拷贝必然失败。
 * @param {string} srcPath
 * @returns {$CancellablePromise<version$0.SDVersionInfo>}
 */
export function ImportLocal(srcPath) {
    return $Call.ByID(3457014507, srcPath);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表。
 * @returns {$CancellablePromise<version$0.SDVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(1556135992);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.SDRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(216997223);
}

/**
 * OpenConfigDir 打开 SubnetDesk 的用户数据目录（身份密钥与设置所在）——纯托管下用户想看"数据在哪"的直达入口。只读导航，不改写。
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfigDir() {
    return $Call.ByID(1130163510);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义在文件对象上是"执行"
 * 而非"打开"（markeron 事故教训）；这里入参恒为目录，语义安全。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(1570404644, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(556761061);
}

/**
 * OpenWindow 窗口唤起编排中枢（SubnetDesk 无唤窗信使，二次拉起 = 新窗口实例）：
 *   - external：EnumWindows 唤起外部便携实例窗口；驻留托盘无窗可唤时只给指引，不越权拉起；
 *   - running：优先唤起自有窗口；窗口已销毁（藏托盘）则派生新实例开窗（同 Job 托管）；
 *   - stopped/failed：解析 active 版本冷启动。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(399714349);
}

/**
 * Quit 退出引擎托管的 SubnetDesk（终止整个进程树，含被控监听端）。
 * external 状态不越权强杀：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(91288314);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(1474110115, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(4248868794);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(982722155, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(83085867, b);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 终止自有实例。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3048288383);
}
