// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WifiService Wails 绑定服务：查看本机已保存的 Wi-Fi 密码
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListProfiles 直接获取全部 WiFi 名称与明文密码
 * @returns {$CancellablePromise<$models.Profile[] | null>}
 */
export function ListProfiles() {
    return $Call.ByID(4080100221);
}
