// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WifiService Wails 绑定服务：查看本机已保存的 Wi-Fi 密码。
 * 业务方法经 holder.Enter() 接入统一调用门（Wave 3）；门拒绝如实上抛 error，
 * 禁止回空表静默消化（Wave 3 口径）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListProfiles 直接获取全部 WiFi 名称与明文密码。
 * Wave 3 口径：门拒绝如实上抛（前端以错误提示呈现），不回空表。
 * netsh 枚举失败仍按既有约定落日志回空表（"WLAN 服务/权限问题 vs 确无配置"
 * 看 slog 分辨），该语义先于调用门存在，本次不动。
 * @returns {$CancellablePromise<$models.Profile[] | null>}
 */
export function ListProfiles() {
    return $Call.ByID(4080100221);
}
