// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EarTrumpetService 是暴露给前端的 Wails Service。
 * 
 * 职责边界：只管官方直装渠道（install.eartrumpet.app）——状态检测（含
 * 运行态与商店版并存标记）、启动、退出、卸载、安装/更新。商店渠道不纳管
 * （用户拍板"商店版不要了"），检测到并存时由 UI 黄条警告。EarTrumpet 是
 * 带开机自启的常驻托盘应用：不绑定 JobObject，退出为按 PID 直接终止
 * （上游无优雅退出通道，见 Exit 注释），关闭 Hanxi 不影响 EarTrumpet。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Exit 终止正在运行的直装版进程，返回终止的进程数。
 * 
 * 上游没有任何优雅退出通道（无 CLI/IPC/唤窗协议，WM_CLOSE 只会关掉其隐藏的
 * flyout 窗口），因此退出 = 按 PID 直接终止（经 KillVerified 指纹复核防 PID
 * 复用，且只杀安装目录匹配直装渠道的进程）。这是安全的：设置保存在事务性
 * LocalSettings 容器，音量状态由系统音频栈持有。只影响当前会话——它注册了
 * 登录自启，下次登录仍会出现；真要常驻移除请卸载，Hanxi 不改它的自启注册。
 * @returns {$CancellablePromise<number>}
 */
export function Exit() {
    return $Call.ByID(2340406779);
}

/**
 * GetRemoteVersion 返回官方直装渠道当前最新版本号（10 分钟缓存，
 * 网络失败回退上次核验成功的清单）。
 * @returns {$CancellablePromise<string>}
 */
export function GetRemoteVersion() {
    return $Call.ByID(1428857165);
}

/**
 * GetStatus 查询直装渠道注册状态，并顺带检测商店版并存。
 * 
 * 每个 Query 都要冷启动一次 PowerShell 子进程（实测约 1.8s/次），两个
 * 查询并发执行把耗时压回单次延迟。
 * @returns {$CancellablePromise<$models.PackageSnapshot>}
 */
export function GetStatus() {
    return $Call.ByID(1762201583);
}

/**
 * Install 安装/更新官方直装渠道的最新版本。
 * 
 * 完整性链条：appinstaller 清单钉死包名+发布者+官方主机（TLS）→ 下载
 * appxbundle → 若 winget-pkgs 官方仓库收录同版本则交叉比对 SHA-256 →
 * Add-AppxPackage 时 Windows 校验 ACS 包签名与发布者身份。
 * 
 * 签名链条（2026-09-03 实测）：上游经 Azure Code Signing 用短时效证书
 * （约 3 天）签名并附 RFC3161 时间戳，Authenticode 视角 Valid、本地 X509
 * 链按当前时钟构建报 NotTimeValid，但实机已成功部署 2.3.0.20——Windows
 * 部署栈接受"过期证书+有效期时间戳"组合。若其他环境仍失败会映射为
 * SignatureInvalid（含 0x800B0101 CERT_E_EXPIRED）。
 * 
 * 与商店版并存会争抢单实例互斥且配置分裂，检测到 Store 版时直接拒绝。
 * @returns {$CancellablePromise<string>}
 */
export function Install() {
    return $Call.ByID(3609241834);
}

/**
 * Launch 激活已安装的直装版。
 * 
 * 不做前置 Query：脚本 activate 分支在同一 PowerShell 进程内已查包，未安装
 * 会返回 CodeNotInstalled——省掉一次 ~1.8s 的子进程冷启动。
 * 
 * 注意上游单实例语义：若已有实例在运行（含并存时的商店版实例），第二个
 * 实例会因单实例互斥静默退出且不会唤起 UI——上游没有唤窗通道。
 * @returns {$CancellablePromise<void>}
 */
export function Launch() {
    return $Call.ByID(3527213604);
}

/**
 * OpenRepo 打开 EarTrumpet 的 GitHub 项目主页。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepo() {
    return $Call.ByID(848874991);
}

/**
 * Uninstall 卸载直装版的当前用户包。
 * 
 * 风险提示：设置（热键、音量覆盖、Actions 规则等）保存在包的 LocalSettings
 * 容器内，随包卸载一并删除。
 * @returns {$CancellablePromise<void>}
 */
export function Uninstall() {
    return $Call.ByID(3331213479);
}
