// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PackageSnapshot 是直装渠道的包状态快照；StoreCoexist 标记商店版并存。
 * @typedef {Object} PackageSnapshot
 * @property {string} observedAt
 * @property {boolean} installed
 * @property {boolean} running
 * @property {string} version
 * @property {string} packageFullName
 * @property {string} architecture
 * @property {string} installLocation
 * @property {string} packageStatus
 * @property {boolean} storeCoexist
 * @property {string} storeVersion
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
