// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WechatService from "./wechatservice.js";
export {
    WechatService
};

import * as $models from "./models.js";

/**
 * @typedef {$models.AttachmentActionResult} AttachmentActionResult
 */

/**
 * InboundMessage 接收到的消息（业务实体）
 * @typedef {$models.InboundMessage} InboundMessage
 */

/**
 * OutgoingAttachmentDraft 是发送前预览所需的安全元数据；Path 仅供本地 Wails 窗口回传确认发送。
 * @typedef {$models.OutgoingAttachmentDraft} OutgoingAttachmentDraft
 */

/**
 * QRInfo 微信登录二维码信息
 * @typedef {$models.QRInfo} QRInfo
 */

/**
 * QRStatus 登录状态响应
 * @typedef {$models.QRStatus} QRStatus
 */

/**
 * WechatAccountState 微信单账号运行时状态模型
 * @typedef {$models.WechatAccountState} WechatAccountState
 */

/**
 * WechatState 模块当前运行时状态（兼容旧版接口）
 * @typedef {$models.WechatState} WechatState
 */
