// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WechatService 暴露给 Wails 前端的服务（支持多微信账号并发管理与收发路由）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckQRStatus 轮询检测二维码状态（支持传入自定义备注名创建独立账号）
 * @param {string} qrcode
 * @param {string} remarkName
 * @returns {$CancellablePromise<$models.QRStatus | null>}
 */
export function CheckQRStatus(qrcode, remarkName) {
    return $Call.ByID(2815777374, qrcode, remarkName);
}

/**
 * DeleteAccount 删除指定微信账号并停止其长轮询
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAccount(id) {
    return $Call.ByID(698820737, id);
}

/**
 * Destroy 销毁模块并彻底停止所有后台监听 Goroutine
 * @returns {$CancellablePromise<void>}
 */
export function Destroy() {
    return $Call.ByID(606446929);
}

/**
 * GetImagePreview 读取本地图片并以 Base64 Data URL 返回，供出站图片气泡内嵌缩略预览
 * （WebView 无法直读 file:// 本地路径，预览字节必须走后端通道）。
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function GetImagePreview(filePath) {
    return $Call.ByID(1937123332, filePath);
}

/**
 * GetLoginQRCode 获取微信登录二维码
 * @returns {$CancellablePromise<$models.QRInfo | null>}
 */
export function GetLoginQRCode() {
    return $Call.ByID(231563010);
}

/**
 * GetPendingMessages 取走指定账号后台积累的未读消息（消费后清空，供前端页面重新挂载时补取）
 * @param {string} accountID
 * @returns {$CancellablePromise<$models.InboundMessage[] | null>}
 */
export function GetPendingMessages(accountID) {
    return $Call.ByID(2401800150, accountID);
}

/**
 * GetState 获取全局/主账号运行时状态（兼容旧前端接口）
 * @returns {$CancellablePromise<$models.WechatState>}
 */
export function GetState() {
    return $Call.ByID(3717410300);
}

/**
 * InitOnDemand 按需懒初始化：用户进入页面或首次调用时拉起所有已配置账号的后台监听
 * @returns {$CancellablePromise<void>}
 */
export function InitOnDemand() {
    return $Call.ByID(4049363425);
}

/**
 * InspectOutgoingAttachment 校验本地附件并生成发送前预览信息。
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.OutgoingAttachmentDraft>}
 */
export function InspectOutgoingAttachment(filePath) {
    return $Call.ByID(2354370216, filePath);
}

/**
 * ListAccounts 获取所有账号及其运行时状态
 * @returns {$CancellablePromise<$models.WechatAccountState[] | null>}
 */
export function ListAccounts() {
    return $Call.ByID(1388396637);
}

/**
 * OpenInboundFile 下载微信入站文件到临时目录，并用系统默认程序打开。
 * @param {string} attachmentID
 * @returns {$CancellablePromise<$models.AttachmentActionResult>}
 */
export function OpenInboundFile(attachmentID) {
    return $Call.ByID(3639868368, attachmentID);
}

/**
 * OpenLocalImage 用系统默认查看器打开出站消息引用的本地图片。
 * 扩展名白名单前置校验，杜绝该 RPC 被借道唤起任意本地关联程序。
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function OpenLocalImage(filePath) {
    return $Call.ByID(1644573941, filePath);
}

/**
 * PickAttachmentDialog 打开统一的系统附件选择对话框；图片真实性在发送前由后端按内容嗅探。
 * @returns {$CancellablePromise<string>}
 */
export function PickAttachmentDialog() {
    return $Call.ByID(1332530701);
}

/**
 * PickFileDialog 保留旧绑定兼容；新前端统一使用 PickAttachmentDialog。
 * @returns {$CancellablePromise<string>}
 */
export function PickFileDialog() {
    return $Call.ByID(3588239546);
}

/**
 * PickImageDialog 保留旧绑定兼容；新前端统一使用 PickAttachmentDialog。
 * @returns {$CancellablePromise<string>}
 */
export function PickImageDialog() {
    return $Call.ByID(2397880461);
}

/**
 * PreviewInboundImage 下载解密入站图片附件并以 Base64 Data URL 返回，供图片气泡内嵌缩略预览。
 * 仅放行 kindImage 附件：预览通道不成为任意大文件的旁路下载器。
 * @param {string} attachmentID
 * @returns {$CancellablePromise<string>}
 */
export function PreviewInboundImage(attachmentID) {
    return $Call.ByID(174810645, attachmentID);
}

/**
 * RefreshAccountContextToken 手动拉取指定账号的 updates
 * @param {string} accountID
 * @returns {$CancellablePromise<string>}
 */
export function RefreshAccountContextToken(accountID) {
    return $Call.ByID(2850430859, accountID);
}

/**
 * RefreshContextToken 刷新主账号 Context Token（遗留兼容接口）
 * @returns {$CancellablePromise<string>}
 */
export function RefreshContextToken() {
    return $Call.ByID(1555551512);
}

/**
 * RegisterClipboardAttachment 将窗口剪贴板中的附件字节安全落到受管临时文件，供现有发送链路复用。
 * @param {string} fileName
 * @param {string} dataURL
 * @returns {$CancellablePromise<$models.OutgoingAttachmentDraft>}
 */
export function RegisterClipboardAttachment(fileName, dataURL) {
    return $Call.ByID(3491948815, fileName, dataURL);
}

/**
 * RegisterClipboardImage 保留旧绑定兼容；新前端统一使用 RegisterClipboardAttachment。
 * @param {string} fileName
 * @param {string} dataURL
 * @returns {$CancellablePromise<$models.OutgoingAttachmentDraft>}
 */
export function RegisterClipboardImage(fileName, dataURL) {
    return $Call.ByID(2721324727, fileName, dataURL);
}

/**
 * ReleaseOutgoingAttachment 仅释放由 RegisterClipboardImage 创建的受管临时文件。
 * @param {string} filePath
 * @returns {$CancellablePromise<boolean>}
 */
export function ReleaseOutgoingAttachment(filePath) {
    return $Call.ByID(2969951465, filePath);
}

/**
 * RevealLocalFile 在资源管理器中定位本地文件（「打开目录」按钮：打开所在文件夹并选中）。
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function RevealLocalFile(filePath) {
    return $Call.ByID(453175521, filePath);
}

/**
 * SaveInboundFile 弹出另存为对话框并保存微信入站文件。
 * @param {string} attachmentID
 * @returns {$CancellablePromise<$models.AttachmentActionResult>}
 */
export function SaveInboundFile(attachmentID) {
    return $Call.ByID(3285446271, attachmentID);
}

/**
 * SendFileMessage 发送文件消息（指定账号与目标）
 * @param {string} accountID
 * @param {string} toUserID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function SendFileMessage(accountID, toUserID, filePath) {
    return $Call.ByID(1037104628, accountID, toUserID, filePath);
}

/**
 * SendImageMessage 发送图片消息（指定账号与目标）
 * @param {string} accountID
 * @param {string} toUserID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function SendImageMessage(accountID, toUserID, filePath) {
    return $Call.ByID(1735217207, accountID, toUserID, filePath);
}

/**
 * SendTextMessage 发送文字消息（指定账号与目标）
 * @param {string} accountID
 * @param {string} toUserID
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SendTextMessage(accountID, toUserID, text) {
    return $Call.ByID(1221764459, accountID, toUserID, text);
}

/**
 * StartAccountListener 启动指定账号的后台监听
 * @param {string} accountID
 * @returns {$CancellablePromise<void>}
 */
export function StartAccountListener(accountID) {
    return $Call.ByID(1549041970, accountID);
}

/**
 * StartListener 启动主账号后台实时监听（遗留兼容接口）
 * @returns {$CancellablePromise<void>}
 */
export function StartListener() {
    return $Call.ByID(457550371);
}

/**
 * StopAccountListener 停止指定账号的后台监听
 * @param {string} accountID
 * @returns {$CancellablePromise<boolean>}
 */
export function StopAccountListener(accountID) {
    return $Call.ByID(3020317984, accountID);
}

/**
 * StopListener 停止主账号后台监听（遗留兼容接口）
 * @returns {$CancellablePromise<boolean>}
 */
export function StopListener() {
    return $Call.ByID(3501850925);
}

/**
 * UpdateAccount 更新账号基本信息（备注名、目标用户 ID、BaseURL）
 * @param {string} id
 * @param {string} remarkName
 * @param {string} targetUserID
 * @param {string} baseURL
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAccount(id, remarkName, targetUserID, baseURL) {
    return $Call.ByID(1417513767, id, remarkName, targetUserID, baseURL);
}
