// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WechatService 暴露给 Wails 前端的服务（支持多微信账号并发管理与收发路由）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckQRStatus 轮询检测二维码状态（支持传入自定义备注名创建独立账号）
 * @param {string} qrcode
 * @param {string} remarkName
 * @returns {$CancellablePromise<$models.QRStatus | null>}
 */
export function CheckQRStatus(qrcode, remarkName) {
    return $Call.ByID(2815777374, qrcode, remarkName);
}

/**
 * DeleteAccount 删除指定微信账号并停止其长轮询
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAccount(id) {
    return $Call.ByID(698820737, id);
}

/**
 * Destroy 销毁模块并彻底停止所有后台监听 Goroutine
 * @returns {$CancellablePromise<void>}
 */
export function Destroy() {
    return $Call.ByID(606446929);
}

/**
 * GetLoginQRCode 获取微信登录二维码
 * @returns {$CancellablePromise<$models.QRInfo | null>}
 */
export function GetLoginQRCode() {
    return $Call.ByID(231563010);
}

/**
 * GetPendingMessages 取走指定账号后台积累的未读消息（消费后清空，供前端页面重新挂载时补取）
 * @param {string} accountID
 * @returns {$CancellablePromise<$models.InboundMessage[] | null>}
 */
export function GetPendingMessages(accountID) {
    return $Call.ByID(2401800150, accountID);
}

/**
 * GetState 获取全局/主账号运行时状态（兼容旧前端接口）
 * @returns {$CancellablePromise<$models.WechatState>}
 */
export function GetState() {
    return $Call.ByID(3717410300);
}

/**
 * InitOnDemand 按需懒初始化：用户进入页面或首次调用时拉起所有已配置账号的后台监听
 * @returns {$CancellablePromise<void>}
 */
export function InitOnDemand() {
    return $Call.ByID(4049363425);
}

/**
 * ListAccounts 获取所有账号及其运行时状态
 * @returns {$CancellablePromise<$models.WechatAccountState[] | null>}
 */
export function ListAccounts() {
    return $Call.ByID(1388396637);
}

/**
 * OpenInboundFile 下载微信入站文件到临时目录，并用系统默认程序打开。
 * @param {string} attachmentID
 * @returns {$CancellablePromise<$models.AttachmentActionResult>}
 */
export function OpenInboundFile(attachmentID) {
    return $Call.ByID(3639868368, attachmentID);
}

/**
 * PickFileDialog 打开系统原生文件选择对话框选择任意文件并返回真实绝对路径
 * @returns {$CancellablePromise<string>}
 */
export function PickFileDialog() {
    return $Call.ByID(3588239546);
}

/**
 * PickImageDialog 打开系统原生文件选择对话框选择图片并返回真实绝对路径
 * @returns {$CancellablePromise<string>}
 */
export function PickImageDialog() {
    return $Call.ByID(2397880461);
}

/**
 * RefreshAccountContextToken 手动拉取指定账号的 updates
 * @param {string} accountID
 * @returns {$CancellablePromise<string>}
 */
export function RefreshAccountContextToken(accountID) {
    return $Call.ByID(2850430859, accountID);
}

/**
 * RefreshContextToken 刷新主账号 Context Token（遗留兼容接口）
 * @returns {$CancellablePromise<string>}
 */
export function RefreshContextToken() {
    return $Call.ByID(1555551512);
}

/**
 * SaveInboundFile 弹出另存为对话框并保存微信入站文件。
 * @param {string} attachmentID
 * @returns {$CancellablePromise<$models.AttachmentActionResult>}
 */
export function SaveInboundFile(attachmentID) {
    return $Call.ByID(3285446271, attachmentID);
}

/**
 * SendFileMessage 发送文件消息（指定账号与目标）
 * @param {string} accountID
 * @param {string} toUserID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function SendFileMessage(accountID, toUserID, filePath) {
    return $Call.ByID(1037104628, accountID, toUserID, filePath);
}

/**
 * SendImageMessage 发送图片消息（指定账号与目标）
 * @param {string} accountID
 * @param {string} toUserID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function SendImageMessage(accountID, toUserID, filePath) {
    return $Call.ByID(1735217207, accountID, toUserID, filePath);
}

/**
 * SendTextMessage 发送文字消息（指定账号与目标）
 * @param {string} accountID
 * @param {string} toUserID
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SendTextMessage(accountID, toUserID, text) {
    return $Call.ByID(1221764459, accountID, toUserID, text);
}

/**
 * StartAccountListener 启动指定账号的后台监听
 * @param {string} accountID
 * @returns {$CancellablePromise<void>}
 */
export function StartAccountListener(accountID) {
    return $Call.ByID(1549041970, accountID);
}

/**
 * StartListener 启动主账号后台实时监听（遗留兼容接口）
 * @returns {$CancellablePromise<void>}
 */
export function StartListener() {
    return $Call.ByID(457550371);
}

/**
 * StopAccountListener 停止指定账号的后台监听
 * @param {string} accountID
 * @returns {$CancellablePromise<boolean>}
 */
export function StopAccountListener(accountID) {
    return $Call.ByID(3020317984, accountID);
}

/**
 * StopListener 停止主账号后台监听（遗留兼容接口）
 * @returns {$CancellablePromise<boolean>}
 */
export function StopListener() {
    return $Call.ByID(3501850925);
}

/**
 * UpdateAccount 更新账号基本信息（备注名、目标用户 ID、BaseURL）
 * @param {string} id
 * @param {string} remarkName
 * @param {string} targetUserID
 * @param {string} baseURL
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAccount(id, remarkName, targetUserID, baseURL) {
    return $Call.ByID(1417513767, id, remarkName, targetUserID, baseURL);
}
