// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotificationService 暴露给 Wails 前端的通知中心管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearHistory 清空历史通知
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory() {
    return $Call.ByID(1146936764);
}

/**
 * GetHistory 获取历史通知
 * @returns {$CancellablePromise<($models.Notification | null)[] | null>}
 */
export function GetHistory() {
    return $Call.ByID(1672241495);
}

/**
 * MarkAllAsRead 全部标记为已读
 * @returns {$CancellablePromise<void>}
 */
export function MarkAllAsRead() {
    return $Call.ByID(2193392253);
}

/**
 * MarkAsRead 标记某条通知为已读
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function MarkAsRead(id) {
    return $Call.ByID(2853896250, id);
}
