// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hostfeed$0 from "../../../../packages/go/hostfeed/models.js";

/**
 * DBXRelease 远程 GitHub Release 中可用的 DBX Windows x64 便携版。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的唯一依据）；
 * digest 缺失即不入列表（上游 .sig 属 minisign 通道，本托管不消费，没有
 * 第二官方摘要源）。
 * @typedef {Object} DBXRelease
 * @property {string} version - 如 v1.5.3
 * @property {string} published - 发布时间（RFC3339）
 * @property {string} assetName - 如 DBX_1.5.3_x64-portable.zip
 * @property {string} assetUrl - 资产下载地址（302 到 CDN）
 * @property {number} size - 资产大小（字节）
 * @property {string} sha256 - 官方 sha256（digest 去掉前缀）
 * @property {hostfeed$0.AssetNote[] | null} [assets] - Assets 上游全发布物平台/形态矩阵（N13 展示层，纯展示，下载路径不消费）。
 * @property {hostfeed$0.Form} [form] - Form 本托管资产形态（N13 形态标注，纯展示，ListRemote 回填）：恒 portable——DBX_x-y-z_x64-portable.zip 解压即用（上游另有 setup.exe / msi / offline 安装形态资产与 minisign .sig 附属，托管不收）。
 */

/**
 * DBXVersionInfo 本地已安装的 DBX 版本信息。
 * SHA256 为账本内 exe 落位摘要（Download/ImportLocal 成功时实测记入）；
 * VerifiedHash 徽章语义对齐托管族（verifiedHash）：远程下载链经官方摘要
 * 校验为 true，本地导入无官方参照为 false。HashDrifted 为账外漂移护栏：
 * ListInstalled 刷新时对"落位后 mtime 变新"的 exe 复算摘要，与账本不符
 * 即如实标记——只报告不处置，不撒谎（成本控制见 driftCheck 注释）。
 * DBX 是上游自带更新器的 Tauri 应用：漂移徽章正是为"应用自更新原地换
 * exe"这一必然发生的场景而设。
 * @typedef {Object} DBXVersionInfo
 * @property {string} version - 如 v1.5.3
 * @property {string} exePath - DBX.exe 完整路径（供启动使用）
 * @property {string} dir - 版本隔离目录（exe 与便携标记/许可文本同目录）
 * @property {number} size - 版本目录整树字节和（度量失败回退 exe 大小）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录（仅导入安装时有值）
 * @property {string} sha256 - 账本内 exe 落位摘要（可为空=账本无摘要）
 * @property {boolean} verifiedHash - 安装时是否经官方摘要校验
 * @property {boolean} hashDrifted - 落位后 exe 是否发生账外漂移
 * @property {string} driftNote - 漂移复查明细（如实转述，含无法比对场景）
 */

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - resolve/downloading/verify/extract/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
