// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * BCURelease 远程 GitHub Release 中可用的 BCU Windows 便携版。
 * @typedef {$models.BCURelease} BCURelease
 */

/**
 * BCUVersionInfo 本地已安装的 BCU 版本信息。
 * @typedef {$models.BCUVersionInfo} BCUVersionInfo
 */

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */
