// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * RecordlyRelease 远程 GitHub Release 中可用的 Recordly Windows x64 安装器。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验第一依据），
 * 安装前还会尽力拉取官方 SHA256SUMS.txt 做交叉比对（第三只眼）。
 * @typedef {$models.RecordlyRelease} RecordlyRelease
 */

/**
 * RecordlyVersionInfo 本地已安装的 Recordly 版本信息。
 * @typedef {$models.RecordlyVersionInfo} RecordlyVersionInfo
 */
