// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - resolve/downloading/verify/install/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * RecordlyRelease 远程 GitHub Release 中可用的 Recordly Windows x64 安装器。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验第一依据），
 * 安装前还会尽力拉取官方 SHA256SUMS.txt 做交叉比对（第三只眼）。
 * @typedef {Object} RecordlyRelease
 * @property {string} version - 如 v1.3.3 / v1.3.5-beta.2
 * @property {string} published - 发布时间（RFC3339）
 * @property {boolean} isPre - 是否为预发布版本（beta 通道条目）
 * @property {string} assetName - 如 Recordly-windows-x64.exe
 * @property {string} assetUrl - 资产下载地址（302 到 CDN）
 * @property {number} size - 资产大小（字节）
 * @property {string} sha256 - 官方 sha256（digest 去掉前缀）
 */

/**
 * RecordlyVersionInfo 本地已安装的 Recordly 版本信息。
 * @typedef {Object} RecordlyVersionInfo
 * @property {string} version - 如 v1.3.3
 * @property {string} exePath - Recordly.exe 完整路径（供启动/唤窗使用）
 * @property {string} dir - 版本隔离目录（NSIS 静默安装的落点）
 * @property {number} size - Recordly.exe 大小（字节）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录（仅导入安装时有值）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
