// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SysInfoService 面向前端的系统档案服务：单次 RPC 返回全量快照。
 * 全部采集为注册表/WinAPI 只读调用（毫秒级），无缓存、无常驻资源、
 * 不产生 journal 事务——与托管家族的写事务通道正交，仅经统一调用门
 * （停用/阻止态拒调用）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetReport 采集一次本机软硬件档案。段级失败如实记入 Errors（前端告警条
 * 呈现），成功段照常送达——绝不为"表观全绿"隐藏采集边界。
 * @returns {$CancellablePromise<$models.Report>}
 */
export function GetReport() {
    return $Call.ByID(400127653);
}

/**
 * PurgeStandby 执行一次可回收待机列表清理。首版先支持已提权宿主的直接路径；
 * 普通权限的 shared helper 接线在下一原子提交完成。MCP 不引用此方法。
 * @returns {$CancellablePromise<$models.PurgeResult>}
 */
export function PurgeStandby() {
    return $Call.ByID(1100157317);
}
