// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SysInfoService 面向前端的系统信息页服务：静态档案快照（GetReport，只读）
 * 与两个谨慎的内存回收动作（PurgeStandby / EmptyWorkingSets）。档案采集全部为
 * 注册表/WinAPI 只读调用（毫秒级），无缓存、无常驻资源、不产生 journal 事务——
 * 与托管家族的写事务通道正交，仅经统一调用门（停用/阻止态拒调用）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EmptyWorkingSets 执行一次"清空全部进程工作集"（RAMMap Empty Working Sets
 * 同款谨慎语义）：把各进程正在占用的页强行压回待机列表，短暂普遍变卡属预期，
 * Windows 随后自动管理回补。与 PurgeStandby 共享 purgeMu 单飞，同一时刻至多
 * 一种清理在飞。MCP 不引用此方法。
 * @returns {$CancellablePromise<$models.PurgeResult>}
 */
export function EmptyWorkingSets() {
    return $Call.ByID(964164732);
}

/**
 * GetReport 采集一次本机软硬件档案。段级失败如实记入 Errors（前端告警条
 * 呈现），成功段照常送达——绝不为"表观全绿"隐藏采集边界。
 * @returns {$CancellablePromise<$models.Report>}
 */
export function GetReport() {
    return $Call.ByID(400127653);
}

/**
 * PurgeStandby 执行一次可回收待机列表清理（只动 Windows 的 standby 页列表，
 * 不关程序、不删文件；压缩存储与进程工作集不在本动作射程）。已提权宿主走直接
 * 路径，普通权限经一次性 UAC helper；两路径都带回前后账目。MCP 不引用此方法。
 * @returns {$CancellablePromise<$models.PurgeResult>}
 */
export function PurgeStandby() {
    return $Call.ByID(1100157317);
}
