// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as fileshare$0 from "../../../../../hubkit/internal/modules/fileshare/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as instance$0 from "../../../../../hubkit/internal/modules/frpc/instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as version$0 from "../../../../../hubkit/internal/modules/frpc/version/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as lan$0 from "../../../../../hubkit/internal/modules/lan/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as instance$1 from "../../../../../hubkit/internal/modules/markeron/instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as version$1 from "../../../../../hubkit/internal/modules/markeron/version/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as portscan$0 from "../../../../../hubkit/internal/modules/portscan/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as wechat$0 from "../../../../../hubkit/internal/modules/wechat/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as notify$0 from "../../../../../hubkit/internal/notify/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "ext:changed": void;
            "fileshare:status": fileshare$0.ServerStatus;
            "fileshare:text-dropped": fileshare$0.DropItem;
            "fileshare:transfer": fileshare$0.TransferEvent;
            "frpc:instance-log": instance$0.LogEntry;
            "frpc:instance-state": instance$0.Snapshot;
            "frpc:version-download": version$0.DownloadProgress;
            "lan:progress": lan$0.LanProgress;
            "markeron:instance-state": instance$1.Snapshot;
            "markeron:version-download": version$1.DownloadProgress;
            "memo:changed": void;
            "notify:received": notify$0.Notification;
            "portscan:progress": portscan$0.ScanProgress;
            "wechat:context-token-updated": { [_ in string]?: string } | null;
            "wechat:message-received": wechat$0.InboundMessage;
        }
    }
}
