// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as MarkerOnService from "./markeronservice.js";
export {
    MarkerOnService
};

import * as $models from "./models.js";

/**
 * StopOutcome 停止执行结果。
 * @typedef {$models.StopOutcome} StopOutcome
 */

/**
 * ToggleOutcome 标注开关执行结果（"开关"语义：告知发生了什么动作，而非状态快照——
 * 标注态本身是奇偶推断，用户直接按全局快捷键会脱同步，故不对外承诺精确状态）。
 * @typedef {$models.ToggleOutcome} ToggleOutcome
 */
