// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MarkerOnService 向前端暴露 MarkerOn 版本管理与标注开关能力。
 * 所有业务 RPC 方法经 holder.Enter() 接入统一调用门（Wave 3）：
 * 未安装/停用/阻止模块的任何方法调用被拒，且调用在途期间停用会等待 drain。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDesktopShortcut 在桌面为当前使用版本创建快捷方式（同名覆盖）。
 * @returns {$CancellablePromise<void>}
 */
export function CreateDesktopShortcut() {
    return $Call.ByID(338963579);
}

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 markeron:version-download
 * 推送进度；同时开一笔 journal 托管事务（install 首装 / update 向已托管工具链
 * 追加版本，managed-declarative 资产形态）——journal 先落盘再副作用，进度阶段
 * 迁移逐步 Advance，收口经观察面 Handle 自动落账并广播 operation:changed
 * （与既有模块事件双通道并行，Wave 4-B 接线）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(459035173, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(3070296309);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 false）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(1585087693);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(3197972571);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表
 * @returns {$CancellablePromise<version$0.MarkerVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(498831606);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）
 * @returns {$CancellablePromise<version$0.MarkerRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(1336341949);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(4111945735);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(3193921181, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(643892372);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(507039601, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(148756569, b);
}

/**
 * Shutdown（RPC 导出版，纯 void）：取得调用门租约后转发内部 shutdown()，
 * 拒绝即早退——Wave 3 口径：void 方法不改签名。前端当前不调用本方法，
 * 但它属绑定面，必须经门收口。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3233554725);
}

/**
 * StopAnnotate 停止引擎托管的 MarkerOn。
 * external 状态不越权强杀（互斥体探测拿不到 PID）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.StopOutcome>}
 */
export function StopAnnotate() {
    return $Call.ByID(332723831);
}

/**
 * ToggleAnnotate 标注开关编排中枢：
 *   - external：任一已装 exe 充当单实例信使，触发外部主实例 toggle_drawing；
 *   - running：自有实例直接翻转（启动后极短时间内先补足消息窗口注册缓冲）；
 *   - stopped/failed：仅启动到后台运行（不自动进入标注）——进入/退出标注交给下一次点击或 Ctrl+Shift+D。
 * @returns {$CancellablePromise<$models.ToggleOutcome>}
 */
export function ToggleAnnotate() {
    return $Call.ByID(4074852051);
}
