// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DBXService 向前端暴露 DBX 版本管理、实例控制与账本漂移感知能力。
 * 数据库连接与 SQL 操作全部在 DBX 自有窗口内完成（纯托管决策：其界面即
 * 产品价值，且直连用户数据库，内嵌重做风险与性价比都不成立）。
 * 
 * 与 ccswitch 引擎的适配差异（上游契约侦查结论，详见 instance 包注释）：
 *   - 同 Tauri v2 家族：互斥体探测 + 信使唤窗逐字同形制（唤窗 = 再拉起一次
 *     exe 触发 single-instance handoff，自动 show+focus，无 CLI 参数）；
 *     探针分治——互斥体拒探（elevated 外部实例等）兜底进程名 DBX.exe 枚举；
 *   - WM_CLOSE 目标取自有 PID 的可见主窗（标题 "DBX"）而非 ccswitch 的
 *     隐藏消息窗实证路径（DBX 上游未验证后者的 CloseRequested 路由）；
 *   - 托管启动注入 DBX_DATA_DIR（数据改道 Hanxi 数据根，ccswitch 无此层）；
 *   - 特有坑治理：用户开"托管备份"会以 schtasks 再拉起 --managed-backup-worker
 *     进程（脱出 JobObject）——Quit 后检见同名残留如实 external 呈现并给
 *     设置内关闭指引，不强杀托管目录外的 DBX.exe；
 *   - 空闲自动退出不做：关窗驻托盘正是许多用户的挂账姿势，DBX 会话长驻
 *     与其"托管备份"后台形态冲突面大（gonavi 同族结论：不引入未要求行为）。
 * 
 * 所有业务 RPC 方法经 holder.Enter() 接入统一调用门（Wave 3）：
 * 未安装/停用/阻止模块的任何方法调用被拒，且调用在途期间停用会等待 drain。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 dbx:version-download
 * 推送进度；同时开一笔 journal 托管事务（install 首装 / update 向已托管工具链
 * 追加版本，managed-declarative 资产形态）——journal 先落盘再副作用，进度阶段
 * 迁移逐步 Advance，收口经观察面 Handle 自动落账并广播 operation:changed
 * （与既有模块事件双通道并行，Wave 4-B 接线，markeron/ccswitch 同构）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(1726055495, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(419654391);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 false）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(2583253175);
}

/**
 * GetStatus 返回引擎当前状态快照 + 使用版本账本漂移投影 + 数据改道账目
 * （先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * 漂移复查对象：设定版本优先，未设定时取快照携带的最近自有版本；
 * 无版本可查（未安装）时不复查、driftNote 留空。VerifyLedger 为 mtime 闸控
 * 只读复查，轮询成本纪律由 version 线保证。
 * @returns {$CancellablePromise<$models.DBXStatus>}
 */
export function GetStatus() {
    return $Call.ByID(2990505725);
}

/**
 * ImportLocal 导入本地已安装的 DBX（安装版/绿色版均可）。
 * 导入物仅版本隔离目录内的 exe 与伴生文件（portable.dbx 标记必须保留——
 * 缺失即拒的闸门在 version 线，错误如实透传不吞）；数据不受导入影响
 * （托管启动恒注入 DBX_DATA_DIR，改道 Hanxi 数据根）。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 文件被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.DBXVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(1787428651, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表（含账外漂移复查明细 HashDrifted/DriftNote）。
 * @returns {$CancellablePromise<version$0.DBXVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(3789290872);
}

/**
 * ListReleases 获取远程可用版本列表（GitHub API digest 官方摘要，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.DBXRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(1262808487);
}

/**
 * MetaHints 如实披露账（前端 meta 区消费，一次拉全）：数据留存策略、
 * 完整性信任根、备份 worker 治理、WebView2 依赖降级预告。所有话术单点
 * 收口在后端（QuitAdvisory 同纪律），前端不得自造第二套口径。
 * @returns {$CancellablePromise<string[] | null>}
 */
export function MetaHints() {
    return $Call.ByID(404645034);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮；受控数据目录
 * 同由前端持 GetStatus.dataDir 走本方法打开——explorer 目录语义，绝不传
 * 文件路径）。收口至 windows.RevealDir（markeron「打开安装目录」事故教训）。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(4238109028, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(552766501);
}

/**
 * OpenWindow 窗口唤起编排中枢（信使路线，ccswitch 同形制）：
 *   - external：任一已装 exe 充当单实例信使，插件回调 show+focus 外部主窗口；
 *   - running：自有实例直接信使唤窗；
 *   - stopped/failed：解析 active 版本，注入 DBX_DATA_DIR 无参启动
 *     （DBX 唯一启动语义即"开窗"）。
 * 
 * 信使与冷启动两路都携带受控数据目录：正常场 env 无人消费（信使转发即退），
 * 接管场（信使转正为新主实例）数据改道纪律不落空。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(2193096557);
}

/**
 * Quit 退出引擎托管的 DBX（优雅 WM_CLOSE + 宽限 + JobObject 强杀兜底，
 * 语义见 QuitAdvisory 预告）。
 * external 状态不越权强杀（互斥体场拿不到外部 PID，worker 残留更不归管辖）：
 * 仅返回人性化指引。自有实例退出后复检一次外部感知——"托管备份"复拉的
 * 残留进程如实 external 呈现并附指引（外部实例治理口径）。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(3958859834);
}

/**
 * QuitAdvisory 托管退出预告文案（前端"退出"按钮确认框在执行 Quit 前展示）：
 * DBX 关窗语义按用户设置驻托盘或弹询问确认框，WM_CLOSE 可能只藏窗或挂
 * 模态框——托管退出在优雅宽限后以 JobObject 强杀兜底（自有实例）。请在
 * 托管退出前保存未完成的工作。静态文案单点收口在后端，避免前端各入口
 * 话术漂移（gonavi 同法）。
 * @returns {$CancellablePromise<string>}
 */
export function QuitAdvisory() {
    return $Call.ByID(1907627485);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的自有版本拒绝卸载）。
 * 数据面纪律：卸载只删版本隔离目录（exe 与 portable.dbx 标记等五条目），
 * **绝不触碰** Hanxi 数据根下的 DBX 受控数据目录——删版本不丢数据；
 * 数据只有在用户明示时才允许清理（本模块不提供任何删数据通道）。
 * 末版可卸口径：允许卸载到"零版本"——卸载后列表为空、activeVersion 清空、
 * 下一次冷启动给出"先下载或导入"的指引，模块不因此死锁。外部实例正占用
 * 文件时由 manager 的 rename 隔离删除如实报错，不谎报成功。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(2707996387, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库官方地址 github.com/t8y2/dbx（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(1682496250);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(3702020011, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(1048326251, b);
}

/**
 * Shutdown（RPC 导出版，纯 void）：取得调用门租约后转发内部 shutdown()，
 * 拒绝即早退——Wave 3 口径：void 方法不改签名。前端当前不调用本方法，
 * 但它属绑定面，必须经门收口。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3161718975);
}
