// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DirSize 目录真实扫描结果（walk 口径，与注册表 EstimatedSize 安装器口径互补）。
 * @typedef {Object} DirSize
 * @property {number} bytes
 * @property {number} files
 * @property {number} dirs
 * @property {number} skipped - 无权限/探测失败的条目数（>0 时结果偏小，如实标注）
 * @property {string} scannedAt
 */

/**
 * DirSlot 一个目录槽位（安装目录 / 两代数据目录的候选点）。
 * ID 由 kind+路径派生（跨次探测稳定，扫描缓存按 ID 挂接）；路径一律后端解析，
 * 前端只回传 ID——与 envcheck RevealToolPath 的"不接受任意路径"红线一致。
 * @typedef {Object} DirSlot
 * @property {string} id
 * @property {string} kind - install | data40 | data30
 * @property {string} label
 * @property {string} path
 * @property {string} origin - registry | hkcu | default | documents | driveRoot | config
 * @property {boolean} exists
 * @property {boolean} active - 数据目录判定在用（含 all_users / wxid_* 账号子目录）
 * @property {DirSize | null} [size]
 * @property {string[] | null} [notes]
 */

/**
 * InstallerFile 一次成功下载的官方安装包落位记录（N38：只搬包到下载目录，
 * 不托管安装/启动——装不装、何时装全由用户双击决定）。
 * Note 恒为如实的校验声明：微信官方直链从不旁挂摘要值，工具只能核字节数与
 * 可执行文件头，绝不冒充"校验通过"。
 * @typedef {Object} InstallerFile
 * @property {string} path
 * @property {string} fileName
 * @property {string} version - 下载时官方直链对应的版本号
 * @property {number} bytes
 * @property {string} downloadedAt
 * @property {string} note
 */

/**
 * InstallerProgress softver:installer-download 事件载荷（安装包下载进度流）。
 * State：downloading | done | canceled | error；done/canceled/error 为终态。
 * done 携带 File（供前端直接写回快照，与 dir-scan 同构）。
 * @typedef {Object} InstallerProgress
 * @property {string} state
 * @property {string} fileName
 * @property {number} done
 * @property {number} total
 * @property {string} [message]
 * @property {InstallerFile | null} [file]
 */

/**
 * LocalInstall 本机一套微信安装（注册表命中一条即一套；3.x 与 4.x 可共存）。
 * @typedef {Object} LocalInstall
 * @property {string} id - 稳定键：weixin|wechat（按注册表子键名）
 * @property {string} generation - 4.x (Weixin) / 3.x (WeChat) / 未知
 * @property {string} displayName - 注册表 DisplayName 原值（如"微信"）
 * @property {string} publisher - 注册表 Publisher
 * @property {string} registryKey - 命中的 Uninstall 子键全路径
 * @property {string} displayVersion - 注册表 DisplayVersion（可空）
 * @property {string} installDir - InstallLocation（回落探测结果，可空）
 * @property {string} installDirOrigin - registry | hkcu | default（安装目录证据来源）
 * @property {boolean} installDirExists
 * @property {number} estimatedSizeKb - 注册表 EstimatedSize（KB，0=无）
 * @property {VersionSource[] | null} sources - 双口径读数（含标源）
 * @property {string} bestVersion - 主口径版本值
 * @property {string[] | null} [notes]
 */

/**
 * OfficialRelease 官方通道读数（更新页解析结果）。
 * DownloadURL 为空表示页面改版只解析出版本号（直链失配），前端仍引导打开官方页。
 * @typedef {Object} OfficialRelease
 * @property {string} version
 * @property {string} downloadUrl
 * @property {string} pageUrl
 * @property {string} fetchedAt
 * @property {string} [parseNote]
 */

/**
 * ScanProgress softver:dir-scan 事件载荷（目录大小扫描进度流）。
 * State：queued | running | done | canceled | error；done/canceled/error 为终态。
 * @typedef {Object} ScanProgress
 * @property {string} id
 * @property {string} state
 * @property {number} bytes
 * @property {number} files
 * @property {number} dirs
 * @property {number} skipped
 * @property {string} current
 * @property {string} [message]
 * @property {string} [scannedAt]
 */

/**
 * Snapshot 页面全量数据：本机探测（注册表+PE+目录槽位）× 官方缓存 × 对比结论。
 * 官方部分只读缓存（网络取数走 RefreshOfficial，页面进入不隐式发起外呼）。
 * @typedef {Object} Snapshot
 * @property {string} probedAt
 * @property {LocalInstall[] | null} installs
 * @property {DirSlot[] | null} dirs
 * @property {OfficialRelease | null} [official]
 * @property {string} [officialError] - 上次官方取数失败原因（降级提示用）
 * @property {UpdateHint | null} [update]
 * @property {string[] | null} scanning - 进行中的扫描槽位 ID
 * @property {boolean} downloading
 * @property {InstallerFile | null} [downloaded] - 最近一次成功下载的安装包
 * @property {string[] | null} [notes]
 */

/**
 * UpdateHint 本机 vs 官方对比结论。Status：latest | available | noLocal | noOfficial。
 * @typedef {Object} UpdateHint
 * @property {string} status
 * @property {string} localVersion
 * @property {string} officialVersion
 * @property {string} message
 */

/**
 * VersionSource 本机版本的一个读数（标源）。
 * Kind 取 registry|pe；Primary 标记本安装的主口径（参与官方对比的那个值）。
 * @typedef {Object} VersionSource
 * @property {string} kind - registry | pe
 * @property {string} label - 人类可读标源：注册表 Uninstall / PE 文件版本信息
 * @property {string} field - DisplayVersion / FileVersion / ProductVersion
 * @property {string} value - 版本读数（空 = 该口径未取到，不出现在列表里）
 * @property {string} detail - 证据位置：注册表键全路径或 exe/dll 全路径
 * @property {boolean} primary - 是否为主口径读数
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
