// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecordlyService 向前端暴露 Recordly 版本管理与窗口唤起能力。
 * 录屏/剪辑操作不内嵌：打开 Recordly 自有窗口完成（其界面完整，内嵌重做
 * 性价比低，且录屏依赖其原生 helper 进程树——决策记录见 module.go 包注释）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDesktopShortcut 在桌面为托管安装创建快捷方式（同名覆盖）。
 * 上游安装器自动建的快捷方式会被装后清理（防绕过托管），此按钮是显式替代。
 * @returns {$CancellablePromise<void>}
 */
export function CreateDesktopShortcut() {
    return $Call.ByID(1617846733);
}

/**
 * DownloadVersion 后台下载并静默安装指定版本：立即返回，
 * 全程经事件 recordly:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(1379743095, targetVersion);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 true）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(3152948903);
}

/**
 * GetReleaseChannel 返回当前更新通道（stable/beta）。
 * @returns {$CancellablePromise<string>}
 */
export function GetReleaseChannel() {
    return $Call.ByID(755344067);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(2287063661);
}

/**
 * ImportLocal 导入本地已安装的 Recordly（整套 Electron 目录搬迁进托管目录）。
 * 配置恒在 %APPDATA%\Recordly 不受导入影响；托管目录已有版本时需先卸载。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 文件被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.RecordlyVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(1890806075, srcDir);
}

/**
 * ListInstalledVersions 获取本地托管安装信息（至多一条，见 Manager 单目录说明）。
 * @returns {$CancellablePromise<version$0.RecordlyVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(771003560);
}

/**
 * ListReleases 获取当前通道可用版本（多镜像回退，10 分钟缓存；
 * 数据源为 GitHub releases——上游存在"空壳 tag"发布事故，tags 不可作准）。
 * @returns {$CancellablePromise<version$0.RecordlyRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(4257726359);
}

/**
 * OpenConfigDir 打开 Recordly 的用户数据目录（配置与录像库所在）——纯托管下用户想看"数据在哪"的直达入口。只读导航，不改写。
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfigDir() {
    return $Call.ByID(3655641958);
}

/**
 * OpenDir 在资源管理器中打开托管安装目录（"打开位置"按钮）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义在文件对象上是"执行"
 * 而非"打开"（markeron「打开安装目录」按钮的事故教训：传 exe 路径直接启动了程序）。
 * 这里入参恒为目录，语义安全，但仍走本模块自有实现保持行为显式。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(1291131476, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(143497301);
}

/**
 * OpenWindow 窗口唤起编排中枢：
 *   - external：任一已装 exe 充当单实例信使，Electron second-instance 回调唤起外部主窗口；
 *   - running：自有实例直接信使唤窗；
 *   - stopped/failed：解析托管安装直接无参启动（Recordly 唯一启动语义即开窗）。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(3886709661);
}

/**
 * Quit 退出引擎托管的 Recordly。
 * external 状态不越权强杀（进程名探测拿不到主进程 PID）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(1002490730);
}

/**
 * RemoveVersion 卸载托管版本（正在运行则拒绝）。%APPDATA%\Recordly 配置与录像保留。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(775226483, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(3147869674);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(1906443835, b);
}

/**
 * SetReleaseChannel 切换更新通道（beta 含上游标注"可能不稳定"的预发布）。
 * @param {string} channel
 * @returns {$CancellablePromise<string>}
 */
export function SetReleaseChannel(channel) {
    return $Call.ByID(645623607, channel);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 终止自有实例。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1283970575);
}
