// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileShareService 面向 Wails 前端与核心调度的服务层
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChooseDirectory 调起操作系统原生目录选择对话框
 * @returns {$CancellablePromise<string>}
 */
export function ChooseDirectory() {
    return $Call.ByID(567837804);
}

/**
 * ClearDropInbox 清空投递箱
 * @returns {$CancellablePromise<void>}
 */
export function ClearDropInbox() {
    return $Call.ByID(1963606260);
}

/**
 * DeleteDropItem 删除单条投递记录
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDropItem(id) {
    return $Call.ByID(1141479905, id);
}

/**
 * GetConfig 获取当前配置
 * @returns {$CancellablePromise<$models.ShareConfig>}
 */
export function GetConfig() {
    return $Call.ByID(1777585778);
}

/**
 * GetDropInbox 获取投递箱列表
 * @returns {$CancellablePromise<$models.DropItem[] | null>}
 */
export function GetDropInbox() {
    return $Call.ByID(1999120895);
}

/**
 * GetNetworkEndpoints 获取所有可访问的局域网接入点
 * @returns {$CancellablePromise<$models.NetworkEndpoint[] | null>}
 */
export function GetNetworkEndpoints() {
    return $Call.ByID(1757787028);
}

/**
 * GetServerStatus 获取服务当前状态
 * @returns {$CancellablePromise<$models.ServerStatus>}
 */
export function GetServerStatus() {
    return $Call.ByID(3312595201);
}

/**
 * SaveConfig 保存并应用配置
 * @param {$models.ShareConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3281269479, cfg);
}

/**
 * SetMemoHook 注册投递自动进入备忘录的钩子
 * @param {any} hook
 * @returns {$CancellablePromise<void>}
 */
export function SetMemoHook(hook) {
    return $Call.ByID(2794078205, hook);
}

/**
 * SetWailsApp 设置 Wails App 引用以便发送事件
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetWailsApp(app) {
    return $Call.ByID(665390589, app);
}

/**
 * StartServer 启动局域网快传服务
 * @returns {$CancellablePromise<$models.ServerStatus>}
 */
export function StartServer() {
    return $Call.ByID(833654743);
}

/**
 * StopServer 停止快传服务
 * @returns {$CancellablePromise<void>}
 */
export function StopServer() {
    return $Call.ByID(1942173019);
}
