// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DropItem 局域网访客投递的文本/链接
 * @typedef {Object} DropItem
 * @property {string} id
 * @property {string} content - 文本内容或 URL
 * @property {string} senderIp - 来源客户端 IP
 * @property {string} userAgent - 客户端 UA
 * @property {string} createdAt
 * @property {boolean} isUrl
 */

/**
 * NetworkEndpoint 局域网接入点信息
 * @typedef {Object} NetworkEndpoint
 * @property {string} interfaceName - 网卡名称 (如 "Wi-Fi", "以太网")
 * @property {string} ip - IPv4 地址
 * @property {string} url - 完整访问 URL
 * @property {boolean} isDefault - 是否具有网关 (默认出站网卡)
 */

/**
 * ServerStatus 服务运行时状态
 * @typedef {Object} ServerStatus
 * @property {boolean} isRunning
 * @property {number} port
 * @property {string} sharePath
 * @property {boolean} allowUpload
 * @property {boolean} allowTextDrop
 * @property {boolean} autoSaveToMemo
 * @property {string[] | null} activeUrls - 如 http://192.168.1.100:8080
 * @property {number} activeConnections - 活跃传输连接数
 * @property {number} uploadCount - 累计上传文件数
 * @property {number} downloadCount - 累计下载次数
 * @property {number} uploadBytes - 累计上传字节数
 * @property {number} downloadBytes - 累计下载字节数
 * @property {number} uploadRate - 当前上传速率 (B/s)
 * @property {number} downloadRate - 当前下载速率 (B/s)
 * @property {string} startedAt - 启动时间
 */

/**
 * ShareConfig 局域网共享服务配置
 * @typedef {Object} ShareConfig
 * @property {number} port - 监听端口 (默认 80，0 为系统自动随机分配)
 * @property {string} sharePath - 挂载共享的本地物理绝对路径
 * @property {boolean} allowUpload - 是否允许访客上传文件
 * @property {boolean} allowTextDrop - 是否允许文本/链接投递
 * @property {boolean} autoSaveToMemo - 投递的文本是否自动存入 DevMemo 备忘录
 * @property {number} maxUploadSizeMB - 单文件最大上传限制 (MB，0 为不限制)
 * @property {string} authToken - 可选访问口令 (为空表示免密局域网共享)
 */

/**
 * TransferEvent 文件传输审计事件 (用于界面日志流)
 * @typedef {Object} TransferEvent
 * @property {string} type - "upload" | "download" | "drop"
 * @property {string} filename
 * @property {number} size
 * @property {string} clientIp
 * @property {string} timestamp
 * @property {boolean} success
 * @property {string} [errorMsg]
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
