// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as PaperTodoService from "./papertodoservice.js";
export {
    PaperTodoService
};

import * as $models from "./models.js";

/**
 * ControlOutcome 打开窗口/收拢纸片操作的执行结果说明。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */

/**
 * RuntimeStatus 系统 .NET 桌面运行时探测结果（no-runtime 变体的可用性提示依据，
 * 直读 Program Files\dotnet\shared 目录，不依赖 dotnet CLI）。
 * @typedef {$models.RuntimeStatus} RuntimeStatus
 */
