// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PaperTodoService 向前端暴露 PaperTodo 版本管理、运行库变体与窗口控制能力。
 * 便签编辑本身不内嵌：全程在 PaperTodo 自有纸片窗口操作（数据在其托管目录，
 * Hanxi 只负责官方原版 exe 的下载托管与启停唤窗）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDesktopShortcut 在桌面为托管安装创建快捷方式（同名覆盖）。
 * @returns {$CancellablePromise<void>}
 */
export function CreateDesktopShortcut() {
    return $Call.ByID(273958213);
}

/**
 * DownloadVersion 后台下载指定版本与变体：立即返回，全程经事件
 * papertodo:version-download 推送进度。variant 传空回退 store 偏好。
 * 运行中的实例拒绝覆盖：Windows 独占运行中的 exe，改名必失败，提前给出友好指引。
 * @param {string} targetVersion
 * @param {string} variant
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion, variant) {
    return $Call.ByID(976394879, targetVersion, variant);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 true）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(3979412799);
}

/**
 * GetInstalledVersion 返回当前托管安装信息；未安装时 Version 为空串（不报错，
 * 前端以空版本号判"未安装"渲染引导卡）。
 * @returns {$CancellablePromise<version$0.PaperVersionInfo>}
 */
export function GetInstalledVersion() {
    return $Call.ByID(1865004301);
}

/**
 * GetRuntimeStatus 探测系统 .NET 桌面运行时（no-runtime 变体的可用性判断）。
 * @returns {$CancellablePromise<$models.RuntimeStatus>}
 */
export function GetRuntimeStatus() {
    return $Call.ByID(620895615);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(21446661);
}

/**
 * GetVariant 返回下载变体偏好（self-contained / no-runtime）。
 * @returns {$CancellablePromise<string>}
 */
export function GetVariant() {
    return $Call.ByID(3778987876);
}

/**
 * HidePapers 收拢全部纸片（hide 命令信使；主实例不在场时拒绝）。
 * 双变体差异仅影响启动依赖，与唤窗/收拢通道无关。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function HidePapers() {
    return $Call.ByID(2910682442);
}

/**
 * ImportLocal 导入本地已有的 PaperTodo 目录（连便签数据一起收编进托管目录）。
 * 运行中的实例（自有或外部）拒绝导入：Windows 下运行中的 exe 被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.PaperVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(4230482067, srcDir);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.PaperRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(1933867375);
}

/**
 * OpenDir 在资源管理器中打开托管目录（"打开位置"按钮）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义在文件对象上是"执行"
 * 而非"打开"（markeron「打开安装目录」按钮的事故教训：传 exe 路径直接启动了程序）。
 * 这里入参恒为目录，语义安全，但仍走本模块自有实现保持行为显式。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(285990780, dir);
}

/**
 * OpenReleasesPage 用默认浏览器打开上游 Releases 页（绕过托管自行下载兜底）。
 * @returns {$CancellablePromise<void>}
 */
export function OpenReleasesPage() {
    return $Call.ByID(1104688148);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(3666521533);
}

/**
 * OpenWindow 窗口唤起编排中枢（show 命令信使 → 上游 ShowAllPapers 找回全部纸片）：
 *   - external：托管 exe 充当单实例信使，主实例经命名管道收到命令；
 *   - running：自有实例直接派信使；
 *   - stopped/failed：解析托管安装直接启动（PaperTodo 启动语义即纸片上桌面）。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(1530153461);
}

/**
 * Quit 退出引擎托管的 PaperTodo（exit 命令优雅退出，宽限后强杀兜底）。
 * external 状态不越权强杀（互斥体探测拿不到 PID）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(1426971906);
}

/**
 * RemoveInstalled 卸载当前托管安装。运行中拒绝；
 * 卸载只删程序本体与元信息，**便签数据（data.json、图片库、plugins）原地保留**。
 * @returns {$CancellablePromise<void>}
 */
export function RemoveInstalled() {
    return $Call.ByID(105083221);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(1026449746);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(2733623923, b);
}

/**
 * SetVariant 设定下载变体（下次下载生效，不追溯已装版本）。
 * @param {string} variant
 * @returns {$CancellablePromise<void>}
 */
export function SetVariant(variant) {
    return $Call.ByID(4268266184, variant);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 终止自有实例。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(4160548423);
}
