// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

/**
 * ControlOutcome 打开窗口/安装操作的执行结果说明。
 * @typedef {Object} ControlOutcome
 * @property {string} action - started / opened / external-opened / confirm-required / installing
 * @property {boolean} external
 * @property {string} message - 面向用户的执行说明
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {Object} QuitOutcome
 * @property {boolean} stopped - 是否真正终止了自有实例
 * @property {boolean} external - true = 当前为外部实例，未越权终止
 * @property {string} message - 面向用户的执行说明
 */

/**
 * Status 前端一次性拉取的组合状态（两形态引擎快照 + 安装版注册表感知 + 联动开关）。
 * @typedef {Object} Status
 * @property {instance$0.Snapshot} portable - 便携版引擎（form=portable）
 * @property {instance$0.Snapshot} installer - 安装版引擎（form=installer）
 * @property {version$0.InstalledInfo} installed - 安装版本机探测（含用户自行安装的）
 * @property {boolean} followOnExit
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
