// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VSCodeService 向前端暴露 VS Code 双形态托管：便携版版本管理 + 安装版
 * 感知/静默安装升级 + 两形态独立启停唤窗。
 * 编辑器操作在 VS Code 自有窗口内完成（其界面即产品，内嵌无意义）；
 * 不设空闲自动退出（关窗即退、窗口开着 = 用户正在编辑，强退反需求）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDesktopShortcut 在桌面为当前使用便携版创建快捷方式（同名覆盖）。
 * @returns {$CancellablePromise<void>}
 */
export function CreateDesktopShortcut() {
    return $Call.ByID(2899617573);
}

/**
 * DownloadVersion 下载并安装便携版：立即返回，全程经事件 vscode:version-download 推送进度。
 * 安装版（form=installer）通道 = 下载 + Inno 静默安装/升级，复用同一进度事件。
 * confirm 是安装版确认闸回执：检测到运行中实例时首次调用返回 confirm-required，
 * 前端全局确认框放行后带 confirm=true 重入（不带参数会永远被拦成死锁）。
 * @param {string} targetVersion
 * @param {string} form
 * @param {boolean} confirm
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function DownloadVersion(targetVersion, form, confirm) {
    return $Call.ByID(3683172511, targetVersion, form, confirm);
}

/**
 * GetActiveVersion 返回便携版设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(3515247343);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 false，两形态共用）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(2432640863);
}

/**
 * GetInstalledApp 探测本机安装版 VS Code（HKCU 注册表；含用户自行安装的）。
 * @returns {$CancellablePromise<version$0.InstalledInfo>}
 */
export function GetInstalledApp() {
    return $Call.ByID(3144869158);
}

/**
 * GetStatus 返回两引擎快照 + 安装版注册表探测 + 开关（先各做一次静止态外部校正）。
 * @returns {$CancellablePromise<$models.Status>}
 */
export function GetStatus() {
    return $Call.ByID(1552675493);
}

/**
 * ImportLocal 导入本地便携版 VS Code 目录（整套迁移，data\ 除外）。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 被独占，且语义易混。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.VersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(1684786611, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装便携版列表。
 * @returns {$CancellablePromise<version$0.VersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(2230141296);
}

/**
 * ListRemoteVersions 获取指定形态（portable/installer）的远程可用版本（官方端点，10 分钟缓存）。
 * @param {string} form
 * @returns {$CancellablePromise<version$0.Release[] | null>}
 */
export function ListRemoteVersions(form) {
    return $Call.ByID(2539157778, form);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 收口至 windows.RevealDir：非空与目录存在性校验及中文报错内置，explorer.exe <dir> 直启；
 * 刻意不走 explorer.exe <file> 的"执行"语义（markeron「打开安装目录」按钮的事故教训）。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(2992078876, dir);
}

/**
 * OpenPreferredWindow 托盘快捷入口：优先便携版（托管隔离通道），
 * 无已装便携版时回落安装版；两者皆无则引导先下载。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenPreferredWindow() {
    return $Call.ByID(3110425610);
}

/**
 * OpenRepository 用默认浏览器打开上游官网。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(3569809373);
}

/**
 * OpenWindow 窗口唤起编排中枢（form = portable/installer）：
 *   - external：信使二次拉起，单实例协议转发唤/开既有实例窗口；
 *   - running：自有实例直接信使唤窗；
 *   - stopped/failed：解析当前版本无参启动。
 * @param {string} form
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow(form) {
    return $Call.ByID(1960600597, form);
}

/**
 * Quit 退出引擎托管的 VS Code（form = portable/installer）。
 * external 状态不越权强杀（安装版互斥体探测拿不到 PID；便携版可能是用户日常实例）：
 * 仅返回人性化指引。
 * @param {string} form
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit(form) {
    return $Call.ByID(1734330722, form);
}

/**
 * RemoveVersion 卸载指定便携版（正在运行的版本拒绝卸载）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(3503102107, targetVersion);
}

/**
 * RepositoryURL 上游官网地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(1201946994);
}

/**
 * SetActiveVersion 设定便携版使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(507646787, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(63347731, b);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 按开关联动终止自有实例。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2545940647);
}
