// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * TrayMenuItem 托盘右键菜单自定义条目（配置切片顺序即菜单显示顺序）。
 * @typedef {$models.TrayMenuItem} TrayMenuItem
 */
