// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayMenuItem 菜单自定义条目（托盘账 TrayMenu 与轮盘账 WheelMenu 共用同一类型，
 * 配置切片顺序即菜单/盘面显示顺序）。
 * @typedef {Object} TrayMenuItem
 * @property {string} type - "command" | "route" | "exe" | "group"
 * @property {string} ref - command: "moduleId/commandId"；route: 前端路由；其余留空
 * @property {string} path - exe: 可执行文件绝对路径；其余留空
 * @property {string} args - exe: 启动参数（空格分隔，支持一对引号包裹含空格参数）；其余留空
 * @property {string} label - 菜单显示名；留空则回退默认名（命令/页面/程序名）；group 必填
 * @property {boolean} enabled - 是否显示在托盘右键菜单
 * @property {TrayMenuItem[] | null} [children] - group: 二级条目（仅 command/route/exe，不允许再嵌套）；其余留空
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
