// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.PackageSnapshot>}
 */
export function GetPackageSnapshot() {
    return $Call.ByID(4102903253);
}

/**
 * @param {string} targetVersion
 * @param {boolean} allowDowngrade
 * @returns {$CancellablePromise<$models.OperationAccepted>}
 */
export function InstallVersion(targetVersion, allowDowngrade) {
    return $Call.ByID(3258870652, targetVersion, allowDowngrade);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Launch() {
    return $Call.ByID(818972950);
}

/**
 * @returns {$CancellablePromise<version$0.CachedPackage[] | null>}
 */
export function ListCachedPackages() {
    return $Call.ByID(4077441234);
}

/**
 * @returns {$CancellablePromise<version$0.Release[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(151699827);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepo() {
    return $Call.ByID(395658193);
}

/**
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveCachedPackage(targetVersion) {
    return $Call.ByID(1790356425, targetVersion);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function RepoURL() {
    return $Call.ByID(107777574);
}

/**
 * @returns {$CancellablePromise<$models.OperationAccepted>}
 */
export function Uninstall() {
    return $Call.ByID(3415905001);
}
