// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CheckpointService 历史版本服务（绑定面）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckpointNow 手动「立即快照」（Q5 拍板）：绕过触发判定与间隔闸，仍受无变更
 * skip 与单飞闸约束。异步执行（UI 稍后重拉列表即可）。
 * @returns {$CancellablePromise<void>}
 */
export function CheckpointNow() {
    return $Call.ByID(1082297365);
}

/**
 * DiffFile 单文件新旧对照（≤512KB 各截断；行 diff 由前端 textdiff 计算）。
 * @param {string} id
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileDiff>}
 */
export function DiffFile(id, path) {
    return $Call.ByID(640236872, id, path);
}

/**
 * FileHistory 单文件时间线（新→旧，只含该文件有变化的版本）。limit 观察窗
 * 在 maxListRevisions 内取值（≤0 或超限回 50）；备份模式事件由相邻清单差集
 * 读时算（A/M/D 真事件，非硬造）。返回恒为非 nil 切片。
 * @param {string} path
 * @param {number} limit
 * @returns {$CancellablePromise<$models.FileRevision[] | null>}
 */
export function FileHistory(path, limit) {
    return $Call.ByID(1737129545, path, limit);
}

/**
 * FlushOnExit 退出前同步补最后一发（挂 OnShutdown 链，3s 闸门卡死不拖退出）。
 * @returns {$CancellablePromise<void>}
 */
export function FlushOnExit() {
    return $Call.ByID(3212447588);
}

/**
 * GetStatus 分区状态行。
 * @returns {$CancellablePromise<$models.StatusInfo>}
 */
export function GetStatus() {
    return $Call.ByID(1290192213);
}

/**
 * ListFiles 受保文件清单（文件为轴左栏）：引擎观察窗内出现过变化的路径 ∪
 * 盘上现存白名单文件（新写未拍也有行，版本数如实为 0）。Alive 以盘上现状为准
 * （已删除文件保留历史可见，恢复链见 FileHistory+RestoreFile）；Display 对
 * memo/ 走标题 resolver，其余回落文件名（批 C 上中文名表）。
 * @returns {$CancellablePromise<$models.TrackedFile[] | null>}
 */
export function ListFiles() {
    return $Call.ByID(1316337368);
}

/**
 * ListRevisions 历史版本列表（新→旧）。
 * @returns {$CancellablePromise<$models.Revision[] | null>}
 */
export function ListRevisions() {
    return $Call.ByID(2803472825);
}

/**
 * NoteActivated 窗口重新聚焦/显示 → 清零失活标记（编辑期不打断用户）。
 * @returns {$CancellablePromise<void>}
 */
export function NoteActivated() {
    return $Call.ByID(2459446224);
}

/**
 * NoteDeactivated 主窗失焦/隐藏/最小化 → 置失活标记（等价一次"用户离开"事件）。
 * 由装配根挂 Wails 窗口事件；驻托盘后不再有失焦事件，故 Hide/Minimise 同样打点。
 * @returns {$CancellablePromise<void>}
 */
export function NoteDeactivated() {
    return $Call.ByID(2520948041);
}

/**
 * OpenHistoryDir 打开快照驻留目录（降级模式 UI 退化的唯一动作，Q3 拍板）。
 * @returns {$CancellablePromise<void>}
 */
export function OpenHistoryDir() {
    return $Call.ByID(548281190);
}

/**
 * PreviewFile 单文件内容预览（≤512KB 文本）。既有绑定面，语义 = 当前版本预览；
 * 新页一律走 PreviewRevision（可指定历史版本，两模式统一读面）。
 * @param {string} id
 * @param {string} path
 * @returns {$CancellablePromise<$models.FilePreview>}
 */
export function PreviewFile(id, path) {
    return $Call.ByID(2570073445, id, path);
}

/**
 * PreviewRevision 读取某白名单文件的正文：revision 空 = 盘上当前内容（两模式
 * 同口径直读，git index 受提交时序干扰不可作"现值"），非空 = 指定历史版本
 * （引擎读面，被删文件在其最后存在版本同样可读——热修复 A 的"看被删内容"）。
 * ≤512KB 截断照旧。
 * @param {string} path
 * @param {string} revision
 * @returns {$CancellablePromise<$models.FilePreview>}
 */
export function PreviewRevision(path, revision) {
    return $Call.ByID(1532962234, path, revision);
}

/**
 * RestoreFile 单文件回滚。memo/ 下的便签走热恢复（内存换装 + memo:changed 事件，
 * 重启无感）；config.json / state JSON 发布 pending restore 包，由下次启动在内存态
 * 构造前应用，避免运行时盘面与 Store 内存分叉。
 * @param {string} id
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RestoreFile(id, path) {
    return $Call.ByID(2283428131, id, path);
}

/**
 * RevisionDetail 某版本包含的文件清单（预览弹窗首层）。
 * @param {string} id
 * @returns {$CancellablePromise<$models.RevisionFile[] | null>}
 */
export function RevisionDetail(id) {
    return $Call.ByID(30820437, id);
}

/**
 * SetMemoRestorer 注入便签热恢复回调（仅装配根调用；nil 安全）。
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetMemoRestorer(fn) {
    return $Call.ByID(3479758725, fn);
}

/**
 * SetMemoTitleResolver 注入便签标题映射回调（仅装配根调用；nil 安全）。
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetMemoTitleResolver(fn) {
    return $Call.ByID(3675311691, fn);
}

/**
 * SetPreferences 保存可调偏好（非法值回出厂默认，与 config() 同口径）。
 * @param {$models.Preferences} p
 * @returns {$CancellablePromise<void>}
 */
export function SetPreferences(p) {
    return $Call.ByID(251133707, p);
}

/**
 * Start 探测引擎并起 5s tick（装配根在窗口建好后调用一次；重复调用 no-op）。
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1864660643);
}

/**
 * Stop 停 tick 循环（装配根 cleanup 调用；不 flush——退出补拍在 OnShutdown 链上先行）。
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(250588593);
}
