// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CheckpointService 历史版本服务（绑定面）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckpointNow 手动「立即快照」（Q5 拍板）：绕过触发判定与间隔闸，仍受无变更
 * skip 与单飞闸约束。异步执行（UI 稍后重拉列表即可）。
 * @returns {$CancellablePromise<void>}
 */
export function CheckpointNow() {
    return $Call.ByID(1082297365);
}

/**
 * FlushOnExit 退出前同步补最后一发（挂 OnShutdown 链，3s 闸门卡死不拖退出）。
 * @returns {$CancellablePromise<void>}
 */
export function FlushOnExit() {
    return $Call.ByID(3212447588);
}

/**
 * GetStatus 分区状态行。
 * @returns {$CancellablePromise<$models.StatusInfo>}
 */
export function GetStatus() {
    return $Call.ByID(1290192213);
}

/**
 * ListRevisions 历史版本列表（新→旧）。
 * @returns {$CancellablePromise<$models.Revision[] | null>}
 */
export function ListRevisions() {
    return $Call.ByID(2803472825);
}

/**
 * NoteActivated 窗口重新聚焦/显示 → 清零失活标记（编辑期不打断用户）。
 * @returns {$CancellablePromise<void>}
 */
export function NoteActivated() {
    return $Call.ByID(2459446224);
}

/**
 * NoteDeactivated 主窗失焦/隐藏/最小化 → 置失活标记（等价一次"用户离开"事件）。
 * 由装配根挂 Wails 窗口事件；驻托盘后不再有失焦事件，故 Hide/Minimise 同样打点。
 * @returns {$CancellablePromise<void>}
 */
export function NoteDeactivated() {
    return $Call.ByID(2520948041);
}

/**
 * OpenHistoryDir 打开快照驻留目录（降级模式 UI 退化的唯一动作，Q3 拍板）。
 * @returns {$CancellablePromise<void>}
 */
export function OpenHistoryDir() {
    return $Call.ByID(548281190);
}

/**
 * PreviewFile 单文件内容预览（≤512KB 文本）。
 * @param {string} id
 * @param {string} path
 * @returns {$CancellablePromise<$models.FilePreview>}
 */
export function PreviewFile(id, path) {
    return $Call.ByID(2570073445, id, path);
}

/**
 * RestoreFile 单文件回滚。memo/ 下的便签走热恢复（内存换装 + memo:changed 事件，
 * 重启无感）；config.json / state JSON 发布 pending restore 包，由下次启动在内存态
 * 构造前应用，避免运行时盘面与 Store 内存分叉。
 * @param {string} id
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RestoreFile(id, path) {
    return $Call.ByID(2283428131, id, path);
}

/**
 * RevisionDetail 某版本包含的文件清单（预览弹窗首层）。
 * @param {string} id
 * @returns {$CancellablePromise<$models.RevisionFile[] | null>}
 */
export function RevisionDetail(id) {
    return $Call.ByID(30820437, id);
}

/**
 * SetMemoRestorer 注入便签热恢复回调（仅装配根调用；nil 安全）。
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetMemoRestorer(fn) {
    return $Call.ByID(3479758725, fn);
}

/**
 * SetPreferences 保存可调偏好（非法值回出厂默认，与 config() 同口径）。
 * @param {$models.Preferences} p
 * @returns {$CancellablePromise<void>}
 */
export function SetPreferences(p) {
    return $Call.ByID(251133707, p);
}

/**
 * Start 探测引擎并起 5s tick（装配根在窗口建好后调用一次；重复调用 no-op）。
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1864660643);
}

/**
 * Stop 停 tick 循环（装配根 cleanup 调用；不 flush——退出补拍在 OnShutdown 链上先行）。
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(250588593);
}
