// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as CheckpointService from "./checkpointservice.js";
export {
    CheckpointService
};

import * as $models from "./models.js";

/**
 * FilePreview 单文件内容预览（≤512KB 文本，超出截断）。
 * @typedef {$models.FilePreview} FilePreview
 */

/**
 * Preferences 分区内可调偏好（落 settings.Store 持久化）。
 * @typedef {$models.Preferences} Preferences
 */

/**
 * Revision 历史版本列表行。ID 为 git commit hash 或影子备份时间戳目录名，
 * 对 PreviewFile/RestoreFile 不透明回传。
 * @typedef {$models.Revision} Revision
 */

/**
 * RevisionFile 某个版本包含的文件及其变化类型（git 语义首字母 M/A/D/R；备份模式恒 M）。
 * @typedef {$models.RevisionFile} RevisionFile
 */

/**
 * StatusInfo "历史版本"分区顶部状态行。
 * @typedef {$models.StatusInfo} StatusInfo
 */
