// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FilePreview 单文件内容预览（≤512KB 文本，超出截断）。
 * @typedef {Object} FilePreview
 * @property {string} path
 * @property {string} content
 * @property {number} size
 * @property {boolean} truncated
 */

/**
 * Preferences 分区内可调偏好（落 settings.Store 持久化）。
 * @typedef {Object} Preferences
 * @property {boolean} enabled
 * @property {number} idleSeconds
 * @property {number} intervalMinutes
 */

/**
 * Revision 历史版本列表行。ID 为 git commit hash 或影子备份时间戳目录名，
 * 对 PreviewFile/RestoreFile 不透明回传。
 * @typedef {Object} Revision
 * @property {string} id
 * @property {string} time - RFC3339
 * @property {string} summary - "config.json, memo/xxx.md 等 N 个文件"
 */

/**
 * RevisionFile 某个版本包含的文件及其变化类型（git 语义首字母 M/A/D/R；备份模式恒 M）。
 * @typedef {Object} RevisionFile
 * @property {string} path
 * @property {string} status
 */

/**
 * StatusInfo "历史版本"分区顶部状态行。
 * @typedef {Object} StatusInfo
 * @property {boolean} enabled
 * @property {string} mode - "git" | "backup"（引擎实际生效模式；未启动为空）
 * @property {boolean} gitAvailable - 探测结论（false 时恒为 backup）
 * @property {string} lastCommitAt - 最近一次成功提交 RFC3339；空=本进程从未提交
 * @property {number} revisionCount - 历史版本份数
 * @property {number} idleSeconds - 生效的空闲阈值
 * @property {number} intervalMinutes - 生效的最小提交间隔
 * @property {string} snapshotDir - .snapshots 目录绝对路径（展示/打开用）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
