// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载进度事件载荷（事件键 windterm:version-download）。
 * Stage 词表与全仓托管家族一致：downloading/verify/extract/done/error。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * WindTermRelease 远程可用版本（GitHub releases 元数据投影）。
 * Version 规范化为 vX.Y.Z 展示形态；AssetName/AssetURL 锁定 Windows x64 便携
 * zip（上游唯一对本托管有效的资产形态）。
 * @typedef {$models.WindTermRelease} WindTermRelease
 */

/**
 * WindTermVersionInfo 本地已安装版本记录。ExePath 指向 payload 目录内的
 * WindTerm.exe（zip 带 WindTerm_X.Y.Z 根目录包裹，托管保持原布局不解套）。
 * SHA256 为 exe 自算诊断哈希（展示用）；VerifiedHash 如实标注是否经官方摘要
 * 校验安装——上游 releases 全量无 GitHub digest（2026-09-23 API 实测 32 个
 * release），远程安装恒为 false，走 vscode 降级三层先例（见 manager.go 包注释）。
 * @typedef {$models.WindTermVersionInfo} WindTermVersionInfo
 */
