// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hostfeed$0 from "../../../../packages/go/hostfeed/models.js";

/**
 * DownloadProgress 下载进度事件载荷（事件键 windterm:version-download）。
 * Stage 词表与全仓托管家族一致：downloading/verify/extract/done/error。
 * @typedef {Object} DownloadProgress
 * @property {string} version
 * @property {string} stage
 * @property {number} done
 * @property {number} total
 * @property {string} message
 */

/**
 * WindTermRelease 远程可用版本（GitHub releases 元数据投影）。
 * Version 规范化为 vX.Y.Z 展示形态；AssetName/AssetURL 锁定 Windows x64 便携
 * zip（上游唯一对本托管有效的资产形态）。
 * @typedef {Object} WindTermRelease
 * @property {string} version
 * @property {string} published
 * @property {boolean} isPre
 * @property {string} assetName
 * @property {string} assetUrl
 * @property {number} size
 * @property {hostfeed$0.AssetNote[] | null} [assets] - Assets 上游全发布物的平台/形态展示矩阵（N13；纯展示，下载路径不消费）。
 * @property {hostfeed$0.Form} [form] - Form 本托管资产形态（N13 形态标注，纯展示，ListRemote 回填）：恒 portable——WindTerm_X_Windows_Portable_x86_64.zip，资产名自带便携证据， 机械判名与安装链事实一致（上游全平台发布物均为 zip 家族，无安装器线）。
 */

/**
 * WindTermVersionInfo 本地已安装版本记录。ExePath 指向 payload 目录内的
 * WindTerm.exe（zip 带 WindTerm_X.Y.Z 根目录包裹，托管保持原布局不解套）。
 * SHA256 为 exe 自算诊断哈希（展示用）；VerifiedHash 如实标注是否经官方摘要
 * 校验安装——上游 releases 全量无 GitHub digest（2026-09-23 API 实测 32 个
 * release），远程安装恒为 false，走 vscode 降级三层先例（见 manager.go 包注释）。
 * @typedef {Object} WindTermVersionInfo
 * @property {string} version
 * @property {string} exePath
 * @property {string} dir
 * @property {number} size
 * @property {string} sha256
 * @property {string} installedAt
 * @property {boolean} isImport
 * @property {string} source
 * @property {boolean} verifiedHash
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
