// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as GoNaviService from "./gonaviservice.js";
export {
    GoNaviService
};

import * as $models from "./models.js";

/**
 * ControlOutcome 打开窗口操作的执行结果说明。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * GoNaviStatus GetStatus 复合投影：实例快照 + 使用版本的账本漂移信号
 * （version 线 VerifyLedger 只读复查结果；mtime 闸控成本纪律见其注释）。
 * 内嵌 Snapshot 经 JSON 展平，前端消费形状 = instance-state 事件载荷 +
 * drifted/driftNote 两字段。
 * @typedef {$models.GoNaviStatus} GoNaviStatus
 */

/**
 * QuitOutcome 退出执行结果。
 * 如实口径：GoNavi 上游关窗时对未保存 SQL 草稿弹确认框，WM_CLOSE 可能被模态
 * 框挂住——托管退出在宽限后以 JobObject 强杀兜底，未经确认的未保存草稿将丢失，
 * 前端退出入口应在执行前预告（"若有未保存 SQL 草稿会弹确认，托管退出前请自行处理"）。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */
