// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InboundMessage 接收到的消息（业务实体）
 * @typedef {Object} InboundMessage
 * @property {string} from
 * @property {number} type - 1: Text, 2: Image, 3: Voice, 4: File, 5: Video
 * @property {string} [text]
 * @property {string} [mediaPath]
 * @property {string} [fileName]
 * @property {string} time
 */

/**
 * QRInfo 微信登录二维码信息
 * @typedef {Object} QRInfo
 * @property {string} qrcode
 * @property {string} qrcodeUrl
 */

/**
 * QRStatus 登录状态响应
 * @typedef {Object} QRStatus
 * @property {string} status - wait | scaned | confirmed | expired | error
 * @property {string} [botToken]
 * @property {string} [ilinkBotId]
 * @property {string} [ilinkUserId]
 * @property {string} [baseUrl]
 * @property {string} [message]
 */

/**
 * WechatState 模块当前运行时状态
 * @typedef {Object} WechatState
 * @property {boolean} isLoggedIn
 * @property {string} botToken
 * @property {string} ilinkBotId
 * @property {string} ilinkUserId
 * @property {string} contextToken
 * @property {string} contextTokenUpdatedAt
 * @property {string} targetUserId
 * @property {boolean} isListening
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
