// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WechatService 暴露给 Wails 前端的服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckQRStatus 轮询检测二维码状态
 * @param {string} qrcode
 * @returns {$CancellablePromise<$models.QRStatus | null>}
 */
export function CheckQRStatus(qrcode) {
    return $Call.ByID(3938578033, qrcode);
}

/**
 * ClearCredentials 清除已保存的登录凭据
 * @returns {$CancellablePromise<void>}
 */
export function ClearCredentials() {
    return $Call.ByID(2294354949);
}

/**
 * Destroy 销毁模块并彻底释放 Goroutine
 * @returns {$CancellablePromise<void>}
 */
export function Destroy() {
    return $Call.ByID(3088660398);
}

/**
 * GetLoginQRCode 获取微信登录二维码
 * @returns {$CancellablePromise<$models.QRInfo | null>}
 */
export function GetLoginQRCode() {
    return $Call.ByID(1768112983);
}

/**
 * GetState 获取当前模块状态
 * @returns {$CancellablePromise<$models.WechatState>}
 */
export function GetState() {
    return $Call.ByID(514691581);
}

/**
 * InitOnDemand 按需懒初始化：用户进入页面或首次调用时才根据配置拉起后台监听
 * @returns {$CancellablePromise<void>}
 */
export function InitOnDemand() {
    return $Call.ByID(3967643708);
}

/**
 * PickFileDialog 打开系统原生文件选择对话框选择任意文件并返回真实绝对路径
 * @returns {$CancellablePromise<string>}
 */
export function PickFileDialog() {
    return $Call.ByID(2513246991);
}

/**
 * PickImageDialog 打开系统原生文件选择对话框选择图片并返回真实绝对路径
 * @returns {$CancellablePromise<string>}
 */
export function PickImageDialog() {
    return $Call.ByID(3544841162);
}

/**
 * RefreshContextToken 手动拉取一次 updates，尝试获取最新的 context_token
 * @returns {$CancellablePromise<string>}
 */
export function RefreshContextToken() {
    return $Call.ByID(523220683);
}

/**
 * SaveConfig 保存用户配置 (支持手动配置目标用户 ID 或自定义 BaseURL)
 * @param {settings$0.WechatConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3881211163, cfg);
}

/**
 * SendFileMessage 发送文件消息
 * @param {string} toUserID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function SendFileMessage(toUserID, filePath) {
    return $Call.ByID(2623208563, toUserID, filePath);
}

/**
 * SendImageMessage 发送图片消息
 * @param {string} toUserID
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function SendImageMessage(toUserID, filePath) {
    return $Call.ByID(1311632950, toUserID, filePath);
}

/**
 * SendTextMessage 发送文字消息
 * @param {string} toUserID
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SendTextMessage(toUserID, text) {
    return $Call.ByID(1115412848, toUserID, text);
}

/**
 * StartListener 启动后台实时监听
 * @returns {$CancellablePromise<void>}
 */
export function StartListener() {
    return $Call.ByID(2689803320);
}

/**
 * StopListener 停止后台监听
 * @returns {$CancellablePromise<boolean>}
 */
export function StopListener() {
    return $Call.ByID(944363988);
}
