// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipboardService 剪贴板历史业务服务（Wails 绑定面）。方法集逐字冻结于契约 §4；
 * 事件名与载荷见 §5。构造签名/生命周期与 memo.MemoService 同谱：装配根在收口
 * 阶段接线（New → SetWailsApp → Module.SetHotkeyRegistry → OnInit start / OnDestroy stop），
 * 本线不碰 app.go。
 * 
 * 锁纪律（三把锁各司其职，绝不互相嵌套调用 Wails API）：
 *   - store.mu：entries 账本（store 内部自理，本层只见返回值拷贝）；
 *   - s.mu：生命周期与运行态（started/paused/监听引用/wailsApp/eventSink）；
 *   - s.ovMu：浮层与热键簿记（见 overlay.go/hotkey.go，memo sheetMu 同谱）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearAll 历史与 blobs 全清（托盘一键擦除走这里）。
 * 事件口径按契约 §5 括注由实现方标注：清空**不发**逐条 removed——数百个
 * {id} 事件对前端是风暴，正确姿势是前端收到 ClearAll 成功后全量重拉（或经
 * GetStatus 对账）；清空语义达成后逐条动画无意义。
 * @returns {$CancellablePromise<void>}
 */
export function ClearAll() {
    return $Call.ByID(2645562109);
}

/**
 * CollapseOverlay 浮层显式收窗（契约 §12 v1.4 H1：§4 十法之一）。前端
 * input.blur()/window.blur() 唤不动顶层窗 HWND 失活，选取完成/Esc 出口必须
 * 走这条显式 RPC——QuickMemoSheet HideQuickSheet 同先例。幂等：未显示时
 * 静默成功；内部走无门版 hideOverlay。
 * @returns {$CancellablePromise<void>}
 */
export function CollapseOverlay() {
    return $Call.ByID(1227820258);
}

/**
 * CreateText 手建文本片段（manual=true，不淘汰；来源记 hanxi）。走与监听入库
 * 同一去重/钳制/敏感判定通道，事件照常广播。
 * @param {string} text
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function CreateText(text) {
    return $Call.ByID(748172778, text);
}

/**
 * Delete 删单条（图片连带 blob，先删 blob 成功才动账本），广播 removed。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(170487774, id);
}

/**
 * Get 单条全文：含解密 Text 与图片 BlobData（PNG 原始字节），并记一次使用
 * （useCount++/lastUsedAt）。blob 回读失败如实上浮（元数据页仍可走 List）。
 * @param {string} id
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function Get(id) {
    return $Call.ByID(1186456603, id);
}

/**
 * GetStatus 运行态快照（监听暂停态、库容量实况、钳制上限与排除表回显）。
 * @returns {$CancellablePromise<$models.Status>}
 */
export function GetStatus() {
    return $Call.ByID(8923085);
}

/**
 * List 历史列表：q 小写子串匹配（Preview/SourceApp/Files/AutoTags 拼接串，
 * 非正则），kind 空/"all" 不过滤，limit≤500；出口不含 Text/BlobData。
 * @param {string} q
 * @param {string} kind
 * @param {number} limit
 * @returns {$CancellablePromise<$models.Entry[] | null>}
 */
export function List(q, kind, limit) {
    return $Call.ByID(1807007845, q, kind, limit);
}

/**
 * Set 回填系统剪贴板。首版仅支持 text（OpenClipboard 重试 ≤5 内含于写手）；
 * image/file 返回可读的"暂不支持"错误——如实告知，不装成功。回填不记使用
 * （使用口径只算 Get，契约 §4）。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Set(id) {
    return $Call.ByID(3030209039, id);
}

/**
 * SetPaused 暂停/恢复监听入库（历史仍可查；恢复后新复制即刻跟进）。
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetPaused(paused) {
    return $Call.ByID(2776865329, paused);
}

/**
 * SetWailsApp 设置 Wails App 引用（装配布线 Go 直调路径，不接调用门，
 * memo 同款纪律）。
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetWailsApp(app) {
    return $Call.ByID(4169509650, app);
}

/**
 * TogglePin 翻转钉选（豁免 LRU 淘汰），返回更新后的完整拷贝。
 * @param {string} id
 * @returns {$CancellablePromise<$models.Entry>}
 */
export function TogglePin(id) {
    return $Call.ByID(2520088920, id);
}
