// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry 一份剪贴板历史。JSON tag 即 wire/落盘字段名，与前端 types/clipboard.ts 逐字对齐。
 * @typedef {Object} Entry
 * @property {string} id - 16 hex 随机
 * @property {string} hash
 * @property {Kind} kind
 * @property {string} [text] - wire 上=明文；落盘=base64(DPAPI)
 * @property {string} preview - ≤120 rune 首行摘要，列表页用
 * @property {string[] | null} [files] - CF_HDROP
 * @property {string} [blob] - "blobs/<sha>.png"
 * @property {number} [width]
 * @property {number} [height]
 * @property {number} byteSize
 * @property {string} [sourceApp] - 复制时前台窗口标题
 * @property {string} [sourceExe] - 小写进程名，无路径
 * @property {string[] | null} [autoTags] - url/email/phone/color/code/cjk
 * @property {boolean} [sensitive]
 * @property {boolean} [pinned]
 * @property {boolean} [manual] - 固定片段（手建，不淘汰）
 * @property {number} createdAt - ms
 * @property {number} [lastUsedAt]
 * @property {number} [useCount]
 * @property {string | null} [blobData] - 仅 Get 回填（PNG 原始字节）
 */

/**
 * Kind 条目内容类型。
 * @readonly
 * @enum {string}
 */
export const Kind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    KindText: "text",
    KindImage: "image",
    KindFile: "file",
};

/**
 * Status 服务运行态（GetStatus 返回面，前端状态区/浮层页脚用）。
 * @typedef {Object} Status
 * @property {boolean} paused
 * @property {number} entryCount
 * @property {number} blobBytes
 * @property {number} maxEntries - 500
 * @property {number} maxBlobBytes - 100<<20
 * @property {string[] | null} excludedExes
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
