// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnState frpc 细粒度网络连接状态
 * @readonly
 * @enum {string}
 */
export const ConnState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 未连接/停止
     */
    ConnStateIdle: "idle",

    /**
     * 正在握手连接服务端
     */
    ConnStateConnecting: "connecting",

    /**
     * 握手成功，穿透正常工作
     */
    ConnStateConnected: "connected",

    /**
     * Token 或认证错误
     */
    ConnStateAuthFailed: "auth_failed",

    /**
     * 网络中断/服务端重连中
     */
    ConnStateReconnecting: "reconnecting",

    /**
     * 协议或配置严重错误
     */
    ConnStateError: "error",
};

/**
 * LogEntry 单条实例日志（事件 frpc:instance-log 载荷）。
 * @typedef {Object} LogEntry
 * @property {string} projectId
 * @property {string} line
 */

/**
 * Snapshot 实例状态快照：事件推送与前端渲染共用同一模型。
 * @typedef {Object} Snapshot
 * @property {string} projectId
 * @property {string} projectName
 * @property {string} version
 * @property {State} state
 * @property {ConnState} connState
 * @property {number} pid
 * @property {number} exitCode
 * @property {string} error
 * @property {string} startedAt
 * @property {string} stoppedAt
 */

/**
 * State 实例生命周期状态机：stopped → starting → running → (stopped | failed)
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 未启动 / 正常退出 / 手动停止
     */
    StateStopped: "stopped",

    /**
     * 进程创建中（极短窗口）
     */
    StateStarting: "starting",

    /**
     * 运行中
     */
    StateRunning: "running",

    /**
     * 启动失败 / 异常退出
     */
    StateFailed: "failed",
};

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
