// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as LiteMonitorService from "./litemonitorservice.js";
export {
    LiteMonitorService
};

import * as $models from "./models.js";

/**
 * ControlOutcome 打开窗口操作的执行结果说明。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */

/**
 * RuntimeStatus 系统 .NET 桌面运行时探测结果。
 * LiteMonitor 发布 zip 为框架依赖版（TargetFramework=net8.0-windows 且不含
 * runtime DLL）——缺 .NET 8 桌面运行时则启动即弹系统错误对话框。
 * 前端据此展示条件提示条（papertodo RuntimeStatus 同构）。
 * @typedef {$models.RuntimeStatus} RuntimeStatus
 */
