// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TranslucentTBService from "./translucenttbservice.js";
export {
    TranslucentTBService
};

import * as $models from "./models.js";

/**
 * ControlOutcome 启动/重设状态操作的执行结果说明。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */
