// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TranslucentTBService from "./translucenttbservice.js";
export {
    TranslucentTBService
};

import * as $models from "./models.js";

/**
 * ControlOutcome 启动/重设状态操作的执行结果说明。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * MsixState 打包形态"当前用户注册状态 + 本地容器缓存清单"的合并快照
 * （GetMsixState 返回值；注册状态实时查询无缓存，缓存清单来自版本线磁盘枚举）。
 * Version 归一化为发布号两段形态（2026.2.0.0 → 2026.2，实证规则见
 * normalizeMsixVersion 注释），与版本线列表行同一比较口径。
 * @typedef {$models.MsixState} MsixState
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */
