// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

/**
 * ControlOutcome 启动/重设状态操作的执行结果说明。
 * @typedef {Object} ControlOutcome
 * @property {string} action - started（冷启动）/ already-running（自有实例）/ external-detected（外部实例已在运行）/ starting（启动竞态中）/ reset-sent（自有实例信使重设）/ external-reset（外部实例信使重设）
 * @property {boolean} external
 * @property {string} message - 面向用户的执行说明
 */

/**
 * MsixState 打包形态"当前用户注册状态 + 本地容器缓存清单"的合并快照
 * （GetMsixState 返回值；注册状态实时查询无缓存，缓存清单来自版本线磁盘枚举）。
 * Version 归一化为发布号两段形态（2026.2.0.0 → 2026.2，实证规则见
 * normalizeMsixVersion 注释），与版本线列表行同一比较口径。
 * @typedef {Object} MsixState
 * @property {boolean} installed
 * @property {string} version
 * @property {string} packageFamily
 * @property {version$0.PackageCached[] | null} cache
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {Object} QuitOutcome
 * @property {boolean} stopped - 是否真正终止了自有实例
 * @property {boolean} external - true = 当前为外部实例，未越权终止
 * @property {string} message - 面向用户的执行说明
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
