// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TranslucentTBService 向前端暴露 TranslucentTB 版本管理与托管启停能力。
 * 任务栏透明样式设置不内嵌：上游 UI 就是系统托盘 XAML 飞控（无主窗口可唤），
 * Hanxi 侧提供版本管理、启停、状态重设与 settings.json 所在目录直达。
 * 本模块禁用空闲自动退出（常驻特效工具：退出 = 任务栏特效消失，与托管诉求正相反）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 translucenttb:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(3261030151, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(2995135159);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 false）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(1392268663);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(1748591805);
}

/**
 * ImportLocal 导入本地已安装的 TranslucentTB 便携版（settings.json 在 exe 同目录，
 * 整套随目录迁移，与 ccswitch 的单 exe 导入不同）。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 文件被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.TBVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(3202045675, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表。
 * @returns {$CancellablePromise<version$0.TBVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(549461048);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.TBRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(543773031);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 收口至 windows.RevealDir：非空与目录存在性校验及中文报错内置，explorer.exe <dir> 直启；
 * 刻意不走 explorer.exe <file> 的"执行"语义（markeron「打开安装目录」按钮的事故教训）。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(4064818468, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(3273053157);
}

/**
 * Quit 退出引擎托管的 TranslucentTB（WM_CLOSE 优雅：保存 settings.json 后退出）。
 * external 状态不越权强杀（互斥体探测拿不到 PID）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(573089530);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）。
 * 注意：TranslucentTB 的 settings.json 就在版本目录内，卸载连同用户配置一起删除
 * （前端卸载确认框如实预告）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(20774563, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(2795533242);
}

/**
 * ResetState 重设任务栏动态状态（等价上游托盘菜单 "Reset dynamic state"）：
 * 经单实例互斥体协议拉起状态信使，运行实例收到 TTB_NewInstanceStarted 后
 * 重放当前配置到任务栏。任务栏外观被 explorer 重启/其它工具改动弄花时的修复通道。
 *   - running/external：可发信使；
 *   - starting：前序启动未完，提示稍候；
 *   - stopped/failed：无实例可通知——拉起只会冷启动新实例，语义不是"重设"，明确报错。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function ResetState() {
    return $Call.ByID(696246681);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(2289867371, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(3827107371, b);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 终止自有实例（仅在联动开启时）。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject 联动口径约束。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3274712191);
}

/**
 * Start 冷启动编排中枢：
 *   - external：不越权拉起第二个实例（上游单实例协议会让它信使化自退并弹
 *     "已在运行"气泡，且托管归属混乱），仅如实告知；
 *   - running：幂等告知；
 *   - stopped/failed：解析 active 版本无参启动。首启会弹上游欢迎授权窗口，
 *     互斥体先于该 UI 创建，WaitReady 不受阻塞。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function Start() {
    return $Call.ByID(1250635371);
}
