// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TranslucentTBService 向前端暴露 TranslucentTB 版本管理与托管启停能力。
 * 任务栏透明样式设置不内嵌：上游 UI 就是系统托盘 XAML 飞控（无主窗口可唤），
 * Hanxi 侧提供版本管理、启停、状态重设与 settings.json 所在目录直达。
 * 本模块禁用空闲自动退出（常驻特效工具：退出 = 任务栏特效消失，与托管诉求正相反）。
 * 
 * 所有业务 RPC 方法经 holder.Enter() 接入统一调用门（Wave 3）：
 * 未安装/停用/阻止模块的任何方法调用被拒，且调用在途期间停用会等待 drain。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 translucenttb:version-download
 * 推送进度；同时开一笔 journal 托管事务（install 首装 / update 向已托管工具链
 * 追加版本，managed-declarative 资产形态）——journal 先落盘再副作用，进度阶段
 * 迁移逐步 Advance，收口经观察面 Handle 自动落账并广播 operation:changed
 * （与既有模块事件双通道并行，Wave 4-B 接线，markeron/ccswitch 同构）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(3261030151, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(2995135159);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 false）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(1392268663);
}

/**
 * GetMsixState 实时查询当前用户 TranslucentTB 打包版注册状态 + 本地容器缓存清单。
 * 注册态无服务端缓存（每次经 platform PowerShell appx 通道 Get-AppxPackage 实查，
 * 20s 超时兜底冷启动），因此便携线引擎状态缓存与此无同步义务，也不存在"安装
 * 成功后刷新缓存"的动作——下一次 GetMsixState 即最新事实。
 * @returns {$CancellablePromise<$models.MsixState>}
 */
export function GetMsixState() {
    return $Call.ByID(2263066119);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(1748591805);
}

/**
 * ImportLocal 导入本地已安装的 TranslucentTB 便携版（settings.json 在 exe 同目录，
 * 整套随目录迁移，与 ccswitch 的单 exe 导入不同）。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 文件被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.TBVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(3202045675, srcDir);
}

/**
 * InstallMsix 下载并安装指定版本的官方 bundle.msixbundle（用户级注册，免提权）。
 * 
 * 全程：HasMsixRelease 前置判定（"有 msix 资产但无官方摘要"的版本不入版本线
 * 列表，与降级钮判定同一口径，无需在本面二次甄别）→ PreparePackage（摘要必检
 * 的缓存落位，终路径只来自自家缓存目录）→ apppackage.Install → Add-AppxPackage
 * （platform 既有 PowerShell 通道，子进程非提权态：正常路径不可能出现 UAC，
 * 若系统仍回报需要提升的错误码，Detail/HResult 原样上抛不吞）→ 回查注册版本
 * 与目标一致才算成功。
 * 
 * AllowDowngrade 恒真：调用方是明确点选版本的用户（崩溃对照降级钮是本线主场景，
 * nanaZip 需二次确认的降级在这里就是功能本身），强制走 -ForceUpdateFromAnyVersion。
 * 
 * 共存语义（只陈述、不干预，与便携托管线既有行为对齐）：
 *   - 便携版与打包版共用上游单实例协议（Local 互斥体 344635E9-…，
 *     instance/probe_windows.go 与上游 main.cpp 同源实证）：后启动者信使化自退，
 *     同一时刻任务栏特效只有一个进程持有；
 *   - 托管启停线只管 Hanxi 拉起的便携进程——InstallMsix/UninstallMsix/LaunchMsix
 *     都不触碰任何在跑实例：不杀便携去装包，也不杀包去留便携；打包版经
 *     LaunchMsix/开始菜单启动后游离于 JobObject 之外，引擎按"外部实例"如实感知；
 *   - 打包版本身正在运行时卸载/升级由部署器裁决：脚本通道带
 *     -DeferRegistrationWhenPackagesAreInUse，冲突时报 APP_PACKAGE_IN_USE
 *     （可重试）归因，同样不静默强杀。
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function InstallMsix(version) {
    return $Call.ByID(3024788777, version);
}

/**
 * LaunchMsix 激活已注册的 TranslucentTB 打包版主应用（对齐 nanaZip 启动通路
 * 实证：apppackage.Activate 经 explorer.exe shell:AppsFolder\<Family>!<AppID> 派发，
 * 等价点击开始菜单磁贴；进程归系统生命周期，不入 JobObject）。未安装明确报错。
 * @returns {$CancellablePromise<void>}
 */
export function LaunchMsix() {
    return $Call.ByID(1977273267);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表。
 * @returns {$CancellablePromise<version$0.TBVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(549461048);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.TBRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(543773031);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 收口至 windows.RevealDir：非空与目录存在性校验及中文报错内置，explorer.exe <dir> 直启；
 * 刻意不走 explorer.exe <file> 的"执行"语义（markeron「打开安装目录」按钮的事故教训）。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(4064818468, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(3273053157);
}

/**
 * Quit 退出引擎托管的 TranslucentTB（WM_CLOSE 优雅：保存 settings.json 后退出）。
 * external 状态不越权强杀（互斥体探测拿不到 PID）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(573089530);
}

/**
 * RemoveMsixCache 删除指定版本的 msixbundle 容器缓存文件（不注销系统包——卸载
 * 是 UninstallMsix 的独立语义）。版本线层不判注册态，拦截在本面：目标版本当前
 * 正注册在系统（其注册版本可能仍在从缓存目录被 servicing 引用）时拒绝，须先
 * UninstallMsix。判定即 GetMsixState 的内容（复用未接门内部查询，语义同
 * "调 GetMsixState 判"，只取实查的 Installed/Version 两事实）。
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMsixCache(version) {
    return $Call.ByID(1683227046, version);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）。
 * 注意：TranslucentTB 的 settings.json 就在版本目录内，卸载连同用户配置一起删除
 * （前端卸载确认框如实预告）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(20774563, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(2795533242);
}

/**
 * ResetState 重设任务栏动态状态（等价上游托盘菜单 "Reset dynamic state"）：
 * 经单实例互斥体协议拉起状态信使，运行实例收到 TTB_NewInstanceStarted 后
 * 重放当前配置到任务栏。任务栏外观被 explorer 重启/其它工具改动弄花时的修复通道。
 *   - running/external：可发信使；
 *   - starting：前序启动未完，提示稍候；
 *   - stopped/failed：无实例可通知——拉起只会冷启动新实例，语义不是"重设"，明确报错。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function ResetState() {
    return $Call.ByID(696246681);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(2289867371, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(3827107371, b);
}

/**
 * Shutdown RPC：经调用门取 operation lease 后执行收尾（与内部版 shutdown 同语义）。
 * 停用/阻止态下被门拒属预期——OnDestroy 路径走内部版，不经本入口。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3274712191);
}

/**
 * Start 冷启动编排中枢：
 *   - external：不越权拉起第二个实例（上游单实例协议会让它信使化自退并弹
 *     "已在运行"气泡，且托管归属混乱），仅如实告知；
 *   - running：幂等告知；
 *   - stopped/failed：解析 active 版本无参启动。首启会弹上游欢迎授权窗口，
 *     互斥体先于该 UI 创建，WaitReady 不受阻塞。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function Start() {
    return $Call.ByID(1250635371);
}

/**
 * UninstallMsix 卸载当前用户的 TranslucentTB 打包版注册（Remove-AppxPackage 按
 * 实查到的包完整名称执行）。不碰任何缓存文件——容器缓存清理是 RemoveMsixCache
 * 的独立语义；便携托管线实例不受触碰（共存口径同 InstallMsix）。
 * @returns {$CancellablePromise<void>}
 */
export function UninstallMsix() {
    return $Call.ByID(250549856);
}
