// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Level 模块级别。
 * @readonly
 * @enum {string}
 */
export const Level = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * LevelBuiltin 编译进主程序的内建模块，可启停但不可卸载。
     */
    LevelBuiltin: "builtin",

    /**
     * LevelExternal 外部子进程模块（未来），可通过模块管理页独立安装/卸载。
     */
    LevelExternal: "external",
};

/**
 * ModuleInfo 模块元信息。
 */
export class ModuleInfo {
    /**
     * Creates a new ModuleInfo instance.
     * @param {Partial<ModuleInfo>} [$$source = {}] - The source object to create the ModuleInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {Level}
             */
            this["level"] = Level.$zero;
        }
        if (!("removable" in $$source)) {
            /**
             * 仅 LevelExternal 为 true
             * @member
             * @type {boolean}
             */
            this["removable"] = false;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModuleInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModuleInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModuleInfo(/** @type {Partial<ModuleInfo>} */($$parsedSource));
    }
}

/**
 * NavEntry 描述左侧导航中的一项（前端据此注册路由）。
 */
export class NavEntry {
    /**
     * Creates a new NavEntry instance.
     * @param {Partial<NavEntry>} [$$source = {}] - The source object to create the NavEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("route" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["route"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("section" in $$source)) {
            /**
             * @member
             * @type {NavSection}
             */
            this["section"] = NavSection.$zero;
        }
        if (!("order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NavEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NavEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NavEntry(/** @type {Partial<NavEntry>} */($$parsedSource));
    }
}

/**
 * NavSection 区分核心导航与扩展导航两个分区。
 * @readonly
 * @enum {string}
 */
export const NavSection = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SectionCore: "core",
    SectionExt: "ext",
};
