// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * PicRelease 远程 GitHub Release 中可用的 PicLite Windows x64 MSI 安装包。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的第一依据）。
 * 注意：上游不提供便携 zip，MSI 是唯一免管理员可拆解的资产形态
 * （-setup.exe 为 perMachine NSIS，需要提权且写卸载注册表，不可用于托管）。
 * @typedef {$models.PicRelease} PicRelease
 */

/**
 * PicVersionInfo 本地已安装的 PicLite 版本信息。
 * 有效载荷即单 exe（Tauri 静态链接，配置恒在 %APPDATA%\com.piclite.desktop，
 * 与 exe 位置无关），目录内另有托管侧写入的 meta.json。
 * @typedef {$models.PicVersionInfo} PicVersionInfo
 */
