// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - resolve/downloading/verify/extract/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * PicRelease 远程 GitHub Release 中可用的 PicLite Windows x64 MSI 安装包。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的第一依据）。
 * 注意：上游不提供便携 zip，MSI 是唯一免管理员可拆解的资产形态
 * （-setup.exe 为 perMachine NSIS，需要提权且写卸载注册表，不可用于托管）。
 * @typedef {Object} PicRelease
 * @property {string} version - 如 v1.4.1
 * @property {string} published - 发布时间（RFC3339）
 * @property {boolean} isPre - 是否为预发布版本
 * @property {string} assetName - 如 PicLite_1.4.1_x64_en-US.msi
 * @property {string} assetUrl - 资产下载地址（302 到 CDN）
 * @property {number} size - 资产大小（字节）
 * @property {string} sha256 - 官方 sha256（digest 去掉前缀）
 */

/**
 * PicVersionInfo 本地已安装的 PicLite 版本信息。
 * 有效载荷即单 exe（Tauri 静态链接，配置恒在 %APPDATA%\com.piclite.desktop，
 * 与 exe 位置无关），目录内另有托管侧写入的 meta.json。
 * @typedef {Object} PicVersionInfo
 * @property {string} version - 如 v1.4.1
 * @property {string} exePath - piclite.exe 完整路径（供启动/唤窗使用）
 * @property {string} dir - 版本隔离目录
 * @property {number} size - piclite.exe 大小（字节）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录（仅导入安装时有值）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
