// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortResult 单端口探测结果
 * @typedef {Object} PortResult
 * @property {number} port
 * @property {PortStatus} status
 * @property {string} service - 识别出的服务名称 (如 http, ssh, mysql, redis)
 * @property {string} banner - 抓取到的响应特征或标题 (如 nginx/1.24.0, OpenSSH 8.9)
 * @property {string} fingerprint - 原始指纹或证书等详情
 * @property {number} latencyMs - 响应延迟 (ms)
 */

/**
 * PortStatus 端口开放状态枚举
 * @readonly
 * @enum {string}
 */
export const PortStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PortOpen: "open",
    PortClosed: "closed",
    PortFiltered: "filtered",
};

/**
 * PresetGroup 常用预设端口分组
 * @typedef {Object} PresetGroup
 * @property {string} key
 * @property {string} name
 * @property {string} description
 * @property {string} ports
 */

/**
 * ScanProgress 实时扫描进度推送
 * @typedef {Object} ScanProgress
 * @property {string} taskId
 * @property {string} target
 * @property {number} scanned
 * @property {number} total
 * @property {number} percent
 * @property {number} foundOpen
 * @property {PortResult | null} [latestPort] - 最新发现的开放端口
 * @property {boolean} isFinished
 * @property {string} [error]
 */

/**
 * ScanRequest 端口扫描请求
 * @typedef {Object} ScanRequest
 * @property {string} target - 目标 IP 或 域名 (如 127.0.0.1, 192.168.1.1, baidu.com)
 * @property {string} portRange - 端口表达式 (如 "80,443,8080-8090")
 * @property {string} proxyUrl - 可选代理 (如 socks5://127.0.0.1:7890 或 http://127.0.0.1:7890)
 * @property {number} timeoutMs - 单端口连接超时(ms)，默认 600
 * @property {number} concurrency - 并发协程数，默认 30
 * @property {number} rateLimitMs - 单 Worker 发包微延迟(ms)，温和防封模式推荐 5~15ms
 * @property {boolean} deepDetect - 是否启用轻量指纹探测
 */

/**
 * ScanSummary 扫描任务最终汇总
 * @typedef {Object} ScanSummary
 * @property {string} taskId
 * @property {string} target
 * @property {number} totalPorts
 * @property {PortResult[] | null} openPorts
 * @property {number} durationMs
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
