// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortScanService 暴露给前端的端口扫描服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckEgressIP 探测当前扫描配置（直连或代理）下的实际发包出网 IP
 * @param {string} proxyURL
 * @returns {$CancellablePromise<string>}
 */
export function CheckEgressIP(proxyURL) {
    return $Call.ByID(4013089757, proxyURL);
}

/**
 * GetPresets 返回常见预设端口组合
 * @returns {$CancellablePromise<$models.PresetGroup[] | null>}
 */
export function GetPresets() {
    return $Call.ByID(1027849389);
}

/**
 * StartScan 启动端口扫描任务（异步），通过 Wails 事件 "portscan:progress" 实时推送进度
 * @param {$models.ScanRequest} req
 * @returns {$CancellablePromise<$models.ScanSummary | null>}
 */
export function StartScan(req) {
    return $Call.ByID(775660186, req);
}

/**
 * StopScan 中止指定任务
 * @param {string} taskID
 * @returns {$CancellablePromise<boolean>}
 */
export function StopScan(taskID) {
    return $Call.ByID(3406103572, taskID);
}
