// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MemoService 便签业务服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create 创建新便签
 * @param {string} title
 * @param {string} content
 * @param {string[] | null} tags
 * @param {string} colorTag
 * @returns {$CancellablePromise<$models.MemoItem>}
 */
export function Create(title, content, tags, colorTag) {
    return $Call.ByID(3394822961, title, content, tags, colorTag);
}

/**
 * Delete 删除指定便签
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(1060927862, id);
}

/**
 * GetStats 获取便签统计数据与标签云
 * @returns {$CancellablePromise<$models.MemoStats>}
 */
export function GetStats() {
    return $Call.ByID(3969630222);
}

/**
 * List 根据过滤条件检索便签
 * @param {$models.MemoFilter} filter
 * @returns {$CancellablePromise<$models.MemoItem[] | null>}
 */
export function List(filter) {
    return $Call.ByID(424731405, filter);
}

/**
 * QuickCreate 快捷创建 (主要供 fileshare 跨模块投递联动使用)
 * @param {string} title
 * @param {string} content
 * @param {string[] | null} tags
 * @returns {$CancellablePromise<void>}
 */
export function QuickCreate(title, content, tags) {
    return $Call.ByID(696857612, title, content, tags);
}

/**
 * SetWailsApp 设置 Wails App 引用
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetWailsApp(app) {
    return $Call.ByID(2496713290, app);
}

/**
 * ToggleMask 切换敏感信息遮罩
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleMask(id) {
    return $Call.ByID(2387226013, id);
}

/**
 * TogglePin 切换置顶状态
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function TogglePin(id) {
    return $Call.ByID(1231598576, id);
}

/**
 * Update 更新已有便签
 * @param {string} id
 * @param {string} title
 * @param {string} content
 * @param {string[] | null} tags
 * @param {string} colorTag
 * @returns {$CancellablePromise<$models.MemoItem>}
 */
export function Update(id, title, content, tags, colorTag) {
    return $Call.ByID(1163210144, id, title, content, tags, colorTag);
}
