// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MemoService 便签业务服务。
 * 存储后端二态：默认文件库（memo/<id>.md，写盘点单条化）；仅当旧库 memo.json
 * 仍在位且迁移未成功（损坏/暂存失败）时回落旧整库 Store，保证"迁移不成也不丢数据"。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearAll 一键全删：清空全部便签（含敏感遮罩条目与隔离取证副本），返回本次删除的
 * 便签条数。"不留残片"纪律：文件库模式清空 memo/ 目录下全部文件（正式 .md 与
 * .bad-/.tmp. 孤儿一并销毁）；回落模式把旧库写回空表（旧库是读写权威，销毁它反而
 * 会在下次启动复活空库文件，故原位清空）。随后清扫与便签同源的数据派生物：
 * 旧库 memo.json 本体（文件库模式下只可能是回滚/异常残留）、其 .migrated 备份与
 * .corrupt- 取证副本、半程暂存目录——迁移留底里带着全量旧便签正文，不清即漏。
 * 部分失败不假装成功：确认删除的条目先从内存移除（内存与盘不分叉），错误如实
 * 聚合上浮，前端重拉即见真实剩余；memo:changed 照常广播，多端联动同步收口。
 * @returns {$CancellablePromise<number>}
 */
export function ClearAll() {
    return $Call.ByID(802866517);
}

/**
 * Create 创建新便签
 * @param {string} title
 * @param {string} content
 * @param {string[] | null} tags
 * @param {string} colorTag
 * @returns {$CancellablePromise<$models.MemoItem>}
 */
export function Create(title, content, tags, colorTag) {
    return $Call.ByID(3394822961, title, content, tags, colorTag);
}

/**
 * Delete 删除指定便签
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(1060927862, id);
}

/**
 * GetStats 获取便签统计数据与标签云
 * @returns {$CancellablePromise<$models.MemoStats>}
 */
export function GetStats() {
    return $Call.ByID(3969630222);
}

/**
 * List 根据过滤条件检索便签
 * @param {$models.MemoFilter} filter
 * @returns {$CancellablePromise<$models.MemoItem[] | null>}
 */
export function List(filter) {
    return $Call.ByID(424731405, filter);
}

/**
 * QuickCreate 快捷创建 (主要供 fileshare 跨模块投递联动使用)。
 * 导出版接门：memo 停用时返回明确的门拒绝错误（当前签名即返回 error，
 * 直调方 fileshare 如实上浮/记录，不静默吞）。
 * @param {string} title
 * @param {string} content
 * @param {string[] | null} tags
 * @returns {$CancellablePromise<void>}
 */
export function QuickCreate(title, content, tags) {
    return $Call.ByID(696857612, title, content, tags);
}

/**
 * RestoreFile 单条热恢复（供 internal/snapshot「历史版本」恢复 memo/<id>.md 时经
 * 装配根注入的钩子调用）：校验文件内容与 ID 一致后原样字节回写，内存换装并广播
 * memo:changed——前端全量重拉即见，热生效无重启。回落旧库模式不支持（无单条概念），
 * 返回可读错误引导重启。content 用 string 承载原样字节（Go string 不校验 UTF-8，
 * 无损；同时避开绑定面对 []byte 的形态特化）。
 * memo 停用时热恢复被门拒绝并上浮明确错误（快照页单文件回滚可见），属预期语义。
 * @param {string} id
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function RestoreFile(id, content) {
    return $Call.ByID(3439614355, id, content);
}

/**
 * SetWailsApp 设置 Wails App 引用。
 * 装配布线: Go 直调路径,不得依赖运行态(见 ADR-0001 Wave 3 注记)——不接调用门。
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetWailsApp(app) {
    return $Call.ByID(2496713290, app);
}

/**
 * TitleForWhitelistPath 把快照白名单路径 memo/<id>.md 映射为便签标题（N33 §2
 * ListFiles 左栏展示用；经装配根注入 internal/snapshot 的标题 resolver 钩子，
 * 规避 snapshot→memo 包引用）。走标准调用门（RPC 门覆盖矩阵同口径）：memo
 * 停用期返 false，快照页如实回落文件名，不借标题旁路复活停用模块的数据面。
 * 非 memo 形态、未命中或空标题同样返 false。
 * @param {string} rel
 * @returns {$CancellablePromise<[string, boolean]>}
 */
export function TitleForWhitelistPath(rel) {
    return $Call.ByID(3778068714, rel);
}

/**
 * ToggleMask 切换敏感信息遮罩。隐私态必须与持久化提交绑定：写盘失败时
 * 保持原遮罩状态且不广播，避免 UI 误以为敏感信息已被安全遮住。
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleMask(id) {
    return $Call.ByID(2387226013, id);
}

/**
 * TogglePin 切换置顶状态。候选值先落盘，失败则内存与事件均不变。
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function TogglePin(id) {
    return $Call.ByID(1231598576, id);
}

/**
 * Update 更新已有便签
 * @param {string} id
 * @param {string} title
 * @param {string} content
 * @param {string[] | null} tags
 * @param {string} colorTag
 * @returns {$CancellablePromise<$models.MemoItem>}
 */
export function Update(id, title, content, tags, colorTag) {
    return $Call.ByID(1163210144, id, title, content, tags, colorTag);
}
