// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * QuickLookRelease 远程 GitHub Release 中可用的 QuickLook Windows 便携 zip。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的第一依据，
 * 与 ccswitch 同款——GitHub 自 2024 起对新资产全覆盖 digest）。
 * @typedef {$models.QuickLookRelease} QuickLookRelease
 */

/**
 * QuickLookVersionInfo 本地已安装的 QuickLook 版本信息。
 * @typedef {$models.QuickLookVersionInfo} QuickLookVersionInfo
 */
