// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * OperationAccepted 操作受理回执：同步校验通过后立即返回，真实进度经事件推送。
 * @typedef {$models.OperationAccepted} OperationAccepted
 */

/**
 * OperationLog npm 命令输出流式行事件（逐行，仿 frpc/ddnsgo instance-log）。
 * @typedef {$models.OperationLog} OperationLog
 */

/**
 * OperationProgress 操作阶段事件（仿 nanazip.OperationProgress 裁剪，无下载字节进度）。
 * @typedef {$models.OperationProgress} OperationProgress
 */

/**
 * Overview 目录整体视图。ActiveOperation 为 npm 全局树互斥锁快照，页面重挂载
 * （如操作中途切走再回）也能恢复按钮忙碌态，避免前端凭内存态误判空闲。
 * @typedef {$models.Overview} Overview
 */

/**
 * ToolBrief 目录工具的最小展示信息（随 Overview 下发，前端不再硬编码包名）。
 * @typedef {$models.ToolBrief} ToolBrief
 */

/**
 * ToolOverview 单个目录工具卡：本机探测 × registry 最新版 × 关系与安全提醒。
 * Local 恒填充（即便未安装也是 status=missing 的 ToolInfo），registry 查询失败
 * 时降级为 LatestError + RelationUnknown，前端仍需渲染本机状态与操作按钮。
 * @typedef {$models.ToolOverview} ToolOverview
 */
