// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * PiikRelease 远程 GitHub Release 中可用的 Piik Windows x64 便携版。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的唯一依据；
 * 上游 .sha256 sidecar 自 v1.2.0 起停发，不作为任何降级参照）。
 * @typedef {$models.PiikRelease} PiikRelease
 */

/**
 * PiikVersionInfo 本地已安装的 Piik 版本信息。
 * SHA256 为账本内主 exe 落位摘要（Download/ImportLocal 成功时实测记入）；
 * VerifiedHash：远程下载链经官方摘要校验为 true，本地导入无官方参照为 false。
 * HashDrifted 为账外漂移护栏：ListInstalled 刷新时对"落位后 mtime 变新"的
 * 主 exe 复算摘要，与账本不符即如实标记——只报告不处置，不撒谎（成本控制
 * 见 driftCheck 注释；piik 上游无自更新器，漂移多属手工换件/磁盘异常，
 * runtime 双 exe 不在复算面内，与家族同口径）。
 * @typedef {$models.PiikVersionInfo} PiikVersionInfo
 */
