// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hostfeed$0 from "../../../../packages/go/hostfeed/models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - resolve/downloading/verify/extract/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * PiikRelease 远程 GitHub Release 中可用的 Piik Windows x64 便携版。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的唯一依据；
 * 上游 .sha256 sidecar 自 v1.2.0 起停发，不作为任何降级参照）。
 * @typedef {Object} PiikRelease
 * @property {string} version - 如 v1.2.0（tag 原样带 v 前缀）
 * @property {string} published - 发布时间（RFC3339）
 * @property {string} assetName - 恒 piik-app-windows-amd64.zip（裸名）
 * @property {string} assetUrl - 资产下载地址（302 到 CDN）
 * @property {number} size - 资产大小（字节）
 * @property {string} sha256 - 官方 sha256（digest 去掉前缀）
 * @property {hostfeed$0.AssetNote[] | null} [assets] - Assets 上游全发布物平台/形态矩阵（N13 展示层，纯展示，下载路径不消费）。
 * @property {hostfeed$0.Form} [form] - Form 本托管资产形态（N13 形态标注，纯展示，ListRemote 回填）：恒 portable——piik-app-windows-amd64.zip 解压即跑（根平铺 + runtime 子树， 无任何安装器形态）。资产名无便携字样，机械判名 Classify 会保守降为 archive，形态以实测布局自证为准。
 */

/**
 * PiikVersionInfo 本地已安装的 Piik 版本信息。
 * SHA256 为账本内主 exe 落位摘要（Download/ImportLocal 成功时实测记入）；
 * VerifiedHash：远程下载链经官方摘要校验为 true，本地导入无官方参照为 false。
 * HashDrifted 为账外漂移护栏：ListInstalled 刷新时对"落位后 mtime 变新"的
 * 主 exe 复算摘要，与账本不符即如实标记——只报告不处置，不撒谎（成本控制
 * 见 driftCheck 注释；piik 上游无自更新器，漂移多属手工换件/磁盘异常，
 * runtime 双 exe 不在复算面内，与家族同口径）。
 * @typedef {Object} PiikVersionInfo
 * @property {string} version - 如 v1.2.0
 * @property {string} exePath - piik-app.exe 完整路径（供 instance 引擎拉起）
 * @property {string} dir - 版本隔离目录（平铺布局根，兄弟路径解析依赖整目录）
 * @property {number} size - 版本目录整树字节和（度量失败回退主 exe 大小）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录（仅导入安装时有值）
 * @property {string} sha256 - 账本内主 exe 落位摘要（空=账本无摘要）
 * @property {boolean} verifiedHash - 安装时是否经官方摘要校验
 * @property {boolean} hashDrifted - 落位后主 exe 是否发生账外漂移
 * @property {string} driftNote - 漂移复查明细（如实转述，含无法比对场景）
 * @property {string} revision - REVISION 记账（上游构建标识；漂移复算不覆盖本字段）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
