// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TermoraService from "./termoraservice.js";
export {
    TermoraService
};

import * as $models from "./models.js";

/**
 * ControlOutcome OpenWindow 编排回执（单实例信使/冷启动分支由后端裁决，UI 恒一钮）。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * QuitOutcome 退出请求结果（自有实例或按 N3 分档处置的外部实例）。
 * Action="confirm-required" 表示 confirm-force 档首入未获授权，前端弹全局
 * 确认框后携 confirm=true 重入（vscode 安装闸同款往返契约）。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */
