// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Result 单条搜索结果（ES 输出列的子集，其余列丢弃）。
 * @typedef {Object} Result
 * @property {string} name - 文件名（目录时含尾部分隔符，见解析说明）
 * @property {string} path - 所在目录完整路径
 * @property {number} size - 字节（目录/未知为 0）
 * @property {string} modified - 修改时间（ES 原样文本）
 * @property {boolean} isDir - 目录标记（ES 属性列含 D）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
