// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as MsgBoardService from "./msgboardservice.js";
export {
    MsgBoardService
};

import * as $models from "./models.js";

/**
 * BoardContent 挂牌弹窗视图模型（/#msgboard 挂载与热更新时拉取）。
 * @typedef {$models.BoardContent} BoardContent
 */

/**
 * Config 留言板偏好（模块页读写的完整快照）：Text 为挂牌正文（留空回落第一条预设）。
 * @typedef {$models.Config} Config
 */

/**
 * ScreenInfo 显示器候选（模块页下拉；设备名即 store 的 Screen 值）。
 * @typedef {$models.ScreenInfo} ScreenInfo
 */

/**
 * Status 留言板运行态（模块页状态区）。HotkeyActive 如实反映热键是否注册在位
 * （开机期抢键失败时只降级不报错，页面据此提示去托盘/轮盘唤起或改键）。
 * @typedef {$models.Status} Status
 */
