// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BoardContent 挂牌弹窗视图模型（/#msgboard 挂载与热更新时拉取）。
 * @typedef {Object} BoardContent
 * @property {string} text
 * @property {number} fontSize
 */

/**
 * Config 留言板偏好（模块页读写的完整快照）：Text 为挂牌正文（留空回落第一条预设）。
 * @typedef {Object} Config
 * @property {string} text
 * @property {number} fontSize - 正文字号（DIP px，钳位区间见 store）
 * @property {string} screen - 目标显示器设备名（如 \\.\DISPLAY2）；空=主屏
 * @property {string} hotkey - 全局热键加速器串（如 Ctrl+Alt+B）；空=停用热键
 */

/**
 * ScreenInfo 显示器候选（模块页下拉；设备名即 store 的 Screen 值）。
 * @typedef {Object} ScreenInfo
 * @property {string} device - 设备名 \\.\DISPLAYn
 * @property {number} width - 物理宽（px）
 * @property {number} height - 物理高（px）
 * @property {boolean} isPrimary - 是否主屏
 */

/**
 * Status 留言板运行态（模块页状态区）。HotkeyActive 如实反映热键是否注册在位
 * （开机期抢键失败时只降级不报错，页面据此提示去托盘/轮盘唤起或改键）。
 * @typedef {Object} Status
 * @property {boolean} shown
 * @property {string} hotkey
 * @property {boolean} hotkeyActive
 * @property {boolean} keepAwake - 挂牌期间防休眠诉求是否已成功挂账
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
