// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度（事件 papertodo:version-download 载荷）。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * PaperAsset 单个发布资产的下载要素。
 * SHA256 为 GitHub API digest（官方计算）。实证：PaperTodo 当前所有 release
 * 资产均无 digest 字段——存在时（GitHub 逐批回刷后）Download 会升级为官方哈希硬校验，
 * 缺失时降级为"字节数 + PE 版本核对 + sha256 指纹存档"链（详见 manager 注释）。
 * @typedef {$models.PaperAsset} PaperAsset
 */

/**
 * PaperRelease 远程可用的 PaperTodo Windows x64 GA 版本（双变体齐备才入列表）。
 * @typedef {$models.PaperRelease} PaperRelease
 */

/**
 * PaperVersionInfo 本地托管安装信息（固定单目录 versions/papertodo，至多一条）。
 * @typedef {$models.PaperVersionInfo} PaperVersionInfo
 */
