// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    IntegrityState
} from "./models.js";

import * as $models from "./models.js";

/**
 * DownloadProgress 下载与安装过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * MangoDiskRelease 远程 GitHub Release 中可用的 Windows x64 portable GUI。
 * @typedef {$models.MangoDiskRelease} MangoDiskRelease
 */

/**
 * MangoDiskVersionInfo 本地已安装版本信息。
 * @typedef {$models.MangoDiskVersionInfo} MangoDiskVersionInfo
 */
