// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PublicIPService 公网/局域网信息聚合服务。
 * 对上游查询源做进程内 TTL 缓存（RWMutex 读写锁）：TTL 内的重复请求直接回吐 cachedData，
 * 前端轮询不放大外部请求量；缓存含部分失败结果（某源挂掉不会立即重查）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetNetworkOverview 获取完整的出口公网 IP、局域网 IP、网关与 DNS 列表（2分钟内直接命中缓存）
 * @param {boolean} forceRefresh
 * @returns {$CancellablePromise<$models.NetworkOverview>}
 */
export function GetNetworkOverview(forceRefresh) {
    return $Call.ByID(1972093024, forceRefresh);
}

/**
 * PingTarget 对目标域名或 IP 执行探测（默认探测 4 次）
 * @param {string} target
 * @param {number} count
 * @returns {$CancellablePromise<$models.PingSummary>}
 */
export function PingTarget(target, count) {
    return $Call.ByID(3975194308, target, count);
}

/**
 * TraceRoute 执行路由追踪（基于 tracert / 本地探测，最大 30 跳）
 * @param {string} target
 * @param {number} maxHops
 * @returns {$CancellablePromise<$models.TracerouteSummary>}
 */
export function TraceRoute(target, maxHops) {
    return $Call.ByID(3389266303, target, maxHops);
}
