// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EverythingService 向前端暴露 Everything 版本管理、托管控制与内嵌搜索能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "./search/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 everything:download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(3970947133, targetVersion);
}

/**
 * EnsureSearchTool 确保 ES 搜索组件已安装（幂等；下载进度经 everything:download 事件推送）。
 * @returns {$CancellablePromise<string>}
 */
export function EnsureSearchTool() {
    return $Call.ByID(3890995923);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(3052984269);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(4248384067);
}

/**
 * ImportLocal 导入本地便携安装整套（exe+配置+语言包+索引库）。
 * 源目录实例运行中（自有/外部）时拒绝：索引库被写锁，拷贝结果不可信。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.EverythingVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(1612677949, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表
 * @returns {$CancellablePromise<version$0.EverythingVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(203060654);
}

/**
 * ListReleases 获取远程可用版本槽位（稳定版 + 1.5 测试版，stale 标记降级状态）
 * @returns {$CancellablePromise<version$0.EverythingRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(465297029);
}

/**
 * OpenTarget 以系统默认方式打开搜索结果目标：
 *   - 目录 → 资源管理器打开该目录；
 *   - 文件 → 默认关联程序打开（rundll32 FileProtocolHandler，不限于 exe 等可执行文件）。
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenTarget(path) {
    return $Call.ByID(108223454, path);
}

/**
 * OpenWindow 打开/唤起搜索窗口：
 *   - 运行中（自有/外部）→ 单实例协议信使唤窗；
 *   - 未运行 → 窗口模式冷启动。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(1139898051);
}

/**
 * Quit 退出 Everything。
 * 外部实例不越权强杀（实例探测拿不到 PID）：仅返回人性化指引。
 * 自有实例走 -quit 优雅退出（先落盘索引库），超时由引擎强杀兜底。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(2145821456);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(2423686741, targetVersion);
}

/**
 * RevealTarget 在资源管理器中定位并选中目标（文件/目录通用）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义在文件对象上是"执行"而非"定位"
 * （markeron「打开安装目录」按钮的事故教训：传 exe 路径直接启动了程序）。
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RevealTarget(path) {
    return $Call.ByID(492552139, path);
}

/**
 * Search 内嵌搜索：查询运行中实例的索引，返回路径列表。
 * 无实例时先懒启动后台实例（等待就绪后查询），用户无感衔接。
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<search$0.Result[] | null>}
 */
export function Search(query, limit) {
    return $Call.ByID(1504903223, query, limit);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(2639376073, targetVersion);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 优雅退出自有实例（5s 兜底强杀）。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1958107661);
}

/**
 * StartBackground 启动后台实例（-startup：后台驻留建索引，不弹搜索窗）。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function StartBackground() {
    return $Call.ByID(328363813);
}
