// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../../platform/models.js";

/**
 * NetworkOverview 综合 IP 与网络详情
 * @typedef {Object} NetworkOverview
 * @property {string} publicIpv4 - 出口公网信息
 * @property {string} publicIpv6
 * @property {string} sourceV4
 * @property {string} sourceV6
 * @property {string} fetchedAt
 * @property {platform$0.Adapter[] | null} adapters - 本机物理与虚拟网卡详情列表
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
