// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetNetworkOverview 获取完整的出口公网 IP、局域网 IP、网关与 DNS 列表（2分钟内直接命中缓存）
 * @param {boolean} forceRefresh
 * @returns {$CancellablePromise<$models.NetworkOverview>}
 */
export function GetNetworkOverview(forceRefresh) {
    return $Call.ByID(3333703889, forceRefresh).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * PingTarget 对目标域名或 IP 执行探测（默认探测 4 次）
 * @param {string} target
 * @param {number} count
 * @returns {$CancellablePromise<$models.PingSummary>}
 */
export function PingTarget(target, count) {
    return $Call.ByID(4267404993, target, count).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * TraceRoute 执行路由追踪（基于 tracert / 本地探测，最大 30 跳）
 * @param {string} target
 * @param {number} maxHops
 * @returns {$CancellablePromise<$models.TracerouteSummary>}
 */
export function TraceRoute(target, maxHops) {
    return $Call.ByID(2608082106, target, maxHops).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.NetworkOverview.createFrom;
const $$createType1 = $models.PingSummary.createFrom;
const $$createType2 = $models.TracerouteSummary.createFrom;
