// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FlClashService 向前端暴露 FlClash 版本管理与窗口唤起能力。
 * 代理订阅/节点配置不内嵌：打开 FlClash 自有窗口操作（界面完整，
 * 配置数据在 %APPDATA% 用户目录，各版本共享）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDesktopShortcut 在桌面为当前使用版本创建快捷方式（同名覆盖）。
 * @returns {$CancellablePromise<void>}
 */
export function CreateDesktopShortcut() {
    return $Call.ByID(3743436157);
}

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 flclash:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(3552819623, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(3203367191);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 true）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(443031831);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(4048668125);
}

/**
 * ImportLocal 导入本地已有的 FlClash 便携目录（黑名单整搬：exe+dll+data+全套）。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 文件被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.FlClashVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(3247500043, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表。
 * @returns {$CancellablePromise<version$0.FlClashVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(1674422552);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.FlClashRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(2297271047);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义在文件对象上是"执行"
 * 而非"打开"（markeron「打开安装目录」按钮的事故教训：传 exe 路径直接启动了程序）。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(2619127364, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(2657123205);
}

/**
 * OpenWindow 窗口唤起编排中枢：
 *   - external：进程枚举拿外部 PID → EnumWindows SW_RESTORE+SetForegroundWindow
 *     直接唤窗（FlClash 二次启动只退出不唤窗，不能走信使）；
 *   - running：自有实例同样直操作窗口；
 *   - stopped/failed：解析 active 版本直接无参启动（FlClash 启动即开窗）。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(391225549);
}

/**
 * Quit 退出引擎托管的 FlClash。
 * external 状态不越权强杀（进程枚举拿到的 PID 非我方托管）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(533458778);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(4187786179, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(3771132890);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(4261636939, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(2551686603, b);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 终止自有实例。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2276360415);
}
