// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as BCUService from "./bcuservice.js";
export {
    BCUService
};

import * as $models from "./models.js";

/**
 * ControlOutcome 打开窗口操作的执行结果说明。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * DotnetEnv 本机 .NET 桌面运行时环境探测结果（框架依赖变体的推荐依据）。
 * @typedef {$models.DotnetEnv} DotnetEnv
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */
