// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    State
} from "./models.js";

import * as $models from "./models.js";

/**
 * LogEntry 单条实例日志行（事件 ddnsgo:instance-log 载荷）。
 * @typedef {$models.LogEntry} LogEntry
 */

/**
 * Snapshot 引擎状态快照：事件推送与前端渲染共用同一模型。
 * @typedef {$models.Snapshot} Snapshot
 */
