// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Adapter 网卡信息
 * @typedef {Object} Adapter
 * @property {number} index
 * @property {string} name
 * @property {string} description
 * @property {string} mac
 * @property {string[] | null} ipv4
 * @property {string[] | null} ipv6
 * @property {IPv6Detail[] | null} ipv6Details
 * @property {string} gateway
 * @property {string} ipv6Gateway
 * @property {string[] | null} dnsServers
 * @property {boolean} isPhysical
 * @property {boolean} isLoopback
 * @property {boolean} isUp
 */

/**
 * IPv6Detail 详细 IPv6 地址（公网、临时、链路本地）
 * @typedef {Object} IPv6Detail
 * @property {string} address
 * @property {string} type - "Public" (公网/主地址) | "Temporary" (临时隐私地址) | "LinkLocal" (链路本地)
 * @property {boolean} isTemporary
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
