// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GuoheViewService 向前端暴露果核看图版本管理与窗口唤起能力。
 * 看图界面本身不内嵌：上游是原生极速渲染（自研解码内核 + 分块加载 + ICC 色彩
 * 管理），内嵌重做毫无性价比，所有浏览操作在 GuoheView 自有窗口完成。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 guoheview:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(1133340071, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(3110683927);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 true）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(2318519575);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(3914060253);
}

/**
 * ImportLocal 导入本地已有的果核看图便携目录（整套搬运，含 config.ini 设置）。
 * 运行中的实例拒绝导入：Windows 下运行中的文件被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.ViewVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(3101153035, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表。
 * @returns {$CancellablePromise<version$0.ViewVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(3488216344);
}

/**
 * ListReleases 获取远程可用版本（上游只发布当前版本，至多 stable+beta 两条）。
 * @returns {$CancellablePromise<version$0.ViewRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(3448968967);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义在文件对象上是"执行"
 * 而非"打开"（markeron「打开安装目录」按钮的事故教训：传 exe 路径直接启动了程序）。
 * 这里入参恒为目录，语义安全，但仍走本模块自有实现保持行为显式。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(294445636, dir);
}

/**
 * OpenRepository 用默认浏览器打开官网页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(2938871685);
}

/**
 * OpenWindow 窗口唤起编排中枢（多实例上游的正确契约，见 instance 包注释）：
 *   - running：聚焦自有托管实例主窗口；窗口尚未出现的极窄竞态给出"启动中"提示；
 *   - external：优先唤回用户已打开的看图窗口；无可聚焦窗口则另开独立窗口
 *     （不进 Job、不随 Hanxi 退出——与用户双击图片的实例同等地位）；
 *   - stopped/failed：解析 active 版本无参启动托管实例。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(1978827981);
}

/**
 * Quit 优雅退出托管实例（WM_CLOSE 关窗即退 + 宽限 + Job 兜底，实证见 instance 包注释）。
 * external 状态不越权强杀（用户自行打开的窗口归用户）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(2798973786);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(170612675, targetVersion);
}

/**
 * RepositoryURL 官网地址（上游闭源无仓库页；前端展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(4048926682);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(4168953675, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(132207051, b);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 终止自有实例。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1732494559);
}
