// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DirUsage 一个推导出的目录及其度量结果（Partial=true 时 Bytes 为下限估算）。
 * @typedef {$models.DirUsage} DirUsage
 */

/**
 * ToolUsage 一个工具的家底清单（Dirs 首项恒为本体，若可推导）。
 * @typedef {$models.ToolUsage} ToolUsage
 */
