// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as FileShareService from "./fileshareservice.js";
export {
    FileShareService
};

import * as $models from "./models.js";

/**
 * DropItem 局域网访客投递的文本/链接
 * @typedef {$models.DropItem} DropItem
 */

/**
 * NetworkEndpoint 局域网接入点信息
 * @typedef {$models.NetworkEndpoint} NetworkEndpoint
 */

/**
 * ServerStatus 服务运行时状态
 * @typedef {$models.ServerStatus} ServerStatus
 */

/**
 * ShareConfig 局域网共享服务配置
 * @typedef {$models.ShareConfig} ShareConfig
 */

/**
 * TransferEvent 文件传输审计事件 (用于界面日志流)
 * @typedef {$models.TransferEvent} TransferEvent
 */
