// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as RAMMapService from "./rammapservice.js";
export {
    RAMMapService
};

import * as $models from "./models.js";

/**
 * ControlOutcome OpenWindow 编排回执（多实例：聚焦自有/唤回外部/冷启动由后端裁决）。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * QuitOutcome 退出请求结果（自有实例或按 N3 force-free 档处置的外部实例）。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */

/**
 * StatusInfo 前端状态投影：宿主提权态与目标 manifest 预判。
 * @typedef {$models.StatusInfo} StatusInfo
 */
