// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ControlOutcome OpenWindow 编排回执（多实例：聚焦自有/唤回外部/冷启动由后端裁决）。
 * @typedef {Object} ControlOutcome
 * @property {string} action - started / started-external-elevated / focused / external-focused / starting / external-unreachable
 * @property {boolean} external
 * @property {boolean} elevated
 * @property {boolean} managed
 * @property {boolean} canQuit
 * @property {string} launchMode - managed / external-elevated / external
 * @property {string} message
 */

/**
 * QuitOutcome 退出请求结果（自有实例或按 N3 force-free 档处置的外部实例）。
 * @typedef {Object} QuitOutcome
 * @property {boolean} stopped
 * @property {boolean} forced
 * @property {boolean} closeRequested
 * @property {string} method
 * @property {boolean} external
 * @property {string} message
 */

/**
 * StatusInfo 前端状态投影：宿主提权态与目标 manifest 预判。
 * @typedef {Object} StatusInfo
 * @property {boolean} requiresElevation
 * @property {boolean} hostElevated
 * @property {string} executionLevel
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
