// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FrpcService 向前端暴露 frp 版本管理与项目实例管理能力
 * （M4.1 版本管理 + M4.2 项目 CRUD + M4.3 多实例运行引擎）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

/**
 * DeleteProject 删除项目（若实例在运行则先停止再移除）
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProject(id) {
    return $Call.ByID(801664446, id);
}

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经由事件 frpc:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(2012837686, targetVersion);
}

/**
 * GenerateToml 生成项目配置的 TOML 预览文本（不落盘，供编辑页展示与校验）
 * @param {domain$0.Project} p
 * @returns {$CancellablePromise<string>}
 */
export function GenerateToml(p) {
    return $Call.ByID(1656285533, p);
}

/**
 * GetProject 按 ID 查询单个项目
 * @param {string} id
 * @returns {$CancellablePromise<domain$0.Project | null>}
 */
export function GetProject(id) {
    return $Call.ByID(3606904391, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetProjectLogs 拉取项目实例最近日志（lastN <= 0 返回全部缓冲）。
 * @param {string} id
 * @param {number} lastN
 * @returns {$CancellablePromise<string[]>}
 */
export function GetProjectLogs(id, lastN) {
    return $Call.ByID(2550889948, id, lastN).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ImportLocalFrpc 弹窗选择本地 frpc.exe 并导入（自动探测版本号）
 * @returns {$CancellablePromise<version$0.FrpVersionInfo>}
 */
export function ImportLocalFrpc() {
    return $Call.ByID(2113418499).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListInstalledVersions 获取本地已安装版本列表
 * @returns {$CancellablePromise<version$0.FrpVersionInfo[]>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(2732803105).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListInstanceStates 返回全部项目实例状态（含已停止的历史实例）。
 * @returns {$CancellablePromise<instance$0.Snapshot[]>}
 */
export function ListInstanceStates() {
    return $Call.ByID(2425021763).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListProjects 返回全部 frpc 项目
 * @returns {$CancellablePromise<domain$0.Project[]>}
 */
export function ListProjects() {
    return $Call.ByID(1588642172).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListReleases 获取远程可用版本列表（GitHub 官方源 + 镜像回退，10 分钟缓存）
 * @returns {$CancellablePromise<version$0.FrpRelease[]>}
 */
export function ListReleases() {
    return $Call.ByID(2381381988).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ParseToml 从用户粘贴/导入的 frp TOML 配置解析回领域模型（兼容 v1.x 与 v0.x 格式）
 * @param {string} content
 * @returns {$CancellablePromise<domain$0.Project>}
 */
export function ParseToml(content) {
    return $Call.ByID(1525046141, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RemoveVersion 卸载已安装版本
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(1140696706, targetVersion);
}

/**
 * SaveProject 新建或更新项目（空 ID 表示新建）
 * @param {domain$0.Project} p
 * @returns {$CancellablePromise<domain$0.Project>}
 */
export function SaveProject(p) {
    return $Call.ByID(1314615508, p).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * StartProject 启动项目实例：解析绑定版本 → 生成 TOML 落盘 → 拉起 frpc.exe 并绑定 JobObject。
 * 启动后状态/日志经事件 frpc:instance-state / frpc:instance-log 持续推送。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StartProject(id) {
    return $Call.ByID(2863609475, id);
}

/**
 * StopProject 停止项目实例（幂等）。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function StopProject(id) {
    return $Call.ByID(1466787459, id);
}

// Private type creation functions
const $$createType0 = domain$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = version$0.FrpVersionInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = instance$0.Snapshot.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = version$0.FrpRelease.createFrom;
const $$createType9 = $Create.Array($$createType8);
