// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as detect$0 from "../detect/models.js";

/**
 * Overview 组合本机 Git 探测结果与官网近期稳定版本。
 * @typedef {Object} Overview
 * @property {detect$0.ToolInfo} local
 * @property {Release[] | null} releases
 * @property {Relation} relation
 * @property {boolean} isStale
 */

/**
 * Relation 表示本机 Git 与官网最新 Git for Windows 稳定版的关系。
 * @readonly
 * @enum {string}
 */
export const Relation = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RelationUnknown: "unknown",
    RelationNotInstalled: "not-installed",
    RelationLatest: "latest",
    RelationUpdateAvailable: "update-available",
    RelationAhead: "ahead",
};

/**
 * Release 表示一个 Git for Windows 官网稳定版本。
 * @typedef {Object} Release
 * @property {string} version
 * @property {string} published
 * @property {boolean} stale
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
