// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LanService 局域网扫描服务。同一时刻仅允许一轮扫描：
 * scanning 原子标志做快速拒重入，cancelScan 记录在途扫描的取消函数（mu 保护读写），
 * 模块 OnDestroy/用户手动停止都经 Cancel 终止 goroutine 并释放 context。
 * 所有业务 RPC 方法经 holder.Enter() 接入统一调用门（Wave 3）：
 * 停用/未安装模块的任何方法调用被拒，扫描在途期间停用会等待 drain。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel 取消当前正在进行的扫描（前端 RPC 导出版：接调用门，停用后拒绝新调用）。
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(2032911531);
}

/**
 * GetSubnets 列出所有可用于扫描的候选网卡子网，支持常见掩码计算
 * @returns {$CancellablePromise<$models.SubnetInfo[] | null>}
 */
export function GetSubnets() {
    return $Call.ByID(323478119);
}

/**
 * Scan 执行并发网段/IP范围扫描
 * @param {string} targetRange
 * @returns {$CancellablePromise<$models.DeviceInfo[] | null>}
 */
export function Scan(targetRange) {
    return $Call.ByID(1483878040, targetRange);
}

/**
 * SetRemark 保存 IP 或 MAC 的用户自定义备注
 * @param {string} key
 * @param {string} remark
 * @returns {$CancellablePromise<void>}
 */
export function SetRemark(key, remark) {
    return $Call.ByID(917148571, key, remark);
}
