// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as HistoryService from "./historyservice.js";
export {
    HistoryService
};

import * as $models from "./models.js";

/**
 * Record 一条历史记录。四文本字段（Summary/Input/Output/Extra）在 Save 入口
 * 统一过脱敏与截断，调用方直接传原文即可。
 * @typedef {$models.Record} Record
 */

/**
 * Store 历史记录存储：内存权威副本 + 每次变更全量原子覆写落盘。
 * 所有公开方法整体持锁（单用户桌面写入频率远低于全量写成本，一把锁收口最简）；
 * 损坏（loadErr 驻留）后禁一切写，读侧返回错误供面板提示。
 * @typedef {$models.Store} Store
 */
