// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 下载过程实时进度
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - resolve/downloading/hash/extract/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * FrpRelease 远程 GitHub Release 中可用的 frp Windows amd64 版本
 * @typedef {Object} FrpRelease
 * @property {string} version - 如 v0.61.1
 * @property {string} published - 发布时间（RFC3339）
 * @property {boolean} isPre - 是否为预发布版本
 * @property {string} assetName - 如 frp_0.61.1_windows_amd64.zip
 * @property {string} assetUrl - 直链下载地址
 * @property {number} size - 资产大小（字节）
 * @property {string} sha256 - 官方 sha256-checksums.txt 中对应的哈希
 */

/**
 * FrpVersionInfo 本地已安装的 frp 版本信息
 * @typedef {Object} FrpVersionInfo
 * @property {string} version - 如 v0.61.1
 * @property {string} exePath - frpc.exe 完整路径（供实例启动使用）
 * @property {number} size - frpc.exe 大小（字节）
 * @property {string} sha256 - 文件哈希（校验依据）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否手动导入（非官方下载）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
