// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * FlClashRelease 远程 GitHub Release 中可用的 FlClash Windows x64 便携版。
 * @typedef {$models.FlClashRelease} FlClashRelease
 */

/**
 * FlClashVersionInfo 本地已安装的 FlClash 版本信息。
 * @typedef {$models.FlClashVersionInfo} FlClashVersionInfo
 */
