// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - resolve/downloading/verify/extract/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * FlClashRelease 远程 GitHub Release 中可用的 FlClash Windows x64 便携版。
 * @typedef {Object} FlClashRelease
 * @property {string} version - 如 0.8.96（无 v）
 * @property {string} tag - release tag（如 v0.8.96）——下载 URL 拼路径用
 * @property {string} published - 发布时间（RFC3339）
 * @property {boolean} isPre - 是否为预发布版本
 * @property {string} assetName - 如 FlClash-0.8.96-windows-amd64.zip
 * @property {string} assetUrl - 资产下载地址（302 到 CDN）
 * @property {number} size - 资产大小（字节）
 * @property {string} sha256 - 官方 sha256（GitHub API digest 去掉前缀）
 */

/**
 * FlClashVersionInfo 本地已安装的 FlClash 版本信息。
 * @typedef {Object} FlClashVersionInfo
 * @property {string} version - 如 0.8.96
 * @property {string} exePath - FlClash.exe 完整路径（供启动/唤窗使用）
 * @property {string} dir - 版本隔离目录
 * @property {number} size - FlClash.exe 大小（字节）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录（仅导入安装时有值）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
