// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @typedef {Object} CachedPackage
 * @property {string} version
 * @property {string} path
 * @property {string} dir
 * @property {number} size
 * @property {string} sha256
 * @property {string} cachedAt
 * @property {string} verificationMode
 * @property {string[] | null} architectures
 */

/**
 * @typedef {Object} Release
 * @property {string} version
 * @property {string} published
 * @property {string} assetName
 * @property {string} assetUrl
 * @property {number} size
 * @property {string} sha256
 * @property {boolean} stale
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
