// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadProgress 下载与安装过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version
 * @property {string} stage - resolve/downloading/verify/install/done/error
 * @property {number} done
 * @property {number} total
 * @property {string} message
 */

/**
 * IntegrityState 本地安装的完整性状态。
 * @readonly
 * @enum {string}
 */
export const IntegrityState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    IntegrityVerified: "verified",
    IntegrityLocalBaseline: "local-baseline",
    IntegrityDrifted: "drifted",
    IntegrityInvalid: "invalid",
};

/**
 * MangoDiskRelease 远程 GitHub Release 中可用的 Windows x64 portable GUI。
 * @typedef {Object} MangoDiskRelease
 * @property {string} version
 * @property {string} published
 * @property {boolean} isPre
 * @property {string} assetName
 * @property {string} assetUrl
 * @property {number} size
 * @property {string} sha256
 */

/**
 * MangoDiskVersionInfo 本地已安装版本信息。
 * @typedef {Object} MangoDiskVersionInfo
 * @property {string} version
 * @property {string} exePath
 * @property {string} dir
 * @property {number} size
 * @property {string} installedAt
 * @property {boolean} isImport
 * @property {string} source
 * @property {IntegrityState} integrity
 * @property {string} integrityNote
 * @property {string} expectedSha256
 * @property {string} currentSha256
 * @property {string} fileVersion
 * @property {string} productName
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
