// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Scheduler 更新感知调度器：注册表 + 模块检查器集合 + 结果缓存（state 目录）。
 * @typedef {$models.Scheduler} Scheduler
 */
