// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Scheduler 更新感知调度器：注册表 + 模块检查器集合 + 结果缓存（state 目录）。
 * @typedef { {
 * } } Scheduler
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
