// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    DeliveryKind,
    DeliveryState,
    Entrypoint,
    HealthState,
    Level,
    NavGroup,
    NavSection,
    OperationKind,
    OperationStatus,
    Permission,
    PolicyState,
    PrimaryAction,
    RuntimeState,
    SummaryKey
} from "./models.js";

import * as $models from "./models.js";

/**
 * Compatibility 声明模块可运行的宿主与平台约束（Phase 1-2 内建模块总是兼容）。
 * @typedef {$models.Compatibility} Compatibility
 */

/**
 * ModuleCatalogItem 描述"模块是谁、如何交付、有哪些入口和能力"，
 * 不承载瞬时进度；由装配根 Catalog 表（app/catalog.go）投影，
 * 基线冻结于 scripts/fixture/module_catalog.json 并由契约测试守护。
 * @typedef {$models.ModuleCatalogItem} ModuleCatalogItem
 */

/**
 * ModuleInfo 模块元信息。
 * @typedef {$models.ModuleInfo} ModuleInfo
 */

/**
 * ModuleState 是模块在当前设备上的四维事实 + 派生主操作。
 * Registry 是唯一权威源；前端只缓存投影，不得持久化第二份真相。
 * @typedef {$models.ModuleState} ModuleState
 */

/**
 * NavEntry 描述左侧导航中的一项（前端据此注册路由）。
 * @typedef {$models.NavEntry} NavEntry
 */

/**
 * Operation 统一表达安装、启停、更新、回滚、修复、卸载与业务调用的生命周期；
 * 同一 Operation 应能被模块中心详情、首页最近任务与诊断视图观察，
 * 前端重载后能从后端恢复，而非依赖组件内存。
 * @typedef {$models.Operation} Operation
 */

/**
 * OperationError 结构化错误：code 稳定可枚举，recoverable 决定是否引导重试。
 * @typedef {$models.OperationError} OperationError
 */
