// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Compatibility 声明模块可运行的宿主与平台约束（Phase 1-2 内建模块总是兼容）。
 * @typedef {Object} Compatibility
 * @property {string} hostRange - 宿主版本区间，"*" 表示任意当前宿主
 * @property {string[] | null} platform - 目标平台（windows 等）
 */

/**
 * DeliveryKind 描述模块的交付形态。Phase 1-2 仅 builtin-logical 落地；
 * managed-declarative 与 official-sidecar 分别对应 Wave 5 / Wave 6。
 * @readonly
 * @enum {string}
 */
export const DeliveryKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * DeliveryBuiltinLogical 内建代码 + 逻辑安装凭据：代码始终随宿主发布，
     * "卸载"仅移除逻辑 receipt 与入口，不释放宿主体积——UI 文案必须如实表达。
     */
    DeliveryBuiltinLogical: "builtin-logical",

    /**
     * DeliveryManagedDeclarative 官方签名声明驱动的共享托管模块（Wave 5+）。
     */
    DeliveryManagedDeclarative: "managed-declarative",

    /**
     * DeliveryOfficialSidecar 官方复杂功能独立交付包（Wave 6+）。
     */
    DeliveryOfficialSidecar: "official-sidecar",
};

/**
 * DeliveryState 交付维度：本机是否持有可运行的安装凭据/资产。
 * @readonly
 * @enum {string}
 */
export const DeliveryState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * DeliveryAbsent 逻辑未安装，或本机无可用声明/sidecar/所需资产。
     */
    DeliveryAbsent: "absent",

    /**
     * DeliveryInstalling 正在安装逻辑凭据、托管资产或官方包。
     */
    DeliveryInstalling: "installing",

    /**
     * DeliveryInstalled 已安装并有完整 receipt。
     */
    DeliveryInstalled: "installed",

    /**
     * DeliveryUpdating 更新事务进行中，旧版本尽量保持可用。
     */
    DeliveryUpdating: "updating",

    /**
     * DeliveryRemoving 正在停止并移除。
     */
    DeliveryRemoving: "removing",

    /**
     * DeliveryRepairing 正在按可信清单修复。
     */
    DeliveryRepairing: "repairing",

    /**
     * DeliveryOrphaned 磁盘内容与 receipt/Catalog 不一致。
     */
    DeliveryOrphaned: "orphaned",
};

/**
 * Entrypoint 模块对外暴露的能力入口类型。可见性与调用门按入口统一裁决：
 * 未安装或停用模块不得从任一入口旁路执行。
 * @readonly
 * @enum {string}
 */
export const Entrypoint = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * EntryRPC Wails 服务方法调用。
     */
    EntryRPC: "rpc",

    /**
     * EntryNavigation 侧栏/路由导航。
     */
    EntryNavigation: "navigation",

    /**
     * EntrySearch 命令面板与全局搜索。
     */
    EntrySearch: "search",

    /**
     * EntryTray 系统托盘菜单与命令。
     */
    EntryTray: "tray",

    /**
     * EntryHotkey 全局热键。
     */
    EntryHotkey: "hotkey",

    /**
     * EntryMCP MCP 工具暴露。
     */
    EntryMCP: "mcp",

    /**
     * EntryWindow 独立窗口（quickmenu/webapp/msgboard 等）。
     */
    EntryWindow: "window",

    /**
     * EntryBackground 启动预激活与常驻后台任务。
     */
    EntryBackground: "background",
};

/**
 * HealthState 健康与版本维度：本机内容与官方目录的一致性判断。
 * Phase 1-2 内建逻辑模块恒为 current；其余取值服务 Wave 4+ 托管与签名目录。
 * @readonly
 * @enum {string}
 */
export const HealthState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * HealthCurrent 当前版本可用且无已知更新。
     */
    HealthCurrent: "current",

    /**
     * HealthUpdateAvailable 有兼容更新。
     */
    HealthUpdateAvailable: "update-available",

    /**
     * HealthPinned 用户固定版本。
     */
    HealthPinned: "pinned",

    /**
     * HealthIncompatible 与宿主、策略、架构或上游环境不兼容。
     */
    HealthIncompatible: "incompatible",

    /**
     * HealthCorrupt 摘要、布局或 receipt 不一致。
     */
    HealthCorrupt: "corrupt",

    /**
     * HealthRevoked 官方目录撤回当前声明或包。
     */
    HealthRevoked: "revoked",

    /**
     * HealthUnverified 缺少有效官方验证，不可激活。
     */
    HealthUnverified: "unverified",

    /**
     * HealthDegraded 可用但部分探测、来源或能力异常。
     */
    HealthDegraded: "degraded",

    /**
     * HealthOfflineStale 本地目录过期，已有版本按离线策略继续使用。
     */
    HealthOfflineStale: "offline-stale",
};

/**
 * Level 模块级别。
 * @readonly
 * @enum {string}
 */
export const Level = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * LevelBuiltin 编译进主程序的内建模块，可启停但不可卸载。
     */
    LevelBuiltin: "builtin",

    /**
     * LevelExternal 外部子进程模块（未来），可通过模块管理页独立安装/卸载。
     */
    LevelExternal: "external",
};

/**
 * ModuleCatalogItem 描述"模块是谁、如何交付、有哪些入口和能力"，
 * 不承载瞬时进度；由装配根 Catalog 表（app/catalog.go）投影，
 * 基线冻结于 scripts/fixture/module_catalog.json 并由契约测试守护。
 * @typedef {Object} ModuleCatalogItem
 * @property {string} id
 * @property {string} name
 * @property {string} description - 展示描述（与 ModuleInfo.Description 同源，模块中心卡片/搜索消费）
 * @property {string} category - NavGroup 六组值之一；"core" 保留给控制平面
 * @property {DeliveryKind} delivery
 * @property {string[] | null} capabilities - 能力标记（如 managed-versions/tray-commands）
 * @property {Entrypoint[] | null} entrypoints - 该模块暴露的全部入口
 * @property {Compatibility} compatibility
 * @property {Permission[] | null} permissions - 需要的受控权限（Wave 0 允许为空）
 * @property {string} owner - 维护 owner（官方清点口径，发布职责不可无主）
 */

/**
 * ModuleInfo 模块元信息。
 * @typedef {Object} ModuleInfo
 * @property {string} id
 * @property {string} name
 * @property {string} version
 * @property {string} description
 * @property {string} author
 * @property {Level} level
 * @property {boolean} removable - 仅 LevelExternal 为 true
 * @property {boolean} enabled
 * @property {boolean} initialized - 当前是否已被按需分配运行时资源
 * @property {boolean} installed - 是否持有逻辑安装凭据（receipt，ADR-0001 §1.5）
 */

/**
 * ModuleState 是模块在当前设备上的四维事实 + 派生主操作。
 * Registry 是唯一权威源；前端只缓存投影，不得持久化第二份真相。
 * @typedef {Object} ModuleState
 * @property {number} schema - ModuleContractSchema
 * @property {string} moduleId
 * @property {DeliveryState} delivery
 * @property {PolicyState} policy
 * @property {RuntimeState} runtime
 * @property {HealthState} health
 * @property {PrimaryAction} primaryAction
 * @property {string} [reason] - ActionNone/受阻时的人类可读原因
 * @property {SummaryKey} summary - 派生摘要语义键
 */

/**
 * NavEntry 描述左侧导航中的一项（前端据此注册路由）。
 * @typedef {Object} NavEntry
 * @property {string} id
 * @property {string} title
 * @property {string} route
 * @property {string} icon
 * @property {NavSection} section
 * @property {number} order
 * @property {NavGroup} [group]
 */

/**
 * NavGroup 区分外壳双栏导航中的能力分组（左栏分组目录的归属依据）。
 * @readonly
 * @enum {string}
 */
export const NavGroup = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 网络与传输
     */
    GroupNetwork: "network",

    /**
     * 系统管理
     */
    GroupSystem: "system",

    /**
     * 桌面增强
     */
    GroupDesktop: "desktop",

    /**
     * 效率办公
     */
    GroupEfficiency: "efficiency",

    /**
     * 媒体影音
     */
    GroupMedia: "media",

    /**
     * 开发者工具
     */
    GroupDeveloper: "developer",
};

/**
 * NavSection 区分核心导航与扩展导航两个分区。
 * @readonly
 * @enum {string}
 */
export const NavSection = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SectionCore: "core",
    SectionExt: "ext",
};

/**
 * Operation 统一表达安装、启停、更新、回滚、修复、卸载与业务调用的生命周期；
 * 同一 Operation 应能被模块中心详情、首页最近任务与诊断视图观察，
 * 前端重载后能从后端恢复，而非依赖组件内存。
 * @typedef {Object} Operation
 * @property {number} schema
 * @property {string} id
 * @property {string} [txnId] - TxnID 是支撑该操作的 journal 事务裸 ID（可空=纯内存操作无账本）。 resumable 回灌记录的 ID 是展示用合成键，DismissResumable 等收口通道 一律消费本字段——前端禁止从 ID 剥前缀反推事务。
 * @property {string} moduleId
 * @property {OperationKind} kind
 * @property {string} phase
 * @property {OperationStatus} status
 * @property {number | null} [progress] - 0-100；nil=不可量化
 * @property {boolean} cancellable
 * @property {string} startedAt - RFC3339
 * @property {string} [finishedAt]
 * @property {OperationError | null} [error]
 */

/**
 * OperationError 结构化错误：code 稳定可枚举，recoverable 决定是否引导重试。
 * @typedef {Object} OperationError
 * @property {string} code
 * @property {string} message
 * @property {boolean} recoverable
 */

/**
 * OperationKind 操作类型。invoke 表示业务调用租约（Acquire 产物），
 * 生命周期操作（install/remove/…）与业务调用共享同一观察协议。
 * @readonly
 * @enum {string}
 */
export const OperationKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OpInstall: "install",
    OpActivate: "activate",
    OpStop: "stop",
    OpUpdate: "update",
    OpRollback: "rollback",
    OpRepair: "repair",
    OpRemove: "remove",
    OpInvoke: "invoke",
};

/**
 * OperationStatus 操作终态机。
 * @readonly
 * @enum {string}
 */
export const OperationStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OpQueued: "queued",
    OpRunning: "running",
    OpSucceeded: "succeeded",
    OpFailed: "failed",
    OpCancelled: "cancelled",
};

/**
 * Permission 声明扩展所需的能力。运行期由宿主白名单校验，
 * 扩展不得绕过宿主 API（host）直接操作系统资源。
 * 注：Module 契约的 Permissions() 已作为死代码移除（无任何调用方），
 * 类型与常量保留给未来子进程插件（LevelExternal）的能力握手复用。
 * @readonly
 * @enum {string}
 */
export const Permission = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 结束进程：宿主强制 PID 复核 + 保护规则
     */
    PermKillProcess: "kill-process",

    /**
     * 局域网探测
     */
    PermLANScan: "lan-scan",

    /**
     * 出站网络访问
     */
    PermNetwork: "network",
};

/**
 * PolicyState 策略维度：用户/平台是否允许使用。
 * @readonly
 * @enum {string}
 */
export const PolicyState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * PolicyEnabled 允许进入导航和调用门。
     */
    PolicyEnabled: "enabled",

    /**
     * PolicyDisabled 已安装但停用。
     */
    PolicyDisabled: "disabled",

    /**
     * PolicyBlocked 因不兼容、撤回、恢复或安全策略禁止启动。
     */
    PolicyBlocked: "blocked",

    /**
     * PolicyPendingConsent 新权限或数据迁移等待用户确认。
     */
    PolicyPendingConsent: "pending-consent",

    /**
     * PolicyMandatory Core 控制平面：不允许卸载或停用。
     */
    PolicyMandatory: "mandatory",
};

/**
 * PrimaryAction 状态机计算出的卡片主操作语义键。前端按词汇表映射文案，
 * 不得依据维度自行推断。
 * @readonly
 * @enum {string}
 */
export const PrimaryAction = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ActionInstall 逻辑安装（builtin-logical：仅登记凭据与入口）。
     */
    ActionInstall: "install",

    /**
     * ActionEnable 启用。
     */
    ActionEnable: "enable",

    /**
     * ActionDisable 停用。
     */
    ActionDisable: "disable",

    /**
     * ActionOpen 打开/进入（含懒激活）。
     */
    ActionOpen: "open",

    /**
     * ActionUpdate 更新到新版本。
     */
    ActionUpdate: "update",

    /**
     * ActionRetry 重试初始化/恢复（崩溃或失败后）。
     */
    ActionRetry: "retry",

    /**
     * ActionRepair 按可信清单修复。
     */
    ActionRepair: "repair",

    /**
     * ActionUninstall 卸载。
     */
    ActionUninstall: "uninstall",

    /**
     * ActionNone 无可执行主操作（进行中或被阻止），以 Reason 说明。
     */
    ActionNone: "none",
};

/**
 * RuntimeState 运行维度：当前是否占用运行资源。
 * 由 Registry wrapper 事实派生：enabled=false→inactive；initializing→activating；
 * stopping→stopping；inFlight>0→busy；initialized→active；init 失败滞留→failed。
 * @readonly
 * @enum {string}
 */
export const RuntimeState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * RuntimeInactive 没有运行资源。
     */
    RuntimeInactive: "inactive",

    /**
     * RuntimeActivating 正在初始化、启动或探测。
     */
    RuntimeActivating: "activating",

    /**
     * RuntimeActive 可接受调用。
     */
    RuntimeActive: "active",

    /**
     * RuntimeBusy 有在途操作。
     */
    RuntimeBusy: "busy",

    /**
     * RuntimeStopping 正在 drain/cancel/destroy。
     */
    RuntimeStopping: "stopping",

    /**
     * RuntimeCrashed 受管进程异常退出。
     */
    RuntimeCrashed: "crashed",

    /**
     * RuntimeFailed 初始化或恢复失败（滞留在 wrapper，待重试）。
     */
    RuntimeFailed: "failed",
};

/**
 * SummaryKey 四维状态派生出的稳定摘要语义键，供首页/模块中心/详情共用同一词汇。
 * @readonly
 * @enum {string}
 */
export const SummaryKey = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 未安装
     */
    SummaryNotInstalled: "not-installed",

    /**
     * 已安装，未启用
     */
    SummaryInstalledIdle: "installed-disabled",

    /**
     * 运行中
     */
    SummaryRunning: "running",

    /**
     * 运行中，有更新
     */
    SummaryRunningUpdate: "running-update",

    /**
     * 已阻止运行（撤回/不兼容/策略）
     */
    SummaryBlocked: "blocked",

    /**
     * 异常，可重试或诊断
     */
    SummaryFaulted: "faulted",

    /**
     * 安装/更新/卸载/修复进行中
     */
    SummaryBusyOperation: "in-progress",

    /**
     * 已安装，未运行
     */
    SummaryIdleEnabled: "installed-enabled",
};

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
