// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as KeyvizService from "./keyvizservice.js";
export {
    KeyvizService
};

import * as $models from "./models.js";

/**
 * ControlOutcome 启动操作的执行结果说明。
 * Keyviz 无唤窗契约（上游单实例回调为空），控制动作只有启动语义。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */
