// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hostfeed$0 from "../../../../packages/go/hostfeed/models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - resolve/downloading/verify/extract/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * TBRelease 远程 GitHub Release 中可用的 TranslucentTB Windows x64 便携版。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验第一依据）。
 * 版本号形如 2026.2（年份.序号，上游惯例，无 v 前缀）。
 * @typedef {Object} TBRelease
 * @property {string} version - 如 2026.2
 * @property {string} published - 发布时间（RFC3339）
 * @property {boolean} isPre - 是否为预发布版本
 * @property {string} assetName - 如 TranslucentTB-portable-x64.zip
 * @property {string} assetUrl - 资产下载地址（302 到 CDN）
 * @property {number} size - 资产大小（字节）
 * @property {string} sha256 - 官方 sha256（digest 去掉前缀）
 * @property {hostfeed$0.AssetNote[] | null} [assets] - Assets 上游全发布物平台/形态矩阵（N13 展示层，下载/校验路径不消费）。
 * @property {hostfeed$0.Form} [form] - Form 本托管资产形态（N13 形态标注，纯展示，ListRemote 回填）：恒 portable——TranslucentTB-portable-x64.zip 解压即用，机械判名与安装链 事实一致（上游另有 msix/appx 包形态资产，托管不收）。
 */

/**
 * TBVersionInfo 本地已安装的 TranslucentTB 版本信息。
 * @typedef {Object} TBVersionInfo
 * @property {string} version - 如 2026.2
 * @property {string} exePath - TranslucentTB.exe 完整路径（供启动/信使使用）
 * @property {string} dir - 版本隔离目录（exe 与 settings.json 同目录）
 * @property {number} size - TranslucentTB.exe 大小（字节）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录（仅导入安装时有值）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
