// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel 取消当前正在进行的扫描
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(1783444182);
}

/**
 * GetSubnets 列出所有可用于扫描的候选网卡子网，支持常见掩码计算
 * @returns {$CancellablePromise<$models.SubnetInfo[]>}
 */
export function GetSubnets() {
    return $Call.ByID(1639537682).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Scan 执行并发网段/IP范围扫描
 * @param {string} targetRange
 * @returns {$CancellablePromise<$models.DeviceInfo[]>}
 */
export function Scan(targetRange) {
    return $Call.ByID(345668133, targetRange).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetRemark 保存 IP 或 MAC 的用户自定义备注
 * @param {string} key
 * @param {string} remark
 * @returns {$CancellablePromise<void>}
 */
export function SetRemark(key, remark) {
    return $Call.ByID(1067643896, key, remark);
}

// Private type creation functions
const $$createType0 = $models.SubnetInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.DeviceInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
