// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DeviceInfo 局域网活跃设备信息
 */
export class DeviceInfo {
    /**
     * Creates a new DeviceInfo instance.
     * @param {Partial<DeviceInfo>} [$$source = {}] - The source object to create the DeviceInfo.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("mac" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mac"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * 用户自定义备注
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }
        if (!("rttMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rttMs"] = 0;
        }
        if (!("isSelf" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isSelf"] = false;
        }
        if (!("isGateway" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isGateway"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceInfo(/** @type {Partial<DeviceInfo>} */($$parsedSource));
    }
}

/**
 * LanProgress 实时扫描进度
 */
export class LanProgress {
    /**
     * Creates a new LanProgress instance.
     * @param {Partial<LanProgress>} [$$source = {}] - The source object to create the LanProgress.
     */
    constructor($$source = {}) {
        if (!("scanned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scanned"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["found"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LanProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LanProgress(/** @type {Partial<LanProgress>} */($$parsedSource));
    }
}

/**
 * SubnetInfo 候选网卡/子网信息
 */
export class SubnetInfo {
    /**
     * Creates a new SubnetInfo instance.
     * @param {Partial<SubnetInfo>} [$$source = {}] - The source object to create the SubnetInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("cidr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cidr"] = "";
        }
        if (!("gateway" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubnetInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SubnetInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubnetInfo(/** @type {Partial<SubnetInfo>} */($$parsedSource));
    }
}
