// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceInfo 局域网活跃设备信息
 * @typedef {Object} DeviceInfo
 * @property {string} ip
 * @property {string} mac
 * @property {string} hostname
 * @property {string} remark - 用户自定义备注
 * @property {number} rttMs
 * @property {boolean} isSelf
 * @property {boolean} isGateway
 */

/**
 * LanProgress 实时扫描进度
 * @typedef {Object} LanProgress
 * @property {number} scanned
 * @property {number} total
 * @property {number} found
 */

/**
 * SubnetInfo 候选网卡/子网信息
 * @typedef {Object} SubnetInfo
 * @property {string} name
 * @property {string} ip
 * @property {string} cidr
 * @property {string} gateway
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
