// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot 引擎状态快照：事件推送与前端渲染共用同一模型。
 * @typedef {Object} Snapshot
 * @property {string} version
 * @property {State} state
 * @property {number} pid
 * @property {number} exitCode
 * @property {string} error
 * @property {boolean} external - state==external 时为 true
 * @property {string} startedAt
 * @property {string} stoppedAt
 */

/**
 * State 引擎状态机：stopped → starting → running → (stopped | failed | external)
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 未运行 / 手动停止 / 外部实例也已退出
     */
    StateStopped: "stopped",

    /**
     * 外层已拉起，等待内层进程树出现（首启含解压）
     */
    StateStarting: "starting",

    /**
     * 自有进程树（提取目录内自有 PID 闭包）存活
     */
    StateRunning: "running",

    /**
     * 启动失败 / 进程树未能出现
     */
    StateFailed: "failed",

    /**
     * 提取目录内有非本引擎托管的便携实例（外部自行启动）
     */
    StateExternal: "external",
};

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
