// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CCSwitchService 向前端暴露 CC Switch 版本管理与窗口唤起能力。
 * 供应商切换本身不内嵌：打开 CC Switch 自有窗口操作（其界面完整，
 * 且切换逻辑直写用户 Claude Code/Codex 配置，由原版实现最稳妥）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "./instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 ccswitch:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(3086832732, targetVersion);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(3639100498);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<instance$0.Snapshot>}
 */
export function GetStatus() {
    return $Call.ByID(3321705606);
}

/**
 * ImportLocal 导入本地已安装的 CC Switch（安装版/绿色版均可）。
 * 配置恒在 ~/.cc-switch 不受导入影响；仅迁移 exe 与便携标记。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 文件被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.CCVersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(804214656, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表。
 * @returns {$CancellablePromise<version$0.CCVersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(2397305487);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.CCRelease[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(3407163426);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义在文件对象上是"执行"
 * 而非"打开"（markeron「打开安装目录」按钮的事故教训：传 exe 路径直接启动了程序）。
 * 这里入参恒为目录，语义安全，但仍走本模块自有实现保持行为显式。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(13363039, dir);
}

/**
 * OpenWindow 窗口唤起编排中枢：
 *   - external：任一已装 exe 充当单实例信使，插件回调 show+focus 外部主窗口；
 *   - running：自有实例直接信使唤窗；
 *   - stopped/failed：解析 active 版本直接无参启动（CC Switch 唯一启动语义即开窗）。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(84425236);
}

/**
 * Quit 退出引擎托管的 CC Switch。
 * external 状态不越权强杀（互斥体探测拿不到 PID）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(263864031);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(2850995892, targetVersion);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(3141032486, targetVersion);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 终止自有实例。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2038129034);
}
