// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebAppEntryView 前端列表行的条目模型（settings.WebAppEntry + 运行时窗态）。
 * 窗态由服务层窗口表推导：WindowOpen=窗口存在且可见，
 * WindowHidden=窗口收起驻留中（隐藏 + TTL 待销毁）。
 * @typedef {Object} WebAppEntryView
 * @property {string} id
 * @property {string} name
 * @property {string} url
 * @property {string} icon
 * @property {string} createdAt
 * @property {string} [defaultOpen]
 * @property {boolean} windowOpen
 * @property {boolean} windowHidden
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
