// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebAppService 暴露给 Wails 前端的服务：条目 CRUD 与开窗/收起编排。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Collapse 收起条目窗口：Hide + 武装空闲 TTL，到期真销毁归还 WebView2 内存。
 * 无窗/已收起时幂等无操作。
 * @param {string} entryID
 * @returns {$CancellablePromise<void>}
 */
export function Collapse(entryID) {
    return $Call.ByID(1514096616, entryID);
}

/**
 * CollapseAll 收起全部可见网页窗（各自进入 TTL 驻留）。
 * @returns {$CancellablePromise<void>}
 */
export function CollapseAll() {
    return $Call.ByID(3428802539);
}

/**
 * DeleteEntry 删除条目（Store 层同步清理托盘/轮盘死引用），存活窗连带真销毁。
 * @param {string} entryID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEntry(entryID) {
    return $Call.ByID(3817443844, entryID);
}

/**
 * ListEntries 返回全部条目（保持配置顺序）及其运行时窗态。
 * @returns {$CancellablePromise<$models.WebAppEntryView[] | null>}
 */
export function ListEntries() {
    return $Call.ByID(2367995865);
}

/**
 * Open 打开（或置顶/恢复）指定条目的网页窗。幂等三态：
 * 可见→仅置顶；收起驻留→取消 TTL 热复用秒显；无窗→按需新建。
 * 登录 cookie 在共享 WebView2 user data folder，真销毁重建也不丢网页会话。
 * @param {string} entryID
 * @returns {$CancellablePromise<void>}
 */
export function Open(entryID) {
    return $Call.ByID(2188958847, entryID);
}

/**
 * OpenExternal 用系统默认浏览器打开条目地址（不进内嵌窗，适合临时跳外链）。
 * @param {string} entryID
 * @returns {$CancellablePromise<void>}
 */
export function OpenExternal(entryID) {
    return $Call.ByID(3641186148, entryID);
}

/**
 * SaveEntry 新增或更新条目：entryID 为空即新建（服务端定 ID），
 * 非空必须命中现有条目（防前端拿着已删 ID 复活幽灵条目）。
 * 名称/URL 闸门不过返回用户可读错误；成功返回定稿条目 ID。
 * @param {string} entryID
 * @param {string} name
 * @param {string} rawURL
 * @param {string} icon
 * @returns {$CancellablePromise<string>}
 */
export function SaveEntry(entryID, name, rawURL, icon) {
    return $Call.ByID(1540803478, entryID, name, rawURL, icon);
}
