// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as detect$0 from "../detect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as remoteversion$0 from "../remoteversion/models.js";

/**
 * Overview 组合本机 Java 探测结果与 Temurin GA 版本通道。
 * @typedef {Object} Overview
 * @property {detect$0.ToolInfo} local
 * @property {remoteversion$0.Channel[] | null} channels
 * @property {boolean} isStale
 * @property {string} fetchedAt
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
