// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    State
} from "./models.js";

import * as $models from "./models.js";

/**
 * Snapshot 引擎状态快照：事件推送（piik:instance-state）与前端渲染共用同一
 * 模型。安全面纪律（联编硬要求，models.go 同款申明）：本类型不得携带口令
 * 明文等任何秘密值——上游 "Local access password: X" 行的明文在解析处即弃，
 * 这里只有 PasswordSet 布尔。
 * @typedef {$models.Snapshot} Snapshot
 */
