// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot 引擎状态快照：事件推送（piik:instance-state）与前端渲染共用同一
 * 模型。安全面纪律（联编硬要求，models.go 同款申明）：本类型不得携带口令
 * 明文等任何秘密值——上游 "Local access password: X" 行的明文在解析处即弃，
 * 这里只有 PasswordSet 布尔。
 * @typedef {Object} Snapshot
 * @property {string} version
 * @property {State} state
 * @property {number} pid
 * @property {number} exitCode
 * @property {string} error
 * @property {boolean} external - state==external 时为 true
 * @property {number} port - 本代/最近一代分配端口（0=从未启动）
 * @property {string} startedAt
 * @property {string} stoppedAt
 * @property {boolean} localAccessOpen - 上游机读字段账（stdout 逐行解析，machine.go）；实例未运行保留最近 一代终值供诊断，新一轮 Start 即清零。 "Local access: open" 命中
 * @property {boolean} passwordSet - 口令行命中且值非空（明文已弃）
 * @property {string} lanInvitation - LAN 邀请来源（原样转呈）
 * @property {string} publicInvitation - 公网邀请来源（原样转呈）
 * @property {boolean} noBrowser - GATE_NO_BROWSER 命中位
 */

/**
 * State 引擎状态机（对前端五态）：stopped → starting → running →
 * (stopped | failed | external)。优雅停收口相（stdin 信令已投、宽限/兜底
 * 终止进行中）在引擎内部以 run.stopping 标记承载，**展示层折并入 running**
 * ——ccswitch/dbx/paseo 家族 mapState 同款口径（终态由收口后的 stopped/
 * failed 广播纠正；B/C 线契约注释已锁"无 quitting 档"）。
 * StateQuitting 为预留词表位：当前实现从不广播该值，联编面若有人引用
 * 仍可编译（永不到来的档——前端删档或本包补档的裁决归联编收口清单）。
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 未运行 / 手动停止 / 外部实例也已退出
     */
    StateStopped: "stopped",

    /**
     * 自有进程创建与 Job 绑定窗口（极短）
     */
    StateStarting: "starting",

    /**
     * 自有 Job 托管实例运行中（含收口窗口折并）
     */
    StateRunning: "running",

    /**
     * 启动失败 / 异常退出
     */
    StateFailed: "failed",

    /**
     * 外部自行启动的 piik 实例（非本引擎托管）
     */
    StateExternal: "external",

    /**
     * 预留：收口相折并入 running，本值当前不广播
     */
    StateQuitting: "quitting",
};

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
