// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * PaseoRelease 远程 GitHub Release 中可用的 Paseo Windows 便携 zip。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验第一依据，
 * 缺 digest 的 release 一律不入列表——与 recordly 同纪律）。
 * @typedef {$models.PaseoRelease} PaseoRelease
 */

/**
 * PaseoVersionInfo 本地已安装的 Paseo 版本信息（一个版本目录一条）。
 * @typedef {$models.PaseoVersionInfo} PaseoVersionInfo
 */
