// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hostfeed$0 from "../../../../packages/go/hostfeed/models.js";

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {Object} DownloadProgress
 * @property {string} version - 目标版本
 * @property {string} stage - downloading/verify/extract/done/error
 * @property {number} done - 已下载字节
 * @property {number} total - 总字节（未知为 0）
 * @property {string} message - 附加信息（如错误描述）
 */

/**
 * PaseoRelease 远程 GitHub Release 中可用的 Paseo Windows 便携 zip。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验第一依据，
 * 缺 digest 的 release 一律不入列表——与 recordly 同纪律）。
 * @typedef {Object} PaseoRelease
 * @property {string} version - 如 0.8.0 / 0.8.0-beta.1（tag 去掉 v 前缀，与版本目录名同形）
 * @property {string} tag - GitHub tag 原文（v0.8.0，下载 URL 路径用）
 * @property {string} published - 发布时间（RFC3339）
 * @property {boolean} isPre - 是否为预发布版本（beta 通道条目）
 * @property {string} assetName - 如 Paseo-Setup-0.8.0-x64.zip
 * @property {string} assetUrl - 资产下载地址（302 到 CDN）
 * @property {number} size - 资产大小（字节）
 * @property {string} sha256 - 官方 sha256（digest 去掉前缀）
 * @property {hostfeed$0.AssetNote[] | null} [assets] - Assets 上游全发布物平台/形态矩阵（N13 展示层，下载/校验路径不消费）。
 * @property {hostfeed$0.Form} [form] - Form 本托管资产形态（N13 形态标注，纯展示，ListRemote 回填）：恒 portable——findZipAsset 判据收 electron-builder win zip target 产物， 解压即运行、无注册表卸载语义。诚实边界：资产名 "Setup" 只是上游 artifactName 模板字样，机械判名 Classify 据此误标 installer，形态以 安装链代码取证（解包直启、与并列 NSIS .exe 两条腿）为准。
 */

/**
 * PaseoVersionInfo 本地已安装的 Paseo 版本信息（一个版本目录一条）。
 * @typedef {Object} PaseoVersionInfo
 * @property {string} version - 如 0.8.0 / 0.8.0-beta.1（版本目录名所载，无 v 前缀）
 * @property {string} exePath - Paseo.exe 完整路径（供启动/唤窗使用）
 * @property {string} dir - 版本隔离目录（解压落点）
 * @property {number} size - Paseo.exe 大小（字节）
 * @property {string} installedAt - 安装时间 yyyy-MM-dd HH:mm:ss
 * @property {boolean} isImport - 是否经「导入本地」安装（非远程下载）
 * @property {string} source - 导入来源目录 / 下载资产名
 * @property {boolean} verifiedHash - 是否经官方 sha256 验证（导入安装为 false）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
