// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * DownloadProgress 下载过程实时进度
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * FrpRelease 远程 GitHub Release 中可用的 frp Windows amd64 版本
 * @typedef {$models.FrpRelease} FrpRelease
 */

/**
 * FrpVersionInfo 本地已安装的 frp 版本信息
 * @typedef {$models.FrpVersionInfo} FrpVersionInfo
 */
