// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as EverythingService from "./everythingservice.js";
export {
    EverythingService
};

import * as $models from "./models.js";

/**
 * ControlOutcome 控制操作（启动后台 / 打开窗口）执行结果说明。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * DownloadTicket 本模块统一下载进度事件载荷（"everything:download"）。
 * Component 区分两类资产：app = Everything 主程序版本包；es = ES 搜索组件。
 * @typedef {$models.DownloadTicket} DownloadTicket
 */

/**
 * QuitOutcome 退出执行结果。
 * @typedef {$models.QuitOutcome} QuitOutcome
 */
