// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 向前端暴露 Bili23 Downloader 版本管理与托管启停能力。
 * 下载操作本身不内嵌：打开 Bili23 自有窗口完成（其 GUI 已高度完整，纯托管决策
 * 详见包注释）。本服务只做三件事：装对版本、起停受控、状态如实。
 * 
 * 与 ccswitch service 的显著差异：**没有空闲自动退出**——下载器无法从外部感知
 * 任务活跃度（无 CLI 状态通道），静默退出打断在途下载的代价远大于省内存的收益。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "./version/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateDesktopShortcut 在桌面为当前使用版本创建快捷方式（同名覆盖）。
 * @returns {$CancellablePromise<void>}
 */
export function CreateDesktopShortcut() {
    return $Call.ByID(3489672072);
}

/**
 * DownloadVersion 后台下载指定版本：立即返回，全程经事件 bili23:version-download 推送进度。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function DownloadVersion(targetVersion) {
    return $Call.ByID(2380629678, targetVersion);
}

/**
 * ForceStop 立即强杀自有实例（「强制结束」按钮）：跳过优雅收尾，在途下载中断——
 * 上游断点续传 + SQLite WAL 保证下次启动可恢复。external 实例不受管辖。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function ForceStop() {
    return $Call.ByID(967219241);
}

/**
 * GetActiveVersion 返回当前设定版本（空字符串 = 未指定，冷启动自动用最新已装）。
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveVersion() {
    return $Call.ByID(337902628);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关值（默认 true）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(2081700590);
}

/**
 * GetStatus 返回引擎当前状态快照（先做一次静止态外部校正，弥补 5s 轮询间隙的即时性）。
 * @returns {$CancellablePromise<$models.Status>}
 */
export function GetStatus() {
    return $Call.ByID(1507123648);
}

/**
 * ImportLocal 导入本地已有的 Bili23 Downloader（Inno 安装版目录 / 手动解压的便携目录均可）。
 * 整目录复制（~108MB）；用户配置恒在 %APPDATA%\Bili23 Downloader\ 不受导入影响。
 * 运行中的实例拒绝导入：Windows 下运行中的 exe 文件被独占，拷贝必然失败。
 * @param {string} srcDir
 * @returns {$CancellablePromise<version$0.Bili23VersionInfo>}
 */
export function ImportLocal(srcDir) {
    return $Call.ByID(2409526798, srcDir);
}

/**
 * ListInstalledVersions 获取本地已安装版本列表。
 * @returns {$CancellablePromise<version$0.Bili23VersionInfo[] | null>}
 */
export function ListInstalledVersions() {
    return $Call.ByID(3197954073);
}

/**
 * ListReleases 获取远程可用版本列表（多镜像回退，10 分钟缓存）。
 * @returns {$CancellablePromise<version$0.Bili23Release[] | null>}
 */
export function ListReleases() {
    return $Call.ByID(4169941804);
}

/**
 * OpenConfigDir 打开 Bili23 的用户数据目录（%APPDATA%\Bili23 Downloader，
 * 配置/任务库/日志所在）——纯托管下用户想看"数据在哪"的直达入口。只读导航，不改写。
 * @returns {$CancellablePromise<void>}
 */
export function OpenConfigDir() {
    return $Call.ByID(120387499);
}

/**
 * OpenDir 在资源管理器中打开版本隔离目录（"打开位置"按钮）。
 * 刻意不复用 AppService.OpenPath：其 explorer.exe <file> 语义在文件对象上是"执行"
 * 而非"打开"（markeron「打开安装目录」按钮的事故教训）。这里入参恒为目录，语义安全。
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function OpenDir(dir) {
    return $Call.ByID(4109295169, dir);
}

/**
 * OpenRepository 用默认浏览器打开上游仓库页面。
 * @returns {$CancellablePromise<void>}
 */
export function OpenRepository() {
    return $Call.ByID(4179700058);
}

/**
 * OpenWindow 窗口唤起编排中枢：
 *   - external：任一已装 exe 充当单实例信使，上游 QLocalServer 回调激活外部主窗口；
 *   - running：自有实例直接信使唤窗（窗口收入托盘后同样经此唤回）；
 *   - stopped/failed：解析 active 版本直接无参启动（Bili23 唯一启动语义即开窗）。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function OpenWindow() {
    return $Call.ByID(2694220310);
}

/**
 * Quit 尽力优雅退出引擎托管的 Bili23。结果如实分叉（引擎不代做决定、不强杀）：
 *   - exited：进程已终结（"关闭窗口=退出"设置，或用户在询问对话框中选择了退出）；
 *   - hidden：进程收入 Bili23 自身托盘（"关闭窗口=最小化"设置），仍受 Job 托管，
 *     可唤窗，也可用「强制结束」终结；
 *   - asked：Bili23 弹出询问对话框等待用户选择（默认设置），请到其窗口内完成决定。
 * 
 * external 状态不越权强杀（互斥体探测拿不到 PID）：仅返回人性化指引。
 * @returns {$CancellablePromise<$models.QuitOutcome>}
 */
export function Quit() {
    return $Call.ByID(339604313);
}

/**
 * RemoveVersion 卸载指定版本（正在运行的版本拒绝卸载）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<void>}
 */
export function RemoveVersion(targetVersion) {
    return $Call.ByID(3065860122, targetVersion);
}

/**
 * RepositoryURL 上游 GitHub 仓库地址（页面展示与复制）。
 * @returns {$CancellablePromise<string>}
 */
export function RepositoryURL() {
    return $Call.ByID(1820696699);
}

/**
 * SetActiveVersion 设定使用版本（先校验已安装，再持久化）。
 * @param {string} targetVersion
 * @returns {$CancellablePromise<string>}
 */
export function SetActiveVersion(targetVersion) {
    return $Call.ByID(2535434680, targetVersion);
}

/**
 * SetFollowOnExit 设定开关（下次启动生效）。
 * @param {boolean} b
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(b) {
    return $Call.ByID(3457881954, b);
}

/**
 * Shutdown 模块停用/应用退出：停后台轮询 + 终止自有实例。
 * 外部实例不受影响（非我方托管）；自有实例另受 JobObject KILL_ON_JOB_CLOSE 内核兜底。
 * 刻意走 Stop（强杀）而非 Quit（优雅）：应用退出通道不能阻塞等待上游下载线程收敛，
 * 且用户若不希望退出被中断，可关闭"随 Hanxi 退出"开关（解除 Job 联动）。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2396497700);
}
