// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Overview 组合本机 Python 探测结果与 Python.org 正式版本通道。
 * @typedef {$models.Overview} Overview
 */
