// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Adapter 网卡信息
 */
export class Adapter {
    /**
     * Creates a new Adapter instance.
     * @param {Partial<Adapter>} [$$source = {}] - The source object to create the Adapter.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("mac" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mac"] = "";
        }
        if (!("ipv4" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ipv4"] = [];
        }
        if (!("ipv6" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ipv6"] = [];
        }
        if (!("ipv6Details" in $$source)) {
            /**
             * @member
             * @type {IPv6Detail[]}
             */
            this["ipv6Details"] = [];
        }
        if (!("gateway" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway"] = "";
        }
        if (!("ipv6Gateway" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ipv6Gateway"] = "";
        }
        if (!("dnsServers" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dnsServers"] = [];
        }
        if (!("isPhysical" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPhysical"] = false;
        }
        if (!("isLoopback" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLoopback"] = false;
        }
        if (!("isUp" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isUp"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Adapter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Adapter}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ipv4" in $$parsedSource) {
            $$parsedSource["ipv4"] = $$createField4_0($$parsedSource["ipv4"]);
        }
        if ("ipv6" in $$parsedSource) {
            $$parsedSource["ipv6"] = $$createField5_0($$parsedSource["ipv6"]);
        }
        if ("ipv6Details" in $$parsedSource) {
            $$parsedSource["ipv6Details"] = $$createField6_0($$parsedSource["ipv6Details"]);
        }
        if ("dnsServers" in $$parsedSource) {
            $$parsedSource["dnsServers"] = $$createField9_0($$parsedSource["dnsServers"]);
        }
        return new Adapter(/** @type {Partial<Adapter>} */($$parsedSource));
    }
}

/**
 * IPv6Detail 详细 IPv6 地址（公网、临时、链路本地）
 */
export class IPv6Detail {
    /**
     * Creates a new IPv6Detail instance.
     * @param {Partial<IPv6Detail>} [$$source = {}] - The source object to create the IPv6Detail.
     */
    constructor($$source = {}) {
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "Public" (公网/主地址) | "Temporary" (临时隐私地址) | "LinkLocal" (链路本地)
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("isTemporary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isTemporary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPv6Detail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IPv6Detail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPv6Detail(/** @type {Partial<IPv6Detail>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = IPv6Detail.createFrom;
const $$createType2 = $Create.Array($$createType1);
