// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as OcrService from "./ocrservice.js";
export {
    OcrService
};

import * as $models from "./models.js";

/**
 * ControlOutcome 启停操作结果（仿 KillResult/QuitOutcome 口径）。
 * @typedef {$models.ControlOutcome} ControlOutcome
 */

/**
 * DropResult 原生文件拖放/组件导入的统一回执（事件 ocr:file-drop-result 与各
 * 导入方法共用）。按 Kind 分流：import 结果刷状态，image 结果直接设为待识别图。
 * @typedef {$models.DropResult} DropResult
 */

/**
 * ImageRef 统一"已选图"模型：对话框/拖拽/粘贴三通道汇流。
 * @typedef {$models.ImageRef} ImageRef
 */

/**
 * OcrLine 单行识别结果与左上角坐标（4.0 引擎不提供宽高/置信度）。
 * @typedef {$models.OcrLine} OcrLine
 */

/**
 * OcrOutcome 识别操作结果（业务失败折进 Error 中文，error 通道留给程序性错误）。
 * @typedef {$models.OcrOutcome} OcrOutcome
 */

/**
 * ServiceState 前端唯一状态视图模型：引擎快照 + /api/status 探测缓存合并。
 * 事件 ocr:service-state 与 GetStatus 共用同一结构。
 * @typedef {$models.ServiceState} ServiceState
 */
