// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ControlOutcome 启停操作结果（仿 KillResult/QuitOutcome 口径）。
 * @typedef {Object} ControlOutcome
 * @property {string} action - started / already-running / starting / external / stopped / already-stopped / external-unmanaged
 * @property {boolean} external
 * @property {string} message
 */

/**
 * DropResult 原生文件拖放/组件导入的统一回执（事件 ocr:file-drop-result 与各
 * 导入方法共用）。按 Kind 分流：import 结果刷状态，image 结果直接设为待识别图。
 * @typedef {Object} DropResult
 * @property {string} kind - import / image
 * @property {boolean} ok
 * @property {string} exePath - 导入成功后的托管副本路径
 * @property {ImageRef | null} image - 图片通道成功时的选图结果
 * @property {string} message - 中文人话（成功说明或失败原因）
 */

/**
 * EngineInfo 引擎注册表单件（GetEngines 列表元素，前端"引擎列表"两行卡按此渲染）。
 * Installed 语义：登记件或默认锚点可解析出可用 exe；未安装时 Path 为空、
 * Error 给中文原因（未找到指引 / 登记路径失效）。
 * @typedef {Object} EngineInfo
 * @property {string} id - wechat / paddle
 * @property {string} label - 中文显示名（微信引擎 / PP-OCR 开源引擎）
 * @property {boolean} installed - 组件可解析（登记或自动发现）
 * @property {boolean} active - 当前活跃引擎（单活语义，至多一行为真）
 * @property {string} version - 登记版本；活跃引擎在线时为 /api/status 实测版本
 * @property {string} path - 解析出的 exe 路径（未安装为空）
 * @property {boolean} auto - 路径来自自动发现（false = 用户设定/导入登记）
 * @property {string} error - 不可解析的中文原因（Installed 为真相空）
 */

/**
 * ImageRef 统一"已选图"模型：对话框/拖拽/粘贴三通道汇流。
 * @typedef {Object} ImageRef
 * @property {string} path
 * @property {string} name
 * @property {number} size
 * @property {string} previewUrl - dataURL；超限为空
 * @property {boolean} temporary - 临时件（RuntimeDir/ocr），生命周期归本模块
 */

/**
 * OcrLine 单行识别结果与左上角坐标（4.0 引擎不提供宽高/置信度）。
 * @typedef {Object} OcrLine
 * @property {string} text
 * @property {number} x
 * @property {number} y
 */

/**
 * OcrOutcome 识别操作结果（业务失败折进 Error 中文，error 通道留给程序性错误）。
 * @typedef {Object} OcrOutcome
 * @property {boolean} ok
 * @property {string} text
 * @property {OcrLine[] | null} lines
 * @property {number} elapsedMs
 * @property {string} error
 */

/**
 * ServiceState 前端唯一状态视图模型：引擎快照 + /api/status 探测缓存合并。
 * 事件 ocr:service-state 与 GetStatus 共用同一结构。
 * @typedef {Object} ServiceState
 * @property {string} state - stopped / starting / running / external / failed
 * @property {boolean} online - 最近一次契约探测成功
 * @property {boolean} managed - 我方 JobObject 托管实例（running）
 * @property {boolean} external - 外部实例（只转发不管理）
 * @property {number} pid
 * @property {string} listenAddr - 127.0.0.1:<port>
 * @property {string} exePath - 生效的服务程序路径（发现结果或设定值）
 * @property {boolean} exeAuto - 生效路径是否来自自动发现（false=用户显式指定）
 * @property {string} version - 上游 status.version
 * @property {string} engine - 上游 status.engine（如 wxocr@8094 / pp-ocrv6-small）
 * @property {string} engineMode - 上游 status.engine_mode（组件如实上报，本侧不解释语义）
 * @property {string} engineID - store 登记的活跃引擎（wechat / paddle，未在线时也可判定）
 * @property {string} engineError - 上游 status.error（引擎已就位但带病的中文原因，空=健康）
 * @property {boolean} engineRunning
 * @property {boolean} hung - 上游报告引擎 Call 挂死
 * @property {string} error - 中文人话错误（failed 时非空）
 * @property {string} checkedAt - 最近探测时刻（格式化，状态新鲜度）
 */

/**
 * SnipHotkeyBinding 宿主注入的热键落实通道。Apply 把"键位 + 开关"期望态落到系统
 * 全局热键（失败返回中文错误，配置端须自行回滚）；Registered 如实回报槽位是否
 * 真实绑定在系统上（启动期抢键失败 → false，设置页据此给"已被占用"提示）。
 * @typedef {any} SnipHotkeyBinding
 */

/**
 * SnipHotkeyState 热键配置的对外视图（设置页一次拉全）。
 * @typedef {Object} SnipHotkeyState
 * @property {boolean} enabled
 * @property {string} accel - 规范化键位（如 Ctrl+Alt+T）
 * @property {boolean} registered - 系统侧真实绑定状态（禁用中恒 false）
 */

/**
 * SnipResult 框选截屏识别结果（悬浮卡事件 ocr:snip-result 与 SnipAndRecognize
 * 返回值共用）。Cancelled=true 表示用户放弃选区（静默路径，前端不打扰）。
 * @typedef {Object} SnipResult
 * @property {boolean} ok
 * @property {string} text
 * @property {number} lineCount
 * @property {number} elapsedMs
 * @property {string} error
 * @property {boolean} copied - 已按开关自动复制进剪贴板
 * @property {boolean} cancelled - 选区超时取消
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
