// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ControlOutcome 启停操作结果（仿 KillResult/QuitOutcome 口径）。
 * @typedef {Object} ControlOutcome
 * @property {string} action - started / already-running / starting / external / stopped / already-stopped / external-unmanaged
 * @property {boolean} external
 * @property {string} message
 */

/**
 * DropResult 原生文件拖放/组件导入的统一回执（事件 ocr:file-drop-result 与各
 * 导入方法共用）。按 Kind 分流：import 结果刷状态，image 结果直接设为待识别图。
 * @typedef {Object} DropResult
 * @property {string} kind - import / image
 * @property {boolean} ok
 * @property {string} exePath - 导入成功后的托管副本路径
 * @property {ImageRef | null} image - 图片通道成功时的选图结果
 * @property {string} message - 中文人话（成功说明或失败原因）
 */

/**
 * ImageRef 统一"已选图"模型：对话框/拖拽/粘贴三通道汇流。
 * @typedef {Object} ImageRef
 * @property {string} path
 * @property {string} name
 * @property {number} size
 * @property {string} previewUrl - dataURL；超限为空
 * @property {boolean} temporary - 临时件（RuntimeDir/ocr），生命周期归本模块
 */

/**
 * OcrLine 单行识别结果与左上角坐标（4.0 引擎不提供宽高/置信度）。
 * @typedef {Object} OcrLine
 * @property {string} text
 * @property {number} x
 * @property {number} y
 */

/**
 * OcrOutcome 识别操作结果（业务失败折进 Error 中文，error 通道留给程序性错误）。
 * @typedef {Object} OcrOutcome
 * @property {boolean} ok
 * @property {string} text
 * @property {OcrLine[] | null} lines
 * @property {number} elapsedMs
 * @property {string} error
 */

/**
 * ServiceState 前端唯一状态视图模型：引擎快照 + /api/status 探测缓存合并。
 * 事件 ocr:service-state 与 GetStatus 共用同一结构。
 * @typedef {Object} ServiceState
 * @property {string} state - stopped / starting / running / external / failed
 * @property {boolean} online - 最近一次契约探测成功
 * @property {boolean} managed - 我方 JobObject 托管实例（running）
 * @property {boolean} external - 外部实例（只转发不管理）
 * @property {number} pid
 * @property {string} listenAddr - 127.0.0.1:<port>
 * @property {string} exePath - 生效的服务程序路径（发现结果或设定值）
 * @property {boolean} exeAuto - 生效路径是否来自自动发现（false=用户显式指定）
 * @property {string} version - 上游 status.version
 * @property {string} engine - 上游 status.engine（如 wxocr@8094 / wcdir@4.1.13.65）
 * @property {boolean} engineRunning
 * @property {boolean} hung - 上游报告引擎 Call 挂死
 * @property {string} error - 中文人话错误（failed 时非空）
 * @property {string} checkedAt - 最近探测时刻（格式化，状态新鲜度）
 */

/**
 * SnipResult 框选截屏识别结果（悬浮卡事件 ocr:snip-result 与 SnipAndRecognize
 * 返回值共用）。Cancelled=true 表示用户放弃选区（静默路径，前端不打扰）。
 * @typedef {Object} SnipResult
 * @property {boolean} ok
 * @property {string} text
 * @property {number} lineCount
 * @property {number} elapsedMs
 * @property {string} error
 * @property {boolean} copied - 已按开关自动复制进剪贴板
 * @property {boolean} cancelled - 选区超时取消
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
