// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OcrService 向前端暴露 hanxi-ocr 本地服务的托管启停、状态探测与图片识别转发。
 * 定位边界：识别能力全部在上游服务内，本服务只做"探活 + 转发 + 生命周期"，
 * 不重复实现上游功能面（与 ddnsgo 托管口径一致）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "../../history/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BrowseServiceExeDialog 打开系统对话框挑选 hanxi-ocr.exe。
 * @returns {$CancellablePromise<string>}
 */
export function BrowseServiceExeDialog() {
    return $Call.ByID(1090173230);
}

/**
 * CardDragEnd 拖拽把手 mouseup 调用：结束跟手移动会话（幂等）。
 * @returns {$CancellablePromise<void>}
 */
export function CardDragEnd() {
    return $Call.ByID(3519330210);
}

/**
 * CardDragStart 拖拽把手 mousedown 调用：进入跟手移动会话（重入忽略）。
 * Wails beta.10 没有拖拽区 API（v2 SetDragRegion 已移除），原生轮询实现见
 * card_windows.go；结束走 CardDragEnd 与左键态检测双通道。
 * @returns {$CancellablePromise<void>}
 */
export function CardDragStart() {
    return $Call.ByID(541182791);
}

/**
 * GetAutoCopy 返回「截屏识别后自动复制文字」开关（默认 true）。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoCopy() {
    return $Call.ByID(4022883145);
}

/**
 * GetEngines 返回引擎注册表全量视图（含未安装引擎——前端据此渲染"导入"入口）。
 * Installed 判定即时解析（登记件在位或自动发现锚点命中）；活跃引擎在线时
 * Version 以 /api/status 实测值优先（探测顺带回写注册表，见 probeStatus）。
 * @returns {$CancellablePromise<$models.EngineInfo[] | null>}
 */
export function GetEngines() {
    return $Call.ByID(3658015710);
}

/**
 * GetFollowOnExit 返回"随 Hanxi 退出一起关闭"开关。
 * @returns {$CancellablePromise<boolean>}
 */
export function GetFollowOnExit() {
    return $Call.ByID(1969177523);
}

/**
 * GetListenPort 服务端口（默认 53120）。
 * @returns {$CancellablePromise<number>}
 */
export function GetListenPort() {
    return $Call.ByID(3413072619);
}

/**
 * GetServiceExePath 返回当前生效的服务程序路径（活跃引擎的自动发现结果或登记件）。
 * @returns {$CancellablePromise<string>}
 */
export function GetServiceExePath() {
    return $Call.ByID(3624823525);
}

/**
 * GetSnipResult 卡片挂载/刷新时拉取当前结果（事件双保险，常驻窗体不漏帧）。
 * found 仅在存在成功结果时为真——取消帧不进卡片通道（showSnipCard 只在成功时调用）。
 * @returns {$CancellablePromise<[$models.SnipResult, boolean]>}
 */
export function GetSnipResult() {
    return $Call.ByID(2567895550);
}

/**
 * GetStatus 返回合并状态（先做一次同步探测，弥补轮询间隙与首帧）。
 * @returns {$CancellablePromise<$models.ServiceState>}
 */
export function GetStatus() {
    return $Call.ByID(572896145);
}

/**
 * HandleNativeDrop Wails 主窗原生文件拖放入口（app.go 接线；只有落在 OcrView
 * 标记 data-file-drop-target 元素上的文件才会到达）。分流：目录 → PP-OCR 引擎包
 * 导入；.exe → 微信件导入；图片 → 真实路径直接选为待识别对象（免走 dataURL 全量
 * IPC）；其余给中文提示。
 * @param {string[] | null} files
 * @returns {$CancellablePromise<void>}
 */
export function HandleNativeDrop(files) {
    return $Call.ByID(2331129421, files);
}

/**
 * ImportPaddleDir 导入 PP-OCR 开源引擎目录（引用式登记，不复制）：
 * 目录须同时含 hanxi-ocr.exe（契约文件名与微信版同名，计划 §3）与 manifest.json
 * （组件自检清单，读其 version 字段登记版本）。登记成功后切 active=paddle——
 * 在跑的托管实例会停旧起新，外部实例占位时只登记不切换（不越权）。
 * 回执与事件复用 ocr:file-drop-result（Kind=import）。
 * @param {string} srcDir
 * @returns {$CancellablePromise<$models.DropResult>}
 */
export function ImportPaddleDir(srcDir) {
    return $Call.ByID(3836450419, srcDir);
}

/**
 * ImportPaddleDirDialog 目录选择框式导入 PP-OCR 引擎包（系统文件夹框为原生
 * 能力，拖放之外的通道；取消返回空回执）。选定后走 ImportPaddleDir 同一套校验。
 * @returns {$CancellablePromise<$models.DropResult>}
 */
export function ImportPaddleDirDialog() {
    return $Call.ByID(2723718847);
}

/**
 * ImportServiceExe 导入用户提供的组件，按文件/目录分流（计划 §5.3）：
 *   - 文件 → 微信版校验（文件名/体积/布局不变），登记为微信引擎；
 *   - 目录 → PP-OCR 开源引擎包（含 manifest.json 自检），转 ImportPaddleDir。
 * 
 * 校验失败不置 error（属业务结果），统一折进 DropResult.Message 并广播
 * ocr:file-drop-result 事件；取消对话框等无操作场景不发事件。
 * @param {string} srcPath
 * @returns {$CancellablePromise<$models.DropResult>}
 */
export function ImportServiceExe(srcPath) {
    return $Call.ByID(3123454301, srcPath);
}

/**
 * ImportServiceExeDialog 对话框式导入（与拖放共用同一套校验）。取消返回空回执。
 * @returns {$CancellablePromise<$models.DropResult>}
 */
export function ImportServiceExeDialog() {
    return $Call.ByID(3234376289);
}

/**
 * InspectImage 校验对话框所选图片并生成预览（不落盘、temporary=false）。
 * @param {string} path
 * @returns {$CancellablePromise<$models.ImageRef>}
 */
export function InspectImage(path) {
    return $Call.ByID(691847548, path);
}

/**
 * Logs 返回最近 n 行托管实例输出（排障）。
 * @param {number} n
 * @returns {$CancellablePromise<string[] | null>}
 */
export function Logs(n) {
    return $Call.ByID(1864815254, n);
}

/**
 * PickImageDialog 打开系统图片选择对话框；取消返回空串。
 * @returns {$CancellablePromise<string>}
 */
export function PickImageDialog() {
    return $Call.ByID(1521780297);
}

/**
 * RecognizeImage 转发图片路径给上游识别。一切业务失败折进 Outcome.Error
 * （中文人话），error 通道留给程序性错误。
 * 统一历史：识别动作的唯一记录点在 recognizeImage 的 defer 单点（成功与失败同记），
 * 截屏链路经 snip 来源标记复用同一记录点，勿二处插。
 * @param {string} path
 * @returns {$CancellablePromise<$models.OcrOutcome>}
 */
export function RecognizeImage(path) {
    return $Call.ByID(2440042768, path);
}

/**
 * SavePastedImage 拖拽/粘贴通道：File→dataURL 解码落盘 RuntimeDir()/ocr，
 * 返回统一 ImageRef（temporary=true）。替换删除上一张粘贴临时件，目录不膨胀。
 * @param {string} fileName
 * @param {string} dataURL
 * @returns {$CancellablePromise<$models.ImageRef>}
 */
export function SavePastedImage(fileName, dataURL) {
    return $Call.ByID(2793413642, fileName, dataURL);
}

/**
 * SetActiveEngine 切换活跃引擎并落盘（id：wechat / paddle）。
 *   - 未知 ID / 目标未安装（登记件失效或锚点无组件）→ error 通道给中文指引；
 *   - 当前托管实例在跑 → 先按 StopService 语义优雅停、再按 StartService 语义起新件
 *     （Detached 联动仍随 followOnExit 开关）；active 在停旧后即持久化，起新件失败
 *     不回滚（注册表如实反映用户意图，失败原因折进 Message，引擎侧已广播 + notify）；
 *   - 外部实例在服务（external）→ 不越权：只提示先手动停止，不做任何切换；
 *   - 服务原本未运行 → 仅切换登记，不擅自拉起。
 * 
 * 幂等：切到当前活跃引擎直接返回 already-active。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function SetActiveEngine(id) {
    return $Call.ByID(1632066051, id);
}

/**
 * SetAutoCopy 设定自动复制开关（下一次截屏识别起生效）。
 * @param {boolean} v
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoCopy(v) {
    return $Call.ByID(885513349, v);
}

/**
 * SetFollowOnExit 设定开关（已运行实例的联动在下一次启动时生效）。
 * @param {boolean} v
 * @returns {$CancellablePromise<void>}
 */
export function SetFollowOnExit(v) {
    return $Call.ByID(126128511, v);
}

/**
 * SetHistory 注入统一历史存储与"全文入库"档位读取器（装配根接线，
 * 照 memo↔fileshare SetMemoHook 先例）。fullText 为 config.json 开关的实时读取
 * 闭包（Q1：默认开=全文入库；关=只记图片路径与摘要）；nil 视为开。
 * @param {history$0.Store | null} h
 * @param {any} fullText
 * @returns {$CancellablePromise<void>}
 */
export function SetHistory(h, fullText) {
    return $Call.ByID(492254989, h, fullText);
}

/**
 * SetListenPort 设定端口并落盘；托管实例运行中返回 pending（下次启动生效）。
 * @param {number} port
 * @returns {$CancellablePromise<string>}
 */
export function SetListenPort(port) {
    return $Call.ByID(3709178999, port);
}

/**
 * SetServiceExePath 设定活跃引擎的登记路径；""=恢复自动发现。返回当前生效值。
 * （双引擎口径：本方法作用于 active 引擎注册件；另一引擎的登记走导入分流。）
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function SetServiceExePath(path) {
    return $Call.ByID(1316221937, path);
}

/**
 * Shutdown 模块销毁：停 watch；随退联动开启时强杀托管实例（限时通道，
 * 不走上游优雅退出——OnDestroy 必须快速返回，照 ddnsgo 决策）。
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2824723323);
}

/**
 * SnipAndRecognize 唤起系统截屏覆盖层（ms-screenclip:），接住框选图像识别，
 * 成功后弹悬浮卡并按开关自动复制文字。业务失败以中文 error 返回
 * （命令派发链路与前端按钮的提示系统会接住）；用户放弃选区静默返回 Cancelled。
 * @returns {$CancellablePromise<$models.SnipResult>}
 */
export function SnipAndRecognize() {
    return $Call.ByID(791784394);
}

/**
 * SnipCardDismiss 收起悬浮卡（前端关闭钮/Esc 调用；只隐藏不销毁）。
 * @returns {$CancellablePromise<void>}
 */
export function SnipCardDismiss() {
    return $Call.ByID(2862850157);
}

/**
 * SnipCopyText 手动复制卡片全文（Go 代理写剪贴板，绕开 webview 安全上下文
 * 限制），成功后收起卡片。
 * @returns {$CancellablePromise<void>}
 */
export function SnipCopyText() {
    return $Call.ByID(590756931);
}

/**
 * StartService 冷启动托管实例（external 占位转为幂等说明而非报错）。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function StartService() {
    return $Call.ByID(1276383666);
}

/**
 * StopService 停止托管实例：优先上游优雅退出（POST /api/shutdown），兜底强杀；
 * external 不越权（进程归属不在本引擎）。
 * @returns {$CancellablePromise<$models.ControlOutcome>}
 */
export function StopService() {
    return $Call.ByID(2170035572);
}
