// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WslService from "./wslservice.js";
export {
    WslService
};

import * as $models from "./models.js";

/**
 * DistroInstance 管理控制台的发行版实例行。
 * Running/Default 为归一后的布尔语义（状态列原文是本地化文案，跨语言系统下
 * 不可作为判据；运行态以 `wsl -l -q --running` 名单为准，默认以 `wsl -l -q`
 * 首行为准，均带回退）。
 * @typedef {$models.DistroInstance} DistroInstance
 */

/**
 * DistroOpResult 发行版操作统一回执；导出成功后 ID/Path 供「打开位置」白名单回查。
 * @typedef {$models.DistroOpResult} DistroOpResult
 */

/**
 * DownloadProgress MSI 下载进度事件载荷（与托管模块 version-download 事件同构）。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */

/**
 * OperationOutcome 提权操作统一回执（UAC 取消不算错误，以文案区分）。
 * @typedef {$models.OperationOutcome} OperationOutcome
 */

/**
 * ReadinessUpdate 流式体检推送载荷（事件 wsl:readiness）：
 * 前端先渲染全量 pending 骨架，各阶段到达后按 key 落位点亮，done 携带终版报告。
 * 阶段划分与数据源一一对应，互不等待：system=探针、wsl=本机运行时、net=Go 网络探测。
 * @typedef {$models.ReadinessUpdate} ReadinessUpdate
 */
