// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as readiness$0 from "./readiness/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usbipd$0 from "./usbipd/models.js";

/**
 * ActiveProxy netsh 现态的一条转发。
 * @typedef {Object} ActiveProxy
 * @property {string} listenAddr
 * @property {number} listenPort
 * @property {string} connectAddr
 * @property {number} connectPort
 */

/**
 * CloneProgress 克隆进度事件载荷。
 * @typedef {Object} CloneProgress
 * @property {string} source
 * @property {string} target
 * @property {string} stage - copying | importing | done | error
 * @property {number} done
 * @property {number} total
 * @property {string} [error]
 * @property {string} [message] - done 时的完整回执文案
 */

/**
 * CompactProgress 压缩进度事件载荷。Stage 时序：backup → trim → optimize → reimport → done|error。
 * @typedef {Object} CompactProgress
 * @property {string} name
 * @property {string} stage
 * @property {string} [message] - 阶段说明/终版回执
 * @property {string} [error]
 * @property {string} [tier] - tier1 | tier2（实际达成路径，如实上报）
 * @property {number} beforeMB
 * @property {number} afterMB
 */

/**
 * DistroForensics 单发行版取证详情载荷。
 * 取不到的项一律留空并汇入 Notes 如实说明，不以零值冒充测定结果。
 * @typedef {Object} DistroForensics
 * @property {string} name
 * @property {string} pfn - PackageFamilyName（商店发行版才有）
 * @property {string} basePath
 * @property {string} vhdxPath
 * @property {number} logicalBytes - VHDX 逻辑大小
 * @property {number} allocBytes - 磁盘实占（稀疏盘显著小于逻辑值）
 * @property {boolean} sparse
 * @property {boolean} running
 * @property {boolean} runtimeKnown - -q --running 通道是否可用
 * @property {number} dfTotalMB
 * @property {number} dfUsedMB
 * @property {number} dfAvailMB
 * @property {number} dfUsePct
 * @property {boolean} dfOk - guest df 是否取到
 * @property {string} ipv4
 * @property {string} networkMode - 宿主 .wslconfig 网络模式（nat/bridged/mirrored/unknown）
 * @property {string[] | null} notes
 */

/**
 * DistroInstance 管理控制台的发行版实例行。
 * Running/Default 为归一后的布尔语义（状态列原文是本地化文案，跨语言系统下
 * 不可作为判据；运行态以 `wsl -l -q --running` 名单为准，默认以 `wsl -l -q`
 * 首行为准，均带回退）。
 * @typedef {Object} DistroInstance
 * @property {string} name
 * @property {boolean} running
 * @property {boolean} default
 * @property {string} version - "1" | "2"（表尾列，非本地化）
 * @property {string} stateText
 * @property {string} basePath
 * @property {string} vhdxPath
 * @property {number} sizeBytes
 */

/**
 * DistroOpResult 发行版操作统一回执；导出成功后 ID/Path 供「打开位置」白名单回查。
 * @typedef {Object} DistroOpResult
 * @property {boolean} success
 * @property {string} message
 * @property {string} [id]
 * @property {string} [path]
 */

/**
 * DownloadProgress MSI 下载进度事件载荷（与托管模块 version-download 事件同构）。
 * @typedef {Object} DownloadProgress
 * @property {string} tag
 * @property {string} platform - x64 | ARM64
 * @property {string} stage - downloading | done | error
 * @property {number} done
 * @property {number} total
 * @property {string} [path] - done 时落盘绝对路径
 * @property {string} [error] - error 时失败原因
 */

/**
 * ExportRecord 导出工件登记（本会话内有效）。多份导出全部在册——
 * 前端经 ListDistroExports 拉全量列表，逐份可「打开位置」。
 * @typedef {Object} ExportRecord
 * @property {string} id
 * @property {string} name - 源发行版名
 * @property {string} path
 * @property {number} size
 * @property {string} at - 落盘时间（与文件名时间戳同源）
 */

/**
 * HostConfDoc .wslconfig 读取载荷。
 * @typedef {Object} HostConfDoc
 * @property {string} path
 * @property {string} text
 * @property {boolean} missing
 * @property {string} networkMode - nat（缺省归一）| bridged | mirrored | unknown
 * @property {string[] | null} warnings
 */

/**
 * InstallDirPref 安装基目录偏好的返回形态：Set=false 表示从未设置过
 * （前端按内置默认 D:\wsl 预填）；Set=true 且 Dir="" 是用户显式选择的
 * "系统默认位置"（装到哪由 WSL 说了算，通常在 C 盘）——三态区分开，
 * "没记得"与"故意留空"不再共用一个空串。
 * @typedef {Object} InstallDirPref
 * @property {boolean} set
 * @property {string} dir
 */

/**
 * OperationOutcome 提权操作统一回执（UAC 取消不算错误，以文案区分）。
 * @typedef {Object} OperationOutcome
 * @property {boolean} success
 * @property {string} message
 */

/**
 * PortProxyView 端口转发总览载荷。
 * @typedef {Object} PortProxyView
 * @property {PortRuleView[] | null} rules
 * @property {ActiveProxy[] | null} foreign - 非本工具登记的现态转发（只展示不管理）
 * @property {boolean} pending - 账本有改动未应用
 * @property {string} networkMode - 宿主网络模式；mirrored 下本机 localhost 直通，通常无需转发
 */

/**
 * PortRule 一条端口转发规则（Hanxi 账本内的期望态）。
 * @typedef {Object} PortRule
 * @property {string} id
 * @property {string} distro
 * @property {number} port - 本机监听端口（TCP）
 * @property {number} guest - guest 目标端口（0=与 Port 相同）
 * @property {string} listen - 本机监听地址（0.0.0.0 或具体 IPv4）
 * @property {boolean} firewall - 同步防火墙入站放行
 * @property {string} [note]
 * @property {boolean} enabled
 */

/**
 * PortRuleView 规则 + 现态对照（前端呈现"已应用/IP 漂移/待应用"）。
 * @typedef {Object} PortRuleView
 * @property {string} id
 * @property {string} distro
 * @property {number} port - 本机监听端口（TCP）
 * @property {number} guest - guest 目标端口（0=与 Port 相同）
 * @property {string} listen - 本机监听地址（0.0.0.0 或具体 IPv4）
 * @property {boolean} firewall - 同步防火墙入站放行
 * @property {string} [note]
 * @property {boolean} enabled
 * @property {boolean} applied
 * @property {string} [activeIP] - netsh 当前指向
 * @property {string} [targetIP] - 解析出的发行版现 IP（漂移对比）
 * @property {boolean} distroRunning
 */

/**
 * ReadinessUpdate 流式体检推送载荷（事件 wsl:readiness）：
 * 前端先渲染全量 pending 骨架，各阶段到达后按 key 落位点亮，done 携带终版报告。
 * 阶段划分与数据源一一对应，互不等待：system=探针、wsl=本机运行时、net=Go 网络探测。
 * @typedef {Object} ReadinessUpdate
 * @property {string} stage - system | wsl | net | done | error
 * @property {readiness$0.CheckItem[] | null} [items]
 * @property {readiness$0.Report | null} [report]
 * @property {string} [error] - stage=error 时的失败说明
 */

/**
 * USBShareEntry 账本里的一条"期望共享"记录（设备 × 目标发行版）。
 * @typedef {Object} USBShareEntry
 * @property {string} id
 * @property {string} busId - 记录时的总线号（重放主匹配键）
 * @property {string} [vid]
 * @property {string} [pid]
 * @property {string} [description] - 设备名快照（账本表可读性）
 * @property {string} distro
 * @property {boolean} enabled
 * @property {string} addedAt
 * @property {string} [lastStatus] - 最近一次重放/操作归因
 * @property {string} [lastAt]
 */

/**
 * UsbView "USB 直通"页签总载荷。
 * @typedef {Object} UsbView
 * @property {boolean} installed
 * @property {string} [version]
 * @property {string} [error] - 取数失败说明（未装不算失败）
 * @property {usbipd$0.Device[] | null} devices
 * @property {USBShareEntry[] | null} ledger
 * @property {boolean} autoEnabled - 开机自动共享总开关（默认关）
 * @property {boolean} replayBusy
 * @property {string} [lastReplay] - 最近一次后台重放摘要
 * @property {string} releasesPage - 引导卡固定跳转地址
 */

/**
 * WslConfDoc /etc/wsl.conf 读取载荷。Missing=true 表示文件不存在（合法空态）。
 * @typedef {Object} WslConfDoc
 * @property {string} name
 * @property {string} text
 * @property {boolean} missing
 * @property {string} wslVersion
 * @property {string[] | null} warnings
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
