// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WslService Wails 绑定服务：WSL 就绪体检（同步 + 流式）、官方版本管理、
 * 白名单提权操作与正规卸载。探测/外呼函数一律以字段注入，单测替换后即可离线断言。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as readiness$0 from "./readiness/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as releases$0 from "./releases/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DisableWslFeatures 提权经 DISM 关闭两个可选功能（虚拟机平台 + WSL 旧功能开关），
 * 这是"把 Windows 自身被 WSL 改变的开关还原回去"的正道；/norestart 交由用户择机重启。
 * @returns {$CancellablePromise<$models.OperationOutcome>}
 */
export function DisableWslFeatures() {
    return $Call.ByID(1923096304);
}

/**
 * DownloadMsi 把官方 MSI 下到系统"下载"文件夹（应用内进度、绝不甩给浏览器）。
 * 单飞：同一时刻仅允许一路下载；tag/文件名走 assetDownloadURL 双重白名单。
 * @param {string} tag
 * @param {string} name
 * @returns {$CancellablePromise<$models.OperationOutcome>}
 */
export function DownloadMsi(tag, name) {
    return $Call.ByID(1814622392, tag, name);
}

/**
 * EnableWslFeatures 提权经 DISM 启用虚拟机平台与旧版 WSL 两个可选功能
 * （与「关闭」对称的状态还原通道；「🚀 一键开启」会在装 WSL 时顺带完成同样动作）。
 * 两条 dism 之间显式传播 $LASTEXITCODE：`;` 链的退出码只反映最后一条命令，
 * 曾因"第一条失败、第二条成功"被整体误报为成功（实机 UAC 窗口一闪而过的漏报事故）。
 * @returns {$CancellablePromise<$models.OperationOutcome>}
 */
export function EnableWslFeatures() {
    return $Call.ByID(3375597247);
}

/**
 * GetReadiness 并发采集探针/网络通道/WSL CLI 现状，返回完整体检报告。
 * 供操作后的同步刷新；首屏渲染走 StartReadiness 流式通道。
 * @returns {$CancellablePromise<readiness$0.Report>}
 */
export function GetReadiness() {
    return $Call.ByID(3730095945);
}

/**
 * GetReleases 拉取 microsoft/WSL 官方发布列表并判定与本机版本的关系。
 * API 被拦（如 api.github.com 对部分云出口 IP 区域封锁 403）时自动降级
 * Atom 订阅源（github.com 域通常畅通），载荷 fallback 标记供前端如实标注。
 * @returns {$CancellablePromise<releases$0.Overview>}
 */
export function GetReleases() {
    return $Call.ByID(1589128305);
}

/**
 * InstallDistro 安装指定在线发行版。ID 不接受裸字符串直传命令——
 * 先实时重取在线清单做白名单校验，杜绝本模块被当作任意参数执行面。
 * @param {string} id
 * @returns {$CancellablePromise<$models.OperationOutcome>}
 */
export function InstallDistro(id) {
    return $Call.ByID(1671179919, id);
}

/**
 * InstallWsl 一键开启：只装 WSL 本体与虚拟机平台，绝不自动装发行版
 * （--install 捆绑模式会把默认 Ubuntu 一起塞进来，与"用户手动挑系统"的
 * 产品语义冲突，故本模块操作面固定走 --no-distribution）。
 * @returns {$CancellablePromise<$models.OperationOutcome>}
 */
export function InstallWsl() {
    return $Call.ByID(1263416846);
}

/**
 * ListOnlineDistros 返回官方在线可安装发行版清单（需 wsl.exe 已具备 --list --online 能力）。
 * @returns {$CancellablePromise<readiness$0.DistroOption[] | null>}
 */
export function ListOnlineDistros() {
    return $Call.ByID(733285110);
}

/**
 * OpenOfficialDocs 打开微软官方 WSL 安装文档。
 * @returns {$CancellablePromise<void>}
 */
export function OpenOfficialDocs() {
    return $Call.ByID(252787703);
}

/**
 * OpenPowerSettings 打开系统「电源」设置页：功能启用/关闭后引导用户自行重启
 * （不代点重启——重启是打断用户工作的高危动作）。
 * @returns {$CancellablePromise<void>}
 */
export function OpenPowerSettings() {
    return $Call.ByID(2051592707);
}

/**
 * OpenReleaseTag 打开指定版本 tag 的发行说明页（tag 必须为纯数字点分版本）。
 * @param {string} tag
 * @returns {$CancellablePromise<void>}
 */
export function OpenReleaseTag(tag) {
    return $Call.ByID(4093249870, tag);
}

/**
 * OpenReleasesPage 打开 microsoft/WSL 官方发布页。
 * @returns {$CancellablePromise<void>}
 */
export function OpenReleasesPage() {
    return $Call.ByID(3762206380);
}

/**
 * RevealDownload 在资源管理器中定位已下载的 MSI；只认本会话自己登记过的路径，
 * 不接受前端传入任意路径（envcheck RevealToolPath 同款红线）。
 * @param {string} tag
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RevealDownload(tag, name) {
    return $Call.ByID(4181564764, tag, name);
}

/**
 * SetDefaultVersion2 将新装发行版默认设为 WSL2。
 * @returns {$CancellablePromise<$models.OperationOutcome>}
 */
export function SetDefaultVersion2() {
    return $Call.ByID(2993198642);
}

/**
 * StartReadiness 异步启动流式体检并立即返回：
 * 三源并发、先到先推（system / wsl / net 阶段逐项落位），全齐后 done 阶段整体收口。
 * 重复调用会静默终止上一轮，永不双跑串扰。
 * @returns {$CancellablePromise<void>}
 */
export function StartReadiness() {
    return $Call.ByID(4117902281);
}

/**
 * UninstallWsl 双形态正规卸载：MSI 系统版走 msiexec /X ProductCode（提权、官方卸载器
 * 自收编其注册表登记），MSIX 用户包走 Remove-AppxPackage（当前用户、无需提权）。
 * 边界如实申明：不强删注册表、不触碰可选功能（另见 DisableWslFeatures）；
 * Lxss 历史发行版注册键属正规卸载器不管辖的残留，巡查后如实报告而非暗中删除。
 * @returns {$CancellablePromise<$models.OperationOutcome>}
 */
export function UninstallWsl() {
    return $Call.ByID(2610190521);
}

/**
 * UpdateWsl 经默认通道更新 WSL 本体。
 * @returns {$CancellablePromise<$models.OperationOutcome>}
 */
export function UpdateWsl() {
    return $Call.ByID(2142344066);
}

/**
 * UpdateWslWebDownload 强制 GitHub 直连更新（商店通道不通时）。
 * @returns {$CancellablePromise<$models.OperationOutcome>}
 */
export function UpdateWslWebDownload() {
    return $Call.ByID(2007508860);
}
