// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as PortScanService from "./portscanservice.js";
export {
    PortScanService
};

export {
    PortStatus
} from "./models.js";

import * as $models from "./models.js";

/**
 * PortResult 单端口探测结果
 * @typedef {$models.PortResult} PortResult
 */

/**
 * PresetGroup 常用预设端口分组
 * @typedef {$models.PresetGroup} PresetGroup
 */

/**
 * ScanProgress 实时扫描进度推送
 * @typedef {$models.ScanProgress} ScanProgress
 */

/**
 * ScanRequest 端口扫描请求
 * @typedef {$models.ScanRequest} ScanRequest
 */

/**
 * ScanSummary 扫描任务最终汇总
 * @typedef {$models.ScanSummary} ScanSummary
 */
