// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PortResult 单端口探测结果
 */
export class PortResult {
    /**
     * Creates a new PortResult instance.
     * @param {Partial<PortResult>} [$$source = {}] - The source object to create the PortResult.
     */
    constructor($$source = {}) {
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {PortStatus}
             */
            this["status"] = PortStatus.$zero;
        }
        if (!("service" in $$source)) {
            /**
             * 识别出的服务名称 (如 http, ssh, mysql, redis)
             * @member
             * @type {string}
             */
            this["service"] = "";
        }
        if (!("banner" in $$source)) {
            /**
             * 抓取到的响应特征或标题 (如 nginx/1.24.0, OpenSSH 8.9)
             * @member
             * @type {string}
             */
            this["banner"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * 原始指纹或证书等详情
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("latencyMs" in $$source)) {
            /**
             * 响应延迟 (ms)
             * @member
             * @type {number}
             */
            this["latencyMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortResult(/** @type {Partial<PortResult>} */($$parsedSource));
    }
}

/**
 * PortStatus 端口开放状态枚举
 * @readonly
 * @enum {string}
 */
export const PortStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PortOpen: "open",
    PortClosed: "closed",
    PortFiltered: "filtered",
};

/**
 * PresetGroup 常用预设端口分组
 */
export class PresetGroup {
    /**
     * Creates a new PresetGroup instance.
     * @param {Partial<PresetGroup>} [$$source = {}] - The source object to create the PresetGroup.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("ports" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ports"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresetGroup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetGroup(/** @type {Partial<PresetGroup>} */($$parsedSource));
    }
}

/**
 * ScanProgress 实时扫描进度推送
 */
export class ScanProgress {
    /**
     * Creates a new ScanProgress instance.
     * @param {Partial<ScanProgress>} [$$source = {}] - The source object to create the ScanProgress.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("scanned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scanned"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("foundOpen" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["foundOpen"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 最新发现的开放端口
             * @member
             * @type {PortResult | null | undefined}
             */
            this["latestPort"] = undefined;
        }
        if (!("isFinished" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFinished"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanProgress}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("latestPort" in $$parsedSource) {
            $$parsedSource["latestPort"] = $$createField6_0($$parsedSource["latestPort"]);
        }
        return new ScanProgress(/** @type {Partial<ScanProgress>} */($$parsedSource));
    }
}

/**
 * ScanRequest 端口扫描请求
 */
export class ScanRequest {
    /**
     * Creates a new ScanRequest instance.
     * @param {Partial<ScanRequest>} [$$source = {}] - The source object to create the ScanRequest.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * 目标 IP 或 域名 (如 127.0.0.1, 192.168.1.1, baidu.com)
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("portRange" in $$source)) {
            /**
             * 端口表达式 (如 "80,443,8080-8090")
             * @member
             * @type {string}
             */
            this["portRange"] = "";
        }
        if (!("timeoutMs" in $$source)) {
            /**
             * 单端口连接超时(ms)，默认 600
             * @member
             * @type {number}
             */
            this["timeoutMs"] = 0;
        }
        if (!("concurrency" in $$source)) {
            /**
             * 并发协程数，默认 30
             * @member
             * @type {number}
             */
            this["concurrency"] = 0;
        }
        if (!("rateLimitMs" in $$source)) {
            /**
             * 单 Worker 发包微延迟(ms)，温和防封模式推荐 5~15ms
             * @member
             * @type {number}
             */
            this["rateLimitMs"] = 0;
        }
        if (!("deepDetect" in $$source)) {
            /**
             * 是否启用轻量指纹探测
             * @member
             * @type {boolean}
             */
            this["deepDetect"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanRequest(/** @type {Partial<ScanRequest>} */($$parsedSource));
    }
}

/**
 * ScanSummary 扫描任务最终汇总
 */
export class ScanSummary {
    /**
     * Creates a new ScanSummary instance.
     * @param {Partial<ScanSummary>} [$$source = {}] - The source object to create the ScanSummary.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("totalPorts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalPorts"] = 0;
        }
        if (!("openPorts" in $$source)) {
            /**
             * @member
             * @type {PortResult[]}
             */
            this["openPorts"] = [];
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanSummary}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("openPorts" in $$parsedSource) {
            $$parsedSource["openPorts"] = $$createField3_0($$parsedSource["openPorts"]);
        }
        return new ScanSummary(/** @type {Partial<ScanSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PortResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
