// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortScanService 暴露给前端的端口扫描服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetPresets 返回常见预设端口组合
 * @returns {$CancellablePromise<$models.PresetGroup[]>}
 */
export function GetPresets() {
    return $Call.ByID(136184176).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * StartScan 启动端口扫描任务（异步），通过 Wails 事件 "portscan:progress" 实时推送进度
 * @param {$models.ScanRequest} req
 * @returns {$CancellablePromise<$models.ScanSummary | null>}
 */
export function StartScan(req) {
    return $Call.ByID(1111344797, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * StopScan 中止指定任务
 * @param {string} taskID
 * @returns {$CancellablePromise<boolean>}
 */
export function StopScan(taskID) {
    return $Call.ByID(2581762785, taskID);
}

// Private type creation functions
const $$createType0 = $models.PresetGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ScanSummary.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
