// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * CCRelease 远程 GitHub Release 中可用的 CC Switch Windows x64 便携版。
 * SHA256 来自 GitHub API 资产 digest（官方计算，完整性校验的第一依据，
 * 比 markeron 的纯字节数校验更强——cc-switch 是后发优势）。
 * @typedef {$models.CCRelease} CCRelease
 */

/**
 * CCVersionInfo 本地已安装的 CC Switch 版本信息。
 * @typedef {$models.CCVersionInfo} CCVersionInfo
 */

/**
 * DownloadProgress 下载过程实时进度。
 * @typedef {$models.DownloadProgress} DownloadProgress
 */
