// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * @typedef {$models.App} App
 */

/**
 * AutostartManager provides cross-platform control over whether the
 * application launches when the user logs in.
 * 
 * Registration takes effect on the next login, not immediately.
 * 
 * Platform behaviour:
 * 
 *   - macOS 13+ (bundled .app):  SMAppService.mainAppService — works for
 *     sandboxed and Mac-App-Store apps, no TCC automation prompt.
 *   - macOS (older or unbundled): a LaunchAgent plist is written to
 *     ~/Library/LaunchAgents/.
 *   - Windows: a value is added under
 *     HKCU\Software\Microsoft\Windows\CurrentVersion\Run.
 *   - Linux: an .desktop file is written to $XDG_CONFIG_HOME/autostart/
 *     (defaulting to ~/.config/autostart/).
 *   - Android / iOS / server builds: ErrAutostartNotSupported.
 * @typedef {$models.AutostartManager} AutostartManager
 */

/**
 * BrowserManager manages browser-related operations
 * @typedef {$models.BrowserManager} BrowserManager
 */

/**
 * ClipboardManager manages clipboard operations
 * @typedef {$models.ClipboardManager} ClipboardManager
 */

/**
 * ContextMenuManager manages all context menu operations
 * @typedef {$models.ContextMenuManager} ContextMenuManager
 */

/**
 * DialogManager manages dialog-related operations
 * @typedef {$models.DialogManager} DialogManager
 */

/**
 * EnvironmentManager manages environment-related operations
 * @typedef {$models.EnvironmentManager} EnvironmentManager
 */

/**
 * EventManager manages event-related operations
 * @typedef {$models.EventManager} EventManager
 */

/**
 * GlobalShortcutManager manages application-wide (global) keyboard shortcuts.
 * 
 * Unlike menu accelerators or [KeyBindingManager] - which only fire while a
 * Wails window has focus - a global shortcut fires regardless of which
 * application is currently focused, as long as the Wails application is
 * running.
 * 
 * Global shortcuts are owned by the application, not by an individual window.
 * Registering the same accelerator twice within the same application is
 * reported as an error and the original binding is preserved; see [Register].
 * 
 * Shortcuts may be registered before [App.Run] is called: the binding with the
 * operating system is then deferred until the application starts.
 * @typedef {$models.GlobalShortcutManager} GlobalShortcutManager
 */

/**
 * KeyBindingManager manages all key binding operations
 * @typedef {$models.KeyBindingManager} KeyBindingManager
 */

/**
 * MenuManager manages menu-related operations
 * @typedef {$models.MenuManager} MenuManager
 */

/**
 * @typedef {$models.ScreenManager} ScreenManager
 */

/**
 * SystemTrayManager manages system tray-related operations
 * @typedef {$models.SystemTrayManager} SystemTrayManager
 */

/**
 * @typedef {$models.WebviewWindow} WebviewWindow
 */

/**
 * WindowManager manages all window-related operations
 * @typedef {$models.WindowManager} WindowManager
 */
