// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvCheckService Wails 绑定服务：本机开发工具链探测、Git/Go/Node.js/Java/Python/.NET
 * 官网版本查询，以及目录内 npm 全局 CLI 工具（Claude Code、Codex 等）的一键安装/升级/卸载。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as detect$0 from "./detect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dotnetversion$0 from "./dotnetversion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitversion$0 from "./gitversion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as goversion$0 from "./goversion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as javaversion$0 from "./javaversion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nodeversion$0 from "./nodeversion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as npmtool$0 from "./npmtool/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pythonversion$0 from "./pythonversion/models.js";

/**
 * Detect 按注册名探测单个工具（预留单卡刷新扩展），未知名返回错误。
 * @param {string} name
 * @returns {$CancellablePromise<detect$0.ToolInfo>}
 */
export function Detect(name) {
    return $Call.ByID(264359636, name);
}

/**
 * DetectAll 并发探测全部已注册工具，同步返回完整列表（前端主入口）。
 * @returns {$CancellablePromise<detect$0.ToolInfo[] | null>}
 */
export function DetectAll() {
    return $Call.ByID(635938415);
}

/**
 * GetDotNetOverview 并发查询本机 .NET 与官方 release-metadata 支持线。
 * 卡片展示版本为 SDK 优先，但通道关系统一使用运行时（Microsoft.NETCore.App）版本比较：
 * 官方 latest-runtime 是运行时编号体系（9.0.19），与 SDK 编号（9.0.100）不可直接比较。
 * @returns {$CancellablePromise<dotnetversion$0.Overview>}
 */
export function GetDotNetOverview() {
    return $Call.ByID(3861305036);
}

/**
 * GetGitForWindowsOverview 并发查询本机 Git 与官网近期稳定版本。
 * @returns {$CancellablePromise<gitversion$0.Overview>}
 */
export function GetGitForWindowsOverview() {
    return $Call.ByID(2627195092);
}

/**
 * GetGoOverview 并发查询本机 Go 与官网 Stable/Oldstable 版本。
 * @returns {$CancellablePromise<goversion$0.Overview>}
 */
export function GetGoOverview() {
    return $Call.ByID(1768501852);
}

/**
 * GetJavaOverview 并发查询本机 Java 与 Eclipse Temurin GA 版本。
 * @returns {$CancellablePromise<javaversion$0.Overview>}
 */
export function GetJavaOverview() {
    return $Call.ByID(3913087858);
}

/**
 * GetNodeOverview 并发查询本机 Node.js 与官网 LTS/Current 版本。
 * @returns {$CancellablePromise<nodeversion$0.Overview>}
 */
export function GetNodeOverview() {
    return $Call.ByID(3661215114);
}

/**
 * GetNpmToolsOverview 汇总目录内各 npm 全局 CLI：本机探测 × registry 最新版关系与安全提醒。
 * @returns {$CancellablePromise<npmtool$0.Overview>}
 */
export function GetNpmToolsOverview() {
    return $Call.ByID(1725161202);
}

/**
 * GetPythonOverview 查询本机 Python、Python.org 最新稳定版及本机受支持版本线。
 * @returns {$CancellablePromise<pythonversion$0.Overview>}
 */
export function GetPythonOverview() {
    return $Call.ByID(520715768);
}

/**
 * InstallNpmTool / UpgradeNpmTool / UninstallNpmTool 经 npm 全局装/升/卸目录工具。
 * 安全红线（与 RevealToolPath 同款）：前端只允许传目录注册 ID（如 claude/codex），
 * 包名与命令参数一律取自后端目录常量，绝不接受前端传入包名/版本/路径字符串；
 * 本模块的"零执行面"哲学自此定向开洞——仅目录白名单内的 npm 命令、隐藏窗口、
 * 不提权、卸载须前端二次确认。长任务进度经 envcheck:npm-tool-* 事件流式回推。
 * @param {string} id
 * @returns {$CancellablePromise<npmtool$0.OperationAccepted>}
 */
export function InstallNpmTool(id) {
    return $Call.ByID(3774688029, id);
}

/**
 * OpenDotNetDownloadPage 使用系统默认浏览器打开固定 .NET 官方下载页。
 * @returns {$CancellablePromise<void>}
 */
export function OpenDotNetDownloadPage() {
    return $Call.ByID(1723745826);
}

/**
 * OpenGitForWindowsDownloadPage 使用系统默认浏览器打开固定官方下载页。
 * @returns {$CancellablePromise<void>}
 */
export function OpenGitForWindowsDownloadPage() {
    return $Call.ByID(410336466);
}

/**
 * OpenGoDownloadPage 使用系统默认浏览器打开固定 Go 官方下载页。
 * @returns {$CancellablePromise<void>}
 */
export function OpenGoDownloadPage() {
    return $Call.ByID(3996844042);
}

/**
 * OpenJavaDownloadPage 使用系统默认浏览器打开固定 Temurin 下载页。
 * @returns {$CancellablePromise<void>}
 */
export function OpenJavaDownloadPage() {
    return $Call.ByID(4290294976);
}

/**
 * OpenNodeDownloadPage 使用系统默认浏览器打开固定 Node.js 官方下载页。
 * @returns {$CancellablePromise<void>}
 */
export function OpenNodeDownloadPage() {
    return $Call.ByID(1571232016);
}

/**
 * OpenPythonDownloadPage 使用系统默认浏览器打开固定 Python 官方下载页。
 * @returns {$CancellablePromise<void>}
 */
export function OpenPythonDownloadPage() {
    return $Call.ByID(3717582198);
}

/**
 * RevealToolPath 在资源管理器中定位该工具探测到的可执行文件。
 * 前端只允许传注册名，路径由后端探测器基于实机 PATH 解析重新获得，
 * 不接受前端传入任意路径字符串，避免本模块被用作任意本地路径探测面。
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RevealToolPath(name) {
    return $Call.ByID(679258983, name);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<npmtool$0.OperationAccepted>}
 */
export function UninstallNpmTool(id) {
    return $Call.ByID(2315520918, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<npmtool$0.OperationAccepted>}
 */
export function UpgradeNpmTool(id) {
    return $Call.ByID(2536657728, id);
}
